NSPR-1550 QSFP LED and Low Speed IO Control Support - XRT phase1
Xilinx/XRT pull request #3984
Opened 2020-09-03 06:38 UTC by xdavidz

Initial version of displaying QSFP port. There are some fixed value due to current U50/55 has limited resource, and my env cannot verify it everything works. With this fix, other team can have a try.

Print HEX value instead of raw. It is simpler.
Will be working on phase2.

2020-09-03 10:26 UTC, gbuildx commented
Build Failed! :(

2020-09-03 14:04 UTC, keryell reviewed
Browsing this uncommented open-source code... What is a reader or a colleague expected to understand from the code? :-(
I do not even understand the description of the commit or PR.
Express yourself! :-)
@stsoe are there some coding guideline for the project?

2020-09-03 16:33 UTC, maxzhen requested changes

2020-09-03 16:33 UTC, maxzhen commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/xmc.c
> +#define CMC_OP_READ_QSFP_DIAGNOSTICS 	0xB
pls add 0xD support per our discussion in the meeting.

2020-09-03 16:33 UTC, maxzhen commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/xmc.c
> +		struct xmc_qsfp_write_op qsfp_write;
don't we want to add them to struct xmc_pkt?

2020-09-03 16:33 UTC, maxzhen commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/xmc.c
> +		return xmc_qsfp_read_hex(xmc, buf, port, lpage, upage);	\
should be just returning raw data, instead of hex, right?

2020-09-03 16:33 UTC, maxzhen commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/xmc.c
> +static int xmc_send_qsfp_pkt(struct xocl_xmc *xmc, struct xmc_qsfp_pkt *qsfp_pkt,
why not just use xmc_send_pkt()?

2020-09-03 16:33 UTC, maxzhen commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/xmc.c
> +static int xmc_recv_qsfp_pkt(struct xocl_xmc *xmc, struct xmc_qsfp_pkt *qsfp_pkt,
why not just call xmc_recv_pkt()?

2020-09-03 18:16 UTC, closed without merging

2020-09-03 18:20 UTC, xdavidz commented
Based on latest meeting, need to convert the sysfs node to raw format.  Close this as it is only support hex format and hex format is not needed.

2020-09-04 09:16 UTC, keryell commented
> Based on latest meeting,

It looks like adding some meeting summary as comments would help this repository. :-)
Otherwise write-only open-source is just a fallacy... :-( @sonals

2020-09-04 15:25 UTC, xdavidz commented
> > Based on latest meeting,
> 
> It looks like adding some meeting summary as comments would help this repository. :-)
> Otherwise write-only open-source is just a fallacy... :-( @sonals

This was closed as we have newer design. If you have question please @me directly.