ERT 3.0 with data flow mode
Xilinx/XRT pull request #4044
Opened 2020-09-14 07:12 UTC by chienwei-lan

2020-09-14 10:06 UTC, gbuildx commented
Build Passed!

2020-09-14 16:09 UTC, maxzhen requested changes

2020-09-14 16:09 UTC, maxzhen commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/ert_user.c
> +	if (major > 3) {
isn't ert_user for ert v2 only?

2020-09-14 17:04 UTC, chienwei-lan commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/ert_user.c
> +	if (major > 3) {
yes, you are right

2020-09-15 06:52 UTC, mamin506 reviewed
Overall, this looks good. Just confusing when and how to create ert_user subdev for SSv2 platform.

2020-09-15 06:52 UTC, mamin506 commented on src/runtime_src/core/pcie/driver/linux/xocl/xocl_fdt.c
> - 	},
I think we still need XOCL_SUBDEV_ERT_USER on SSv2 shell. Am I right?

2020-09-15 17:11 UTC, gbuildx commented
Build Passed!

2020-09-16 03:52 UTC, maxzhen approved these changes

2020-09-16 19:41 UTC, gbuildx commented
Build Passed!

2020-09-16 21:05 UTC, mamin506 approved these changes

2020-09-16 23:53 UTC, merged