XMA2 Timeout fix. CR-1072041
Xilinx/XRT pull request #4114
Opened 2020-09-28 17:11 UTC by sarab96

CU cmd Timeout fix. timeout of cu hangs or soft kernel crashes.
CR-1072041

2020-09-28 19:30 UTC, gbuildx commented
Build Passed!

2020-09-29 15:16 UTC, stsoe requested changes
Please add comments explaining what it going on.  The functions are too long to review without comments.

2020-09-29 17:09 UTC, sarab96 commented
Done
> Please add comments explaining what it going on. The functions are too long to review without comments.

2020-09-29 19:43 UTC, gbuildx commented
Build Passed!

2020-09-29 20:22 UTC, stsoe approved these changes
The code is still too poorly organized to review probably , I think this is legacy code though.

2020-09-29 20:23 UTC, merged