enable GUI for 3rd party simulator - DC
Xilinx/XRT pull request #4124
Opened 2020-09-29 10:51 UTC by ramyam-xilinx

Reviewer : venkatp

2020-09-29 11:41 UTC, gbuildx commented
Build Passed!

2020-09-29 16:28 UTC, keryell requested changes
That looks good but I can see a few simplifications

2020-09-29 16:28 UTC, keryell commented on src/runtime_src/core/pcie/emulation/hw_em/generic_pcie_hal2/shim.h
> +      void writeNewSimulateScript (const std::string& simPath, const std::string& simulatorName );
```suggestion
      void writeNewSimulateScript (const std::string& simPath, const std::string& simulatorName);
```

2020-09-29 16:28 UTC, keryell commented on src/runtime_src/core/pcie/emulation/hw_em/generic_pcie_hal2/shim.cxx
> +    return std::string((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());
Useless `()`.
Also you can probably simplify this to
```suggestion
    return { std::istreambuf_iterator<char>(file), std::istreambuf_iterator<char>() };
```

2020-09-29 16:28 UTC, keryell commented on src/runtime_src/core/pcie/emulation/hw_em/generic_pcie_hal2/shim.cxx
> +        std::transform(simulatorType.begin(), simulatorType.end(), simulatorType.begin(), ::tolower);
Do not use random C code in C++
```suggestion
        std::transform(simulatorType.begin(), simulatorType.end(), simulatorType.begin(), std::tolower);
```
and add `#include <cctype>` (while sorting the header includes...).

2020-09-30 13:14 UTC, gbuildx commented
Build Failed! :(

2020-09-30 13:39 UTC, gbuildx commented
Build Failed! :(

2020-09-30 14:04 UTC, gbuildx commented
Build Failed! :(

2020-10-06 05:55 UTC, xilinxgitops commented
retest this please

2020-10-06 08:48 UTC, gbuildx commented
Build Passed!

2020-10-06 08:56 UTC, merged