CR-1077438 ASTeR TC 7.02 - Intermittent firewall trip during xbutil validate (u50 base4)
Xilinx/XRT pull request #4127
Opened 2020-09-29 17:47 UTC by chienwei-lan

2020-09-29 18:52 UTC, maxzhen requested changes

2020-09-29 18:52 UTC, maxzhen commented on src/runtime_src/ert/scheduler/scheduler_v30.cpp
> +              write_reg(slot.slot_addr,0x0); // clear
why do we still need this change? shouldn't the one line change below just do it?

2020-09-29 20:32 UTC, gbuildx commented
Build Passed!

2020-09-29 21:07 UTC, mamin506 approved these changes

2020-09-29 22:13 UTC, maxzhen approved these changes

2020-09-30 03:34 UTC, gbuildx commented
Build Passed!

2020-09-30 03:37 UTC, merged