Update xrtDeviceGetXclbinUUID in xrt_device.h
Xilinx/XRT pull request #4184
Opened 2020-10-07 23:53 UTC by AlphaBu

No return value for xrtDeviceGetXclbinUUID

2020-10-07 23:54 UTC, gbuildx commented
Can one of the admins verify this patch?

2020-10-08 16:51 UTC, stsoe requested changes
Let's change to return status

2020-10-12 04:10 UTC, sonals commented
ok to test

2020-10-12 05:05 UTC, gbuildx commented
Build Passed!

2020-10-15 20:25 UTC, stsoe commented
Thank you for pointing out the inconsistency.  I am replacing this PR with #4246

2020-10-15 20:25 UTC, closed without merging