CR-1075543 Add support for AIE dynamic profiling
Xilinx/XRT pull request #4212
Opened 2020-10-10 00:49 UTC by larry9523

This PR addresses the following issues and features
1. Fix failure of xclCloseContext that returns non-zero as successful by revert return value to 0
2. Added all other remaining 3 profiling options so that we have a full support of the 4 profiling options supported
   enum xrtProfilingOption {
      IO_TOTAL_STREAM_RUNNING_TO_IDLE_CYCLE = 0,
      IO_STREAM_START_TO_BYTES_TRANSFERRED_CYCLES,
      IO_STREAM_START_DIFFERENCE_CYCLES,
      IO_STREAM_RUNNING_EVENT_COUNT
   };
3. Re commit the "Use block mem access when read/update rtp". This was merged by https://github.com/Xilinx/XRT/pull/4093 but then reverted by https://github.com/Xilinx/XRT/pull/4096. The issue underline has been fixed and tested. We can now safely use the block mem interfaces.

@xdavidz you are welcome to review other changes, but please particularly take a look at the change in zocl_xclbin.c

2020-10-10 03:42 UTC, xdavidz approved these changes

2020-10-10 03:58 UTC, gbuildx commented
Build Passed!

2020-10-10 21:12 UTC, stsoe requested changes

2020-10-10 21:12 UTC, stsoe commented on src/runtime_src/core/edge/user/aie/aie.cpp
> +  int handleId = eventRecords.size();
Here definitely auto should be used.  int and return type doesn't even match in this case.

2020-10-10 21:12 UTC, stsoe commented on src/runtime_src/core/edge/user/aie/aie.cpp
> +                { shim_tile, Resources::pl_module, Resources::stream_switch_event_port, (size_t)eventPortId } } } );
Return type of various APIs and how these are used don't seem to agree very well.  Why are there so many casts?  Also C-style casting is not good.  Please use static_cast, more type yes, but more incentive to fix and easier to locate bad code.

2020-10-10 21:12 UTC, stsoe commented on src/runtime_src/core/edge/user/aie/aie.cpp
> +      handle = handleId;
Is this code duplication from earlier around ~492?
Functions in this file could benefit a lot from refactoring, they are much too long and completely without comments.  Impossible to guess what's going on.

2020-10-10 21:12 UTC, stsoe commented on src/runtime_src/core/edge/user/aie/aie.cpp
> +start_profiling_diff_cycles(const std::string& port1_name, const std::string& port2_name)
Please refactor.  This function is way too long

2020-10-10 21:12 UTC, stsoe commented on src/runtime_src/core/edge/user/aie/aie.cpp
> +  int handle = -1;
Move closer to where it is first needed.

2020-10-10 21:12 UTC, stsoe commented on src/runtime_src/core/edge/user/aie/aie.cpp
> +  } else {
new line missing

2020-10-12 16:26 UTC, larry9523 commented
Hi @stsoe, The AIE profiling code is a temporary solution for 2020.2 so that we have full profiling support in libadf_api_xrt. In next release we will revisit the architecture, with a solid AIE resource manager (in AIE driver or somewhere), these code will be entirely refactored, probably in XDP.

2020-10-12 16:30 UTC, stsoe commented
Merging under the assumption that this code is temporary.

2020-10-12 16:30 UTC, merged