CR-1075730 softkernel crash when gdb attached
Xilinx/XRT pull request #4215
Opened 2020-10-10 19:32 UTC by xdavidz

softkernel to support xclSKOpenContext and xslSKCloseContext

Still testing, using pipeline to find basic issues.

2020-10-10 20:48 UTC, gbuildx commented
Build Failed! :(

2020-10-12 00:56 UTC, gbuildx commented
Build Failed! :(

2020-10-12 05:36 UTC, gbuildx commented
Build Failed! :(

2020-10-12 07:16 UTC, gbuildx commented
Build Passed!

2020-10-12 17:24 UTC, mamin506 approved these changes

2020-10-12 18:38 UTC, larry9523 commented on src/runtime_src/core/common/drv/include/kds_core.h
> + * @sk_cu_id: soft kernel cu index, default is -1
how can u32 type be default -1?

2020-10-12 18:39 UTC, larry9523 commented on src/runtime_src/core/edge/drm/zocl/include/sched_exec.h
> + * @sk_cu_id: soft kernel cu index, default is -1
see above

2020-10-12 18:40 UTC, larry9523 commented on src/runtime_src/core/edge/drm/zocl/zocl_drv.c
> +		zocl_fini_soft_kernel_cu(zdev, client->sk_cu_id);
you probably don't need {} for a single line after "if"

2020-10-12 18:46 UTC, larry9523 commented on src/runtime_src/core/edge/drm/zocl/zocl_ioctl.c
> +		((struct sched_client_ctx *)filp->driver_priv)->sk_cu_id = INVALID_CU_ID;
Do we need mutex protection here? Or are we relying on softkernel framework to enforce it? If latter, which is not very reliable, we should at least put some comments here

2020-10-12 19:15 UTC, larry9523 commented on src/runtime_src/core/edge/drm/zocl/zocl_sk.c
> +
Operation after this should be protected by mutex

2020-10-12 19:15 UTC, larry9523 requested changes
Minor changes requested

2020-10-13 07:22 UTC, gbuildx commented
Build Passed!

2020-10-14 22:37 UTC, houlz0507 commented on src/runtime_src/core/edge/drm/zocl/zocl_kds.c
> +		break;
Why do we introduce OPEN/CLOSE here but not use ALLOC_CTX and FREE_CTX?

2020-10-14 22:45 UTC, houlz0507 commented on src/runtime_src/core/edge/drm/zocl/zocl_sk.c
> +	scu = NULL;
you need to set sk->sk_cu[cu_idx] to NULL here.

2020-10-15 02:45 UTC, xdavidz commented
Not an appropriate fix, based on testing, skd will open/close fd multiple times without close the softkernel. The softkernel creataion is done by another ioctl. Thus, handling this in open/close is over kill.

2020-10-15 02:45 UTC, closed without merging