refactor-1
Xilinx/XRT pull request #4262
Opened 2020-10-17 20:31 UTC by sarab96

refactor of code

2020-10-17 22:01 UTC, stsoe requested changes
These are simple changes for the better.  Please consider my comments.

2020-10-17 22:18 UTC, gbuildx commented
Build Passed!

2020-10-18 16:03 UTC, sarab96 commented on src/xma/src/xmaplugin/xma_utils.cpp
> +int32_t check_xma_session(XmaSession &s_handle) {
Agree. Done

2020-10-18 16:03 UTC, sarab96 commented on src/xma/src/xmaplugin/xma_utils.cpp
> +    XmaHwSessionPrivate *priv1 = (XmaHwSessionPrivate*) s_handle.hw_session.private_do_not_use;
Yes agree. Done

2020-10-18 16:06 UTC, sarab96 commented on src/xma/src/xmaplugin/xma_utils.cpp
> +    if (s_handle.session_signature != (void*)(((uint64_t)priv1) | ((uint64_t)priv1->reserved))) {
Agreed. Done

2020-10-18 17:04 UTC, gbuildx commented
Build Passed!

2020-10-19 15:17 UTC, stsoe approved these changes

2020-10-19 15:17 UTC, merged