Added support for HBM backward compatibility of existing application
Xilinx/XRT pull request #4267
Opened 2020-10-19 07:44 UTC by saifuddin-xilinx

- This supports the backward compatibility of the existing applications.
- Application code with EXT pointer will still work with this change. 
- It is advisable not to use EXT pointer in the application.

2020-10-19 09:32 UTC, gbuildx commented
Build Failed! :(

2020-10-19 13:08 UTC, gbuildx commented
Build Passed!

2020-10-19 19:13 UTC, stsoe approved these changes
Changes are good.  
Before we merge, let me run standard board tests.

2020-10-19 21:03 UTC, stsoe commented
Tests are passing just fine.

2020-10-19 23:09 UTC, rozumx requested changes
There are several array dependencies and DRC checks are being bypassed which greatly concerns me.  

Please do schedule a meeting with Soren and myself to review the use-cases and possible solutions.

2020-10-19 23:09 UTC, rozumx commented on src/runtime_src/tools/xclbinutil/XclBinUtilities.cxx
> +      validateMemoryBankGroupEntries((unsigned int) memTopology.size(), groupTopology, groupConnectivity);
The reason why this validation was done at the end was to validate the contents and connections of the two GROUP sections.  Now that is no longer the case.

Why couldn't the validation method be updated?

2020-10-19 23:09 UTC, rozumx commented on src/runtime_src/tools/xclbinutil/XclBinUtilities.cxx
> +      for (auto & connection : connectivity) {
So now we have duplicate entries.

Couldn't find it, how did you make sure that the indexes GROUP memory indexes are correct?  Are you assuming that the memory indexes are at the start.  If so this causes a hard-coded binding which should NOT be there.

Also, could you refer us to the various use-cases that need this data.  

Again, this looks very dangerous.

2020-10-19 23:09 UTC, rozumx commented on src/runtime_src/xocl/core/device.cpp
> +      for (int idx=mask.size() - 1; idx >= 0; --idx) {
There should not be any order dependencies.

2020-10-20 18:53 UTC, rozumx approved these changes
After a discussion with Soren, Saif, Vamshi, and Uday we understand why these changes were made.  In addition, where we are in the release and to minimize the release risk, these change will remain as is.  

Post 2020.2, we all committed to re-examining how the grouping is performed and to create a more robust solution.

2020-10-20 18:56 UTC, chvamshi-xilinx approved these changes

2020-10-20 18:59 UTC, merged