allow enable ert only when ert subdev exist
Xilinx/XRT pull request #4288
Opened 2020-10-21 19:20 UTC by mamin506

Since ERT is by default enable in xrt.ini and U.2 shell doesn't support ERT, it would cause kernel panic without this fix.

2020-10-21 21:01 UTC, maxzhen requested changes
please investigate why we don't have ert enabled on u.2. it does not sound right.

2020-10-21 23:05 UTC, houlz0507 approved these changes

2020-10-21 23:06 UTC, mamin506 commented
> please investigate why we don't have ert enabled on u.2. it does not sound right.

This is because "XOCL_DEVINFO_ERT_USER" is missed in USER_RES_DSA52_U2. I added it and test on Raptor2 and legacy shell.

2020-10-22 01:40 UTC, gbuildx commented
Build Passed!

2020-10-22 05:14 UTC, maxzhen approved these changes

2020-10-22 07:36 UTC, gbuildx commented
Build Passed!

2020-10-22 09:07 UTC, gbuildx commented
Build Passed!

2020-10-25 00:27 UTC, merged