CR-1082043 uart over PCIe won't work with 115200
Xilinx/XRT pull request #4363
Opened 2020-10-30 18:20 UTC by chienwei-lan

2020-10-30 19:35 UTC, maxzhen requested changes

2020-10-30 19:35 UTC, maxzhen commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/ulite.c
> +	mutex_unlock(&pdata->lock);
better include the two uart_out32 in the mutex lock to avoid race.

2020-10-30 19:35 UTC, maxzhen commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/ulite.c
> +	mutex_unlock(&pdata->lock);
ditto.

2020-10-30 20:54 UTC, maxzhen approved these changes

2020-10-30 21:58 UTC, gbuildx commented
Build Passed!

2020-10-30 23:39 UTC, gbuildx commented
Build Failed! :(

2020-10-31 06:40 UTC, xilinxgitops commented
retest this please

2020-10-31 07:25 UTC, xilinxgitops commented
retest this please

2020-10-31 08:37 UTC, gbuildx commented
Build Passed!

2020-10-31 19:07 UTC, merged