zocl driver version
Xilinx/XRT pull request #4374
Opened 2020-11-02 01:23 UTC by sarab96

zocl version update for 2020
This version is used by lspci, etc

2020-11-02 02:46 UTC, gbuildx commented
Build Passed!

2020-11-02 18:49 UTC, maxzhen requested changes
do we expect any change to zocl to update driver date? when do we want to update driver major?

2020-11-02 20:06 UTC, sarab96 commented
zocl had large changes for soft kernel support and I think date was not bumped up for that. Now for U30 there are some changes.
So I think driver date can be changed now. Release, major, minor can be changed now to match current XRT release as it was not changed in earlier releases.

2020-11-02 20:10 UTC, maxzhen commented
driver's major is 2020, minor is 2 and patch leve is 1, how does it match XRT's release version, which is something like 2.9.0 here? Can we make it updated automatically as xocl?

2020-11-04 17:25 UTC, larry9523 commented
I think we have agreement that we should report zocl vsersion as "<xrt version>:<commit number>"

2020-11-04 17:36 UTC, larry9523 reviewed
see comment

2020-11-04 19:12 UTC, sarab96 commented
Closing this one. New changes made in new PR: https://github.com/Xilinx/XRT/pull/4398

2020-11-04 19:12 UTC, closed without merging