Load legacy scheduler bin (sched.bin) when the firmware branch name is legacy
Xilinx/XRT pull request #4377
Opened 2020-11-02 13:18 UTC by rajkumar-xilinx

Signed-off-by: Rajkumar Rampelli <rajkumar@xilinx.com>

2020-11-02 15:03 UTC, gbuildx commented
Build Passed!

2020-11-02 16:13 UTC, maxzhen requested changes
Where does this "legacy" come from and why it can't be "sched.bin"?

2020-11-02 19:17 UTC, chvamshi-xilinx commented
> Where does this "legacy" come from and why it can't be "sched.bin"?

Hi @maxzhen , There is no way to make firmware_branch_version to empty string in DTB. When this value is "empty string" in partition.dts, it is becoming some junk characters in the dtb.   Thatswhy Platform team is decided to add 
"legacy" for the firmware_branch_version in the partition metadata so that XRT can load the sched.bin.

We never hit this case as XRT tries to load scheduler which is in XRT installation area first.  If it doesn't find proper scheduler in XRT installation area,  it loads a scheduler which is part of xsabin. As this xsabin is generated for 0RP shell as there is no scheduler inside xsabin.

2020-11-02 19:31 UTC, maxzhen approved these changes

2020-11-02 19:31 UTC, maxzhen commented
> 
> 
> > Where does this "legacy" come from and why it can't be "sched.bin"?
> 
> Hi @maxzhen , There is no way to make firmware_branch_version to empty string in DTB. When this value is "empty string" in partition.dts, it is becoming some junk characters in the dtb. Thatswhy Platform team is decided to add
> "legacy" for the firmware_branch_version in the partition metadata so that XRT can load the sched.bin.
> 
> We never hit this case as XRT tries to load scheduler which is in XRT installation area first. If it doesn't find proper scheduler in XRT installation area, it loads a scheduler which is part of xsabin. As this xsabin is generated for 0RP shell as there is no scheduler inside xsabin.

OK, I see. Thanks for explaining.

2020-11-02 19:32 UTC, chienwei-lan approved these changes

2020-11-03 05:50 UTC, chvamshi-xilinx approved these changes

2020-11-03 10:39 UTC, merged