CR-1082221 add icap controller endpoint support for Raptor2 0RP shell
Xilinx/XRT pull request #4391
Opened 2020-11-03 08:43 UTC by rajkumar-xilinx

-XRT will confirm if the shell is flat shell when the platform doesn't have isolate_ulp endpoint defined in the partition metadata.
-Add icap controller programming endpoint support for raptor2 0RP flow

Signed-off-by: Rajkumar Rampelli <rajkumar@xilinx.com>

2020-11-03 09:25 UTC, gbuildx commented
Build Failed! :(

2020-11-03 10:26 UTC, gbuildx commented
Build Failed! :(

2020-11-03 11:14 UTC, chvamshi-xilinx requested changes

2020-11-03 11:19 UTC, chvamshi-xilinx approved these changes

2020-11-03 12:29 UTC, gbuildx commented
Build Failed! :(

2020-11-04 01:20 UTC, stsoe commented
retest this please

2020-11-04 07:38 UTC, gbuildx commented
Build Passed!

2020-11-04 07:54 UTC, maxzhen approved these changes

2020-11-04 08:29 UTC, merged

2020-11-04 08:31 UTC, chvamshi-xilinx commented
Sorry, I didnt observe that this change is still need to be reviewed by @houlz0507.

2020-11-04 08:33 UTC, chvamshi-xilinx commented
@houlz0507 , please review the change and give your feedback. @rajkumar-xilinx , can you please incorporate his feedback in another PR,
Sorry for the confusion.

2020-11-04 15:57 UTC, maxzhen commented
> 
> 
> Sorry, I didnt observe that this change is still need to be reviewed by @houlz0507.

@houlz0507 is mostly familiar with code in this area. This is why I added him for reviewing this change.

2020-11-04 16:30 UTC, houlz0507 reviewed
No comment, approved.

2020-11-04 16:32 UTC, chvamshi-xilinx commented
Thanks @maxzhen & @houlz0507 :-)