Fix for CR 1080843 and add warning message for trace buffer full in HAL Device Offload Plugin
Xilinx/XRT pull request #4413
Opened 2020-11-05 21:58 UTC by IshitaGhosh

2020-11-05 23:22 UTC, stsoe requested changes

2020-11-05 23:22 UTC, stsoe commented on src/runtime_src/core/common/config_reader.h
> +  std::string value = detail::get_string_value("Debug.data_transfer_trace","off");
Why was static removed?

2020-11-06 03:22 UTC, gbuildx commented
Build Passed!

2020-11-06 03:51 UTC, IshitaGhosh commented on src/runtime_src/core/common/config_reader.h
> +  std::string value = detail::get_string_value("Debug.data_transfer_trace","off");
I have shared details over email.

2020-11-06 04:10 UTC, pgschuey approved these changes
changes look good

2020-11-06 21:57 UTC, stsoe approved these changes

2020-11-06 22:34 UTC, gbuildx commented
Build Passed!

2020-11-08 02:19 UTC, merged