cherry pick timeout fix, DMA checks
Xilinx/XRT pull request #4463
Opened 2020-11-15 01:29 UTC by sarab96

cherry pick XMA2 commits to 2020.1
As per CR from video team

2020-11-15 04:38 UTC, stsoe requested changes
Please follow the conventions and title pull request with the CR number, per Scale-X
https://confluence.xilinx.com/display/XSW/Scale-X

2020-11-15 11:47 UTC, gbuildx commented
Build Failed! :(

2020-11-16 18:20 UTC, sarab96 commented
retest this please

2020-11-16 22:28 UTC, gbuildx commented
Build Failed! :(

2020-11-17 14:00 UTC, sarab96 commented
retest this please

2020-11-17 18:57 UTC, merged

2020-11-17 19:09 UTC, gbuildx commented
Build Failed! :(