Cherry pick fixes from master
Xilinx/XRT pull request #4549
Opened 2020-12-10 21:03 UTC by AShivangi

2020-12-10 21:13 UTC, arpitxilinx approved these changes

2020-12-10 22:10 UTC, stsoe requested changes
Hi @AShivangi   For tracking purposes can you please make sure CR-1082806 is blessed by Sonal for merge to 2020.2 release branch?

2020-12-10 22:58 UTC, AShivangi commented
Hi @sonals, can you please review this PR for 2020.2 branch? These fixes are needed for msft

2020-12-10 23:07 UTC, gbuildx commented
Build Passed!

2020-12-15 19:15 UTC, sonals approved these changes

2020-12-15 19:16 UTC, merged