Fix missed std:: for streampos
Xilinx/XRT pull request #4559
Opened 2020-12-14 21:02 UTC by matwey

`streampos` is a member of `std::` and that should be properly specified in order
to comply the standard.

2020-12-14 21:04 UTC, gbuildx commented
Can one of the admins verify this patch?

2020-12-14 21:14 UTC, maxzhen commented
ok to test

2020-12-14 21:18 UTC, AShivangi approved these changes

2020-12-14 22:28 UTC, gbuildx commented
Build Passed!

2020-12-16 14:56 UTC, stsoe requested changes
Let be more modern and use `auto` here; the type really is pretty clear from tellg().

2020-12-17 09:10 UTC, gbuildx commented
Build Failed! :(

2020-12-17 10:44 UTC, gbuildx commented
Build Passed!

2020-12-17 15:18 UTC, merged