Fixed the Coverity issues reported
Xilinx/XRT pull request #4612
Opened 2021-01-11 08:02 UTC by venkatp-xilinx

Fixed the Coverity issues reported in the mbscheduler_hw_emu module of HW Emulation

2021-01-11 09:02 UTC, gbuildx commented
Build Passed!

2021-01-11 20:34 UTC, stsoe requested changes

2021-01-11 20:34 UTC, stsoe commented on src/runtime_src/core/pcie/emulation/hw_em/generic_pcie_hal2/mbscheduler_hwemu.cxx
> +        this->run_cnt = 0;
Please use initialization: https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rc-initialize
Or better yet, use in-class initializers: https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rc-in-class-initializer

2021-01-11 20:34 UTC, stsoe commented on src/runtime_src/core/pcie/emulation/hw_em/generic_pcie_hal2/mbscheduler_hwemu.cxx
> +        delete exec;
This looks like a misplaced delete.  Please use std::unique_ptr for the resources .

2021-01-21 04:21 UTC, closed without merging

2021-01-21 04:22 UTC, venkatp-xilinx commented
We can remove this pull request, these changes are handled from other PR.