VITIS-1481 Alveo Feature: QSFP - Full QSFP I2C Read/Write Support and…
Xilinx/XRT pull request #4686
Opened 2021-02-03 06:52 UTC by xdavidz

Initial code to support qsfp i2c. Using pipeline to check any blocking issue. Will submit for code review once the design is finalized.

2021-02-03 07:42 UTC, gbuildx commented
Build Passed!

2021-02-24 09:53 UTC, gbuildx commented
Build Passed!

2021-03-04 21:24 UTC, gbuildx commented
Build Passed!

2021-03-08 08:51 UTC, gbuildx commented
Build Passed!

2021-03-08 16:55 UTC, maxzhen requested changes

2021-03-08 16:55 UTC, maxzhen commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/xmc.c
> +/* depracted */
Can we just remove this?

2021-03-08 17:25 UTC, xdavidz commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/xmc.c
> +/* depracted */
> Can we just remove this?

Removed.

2021-03-08 17:59 UTC, maxzhen approved these changes

2021-03-08 18:16 UTC, gbuildx commented
Build Passed!

2021-03-08 18:28 UTC, houlz0507 approved these changes

2021-03-12 05:47 UTC, merged