CR-1087204 fix for p2p_fpga2fpga data transfer
Xilinx/XRT pull request #4693
Opened 2021-02-04 07:33 UTC by madhusud-xilinx

fix for p2p_fpga2fpga data transfer

2021-02-04 07:34 UTC, gbuildx commented
Can one of the admins verify this patch?

2021-02-04 17:21 UTC, maxzhen commented
ok to test

2021-02-04 17:47 UTC, stsoe requested changes
Feel free to ignore comments under the pretense that this is supposed to resemble linux driver code as closely as possible.

2021-02-04 17:47 UTC, stsoe commented on src/runtime_src/core/pcie/emulation/hw_em/generic_pcie_hal2/mbscheduler_hwemu.cxx
> +        uint64_t dst_addr = -1;
It would be great if these declarations were moved to the point where they are defined.

2021-02-04 17:47 UTC, stsoe commented on src/runtime_src/core/pcie/emulation/hw_em/generic_pcie_hal2/mbscheduler_hwemu.cxx
> +        xclemulation::drm_xocl_bo* dBo = device->xclGetBoByHandle(scmd->dst_bo_hdl);
Be consistent.  Don't mix camelCase and non camelCase.  I think you should do 
```
auto src_bo = ...;
auto dst_bo = ...;
```

2021-02-04 17:47 UTC, stsoe commented on src/runtime_src/core/pcie/emulation/hw_em/generic_pcie_hal2/mbscheduler_hwemu.cxx
> +            dst_addr = dBo->base;
Move after 2265 where we know src_bo and dst_bo re valid and then either use `src_bo->base` in place of src_addr (ditto dst_bo->base) or create the local variables closest to where they are first used.

2021-02-04 17:47 UTC, stsoe commented on src/runtime_src/core/pcie/emulation/hw_em/generic_pcie_hal2/mbscheduler_hwemu.cxx
> +        convert_execbuf(xcmd);
Looks like the return value is ignored?  This is why error handling with return values is bad, return codes are ignored by default.  It's better to use exceptions in c++ code, but I realize this is mostly copied from driver code where there are no exceptions so it's easier to stay close to that code.  That also goes for some of the other comments.

2021-02-04 17:47 UTC, stsoe commented on src/runtime_src/core/pcie/emulation/hw_em/generic_pcie_hal2/mbscheduler_hwemu.cxx
> +        }
Better no braces for single statement, just follow the single statement with a new line.

2021-02-04 17:47 UTC, stsoe commented on src/runtime_src/core/pcie/emulation/hw_em/generic_pcie_hal2/mbscheduler_hwemu.cxx
> +        for (unsigned int i = exec->num_cus - exec->num_cdma; i < exec->num_cus; i++)
probably better to auto here to match the type of exec->num_cus and num_cdma

2021-02-04 18:07 UTC, gbuildx commented
Build Passed!

2021-02-05 12:56 UTC, gbuildx commented
Build Failed! :(

2021-02-08 08:59 UTC, dayeh-xilinx commented
retest this please

2021-02-08 13:47 UTC, gbuildx commented
Build Passed!

2021-02-09 15:48 UTC, stsoe approved these changes

2021-02-09 15:49 UTC, merged