CR-1088262: fix grp index issue for use host mem ptr in edge
Xilinx/XRT pull request #4732
Opened 2021-02-15 12:43 UTC by Himanshu-xilinx

2021-02-15 13:03 UTC, chvamshi-xilinx approved these changes
Looks good.

2021-02-15 13:36 UTC, gbuildx commented
Build Passed!

2021-02-15 23:28 UTC, stsoe requested changes
Please update description with what was the root cause and why the fixes in this PR fixes it.

2021-02-16 16:31 UTC, larry9523 approved these changes
The only thing is missing is the copyright year should be updated. But if this is urgent, we can fix it with a later push.

2021-02-16 19:52 UTC, stsoe approved these changes

2021-02-16 19:53 UTC, merged