Check xocl_ert_on while probe
Xilinx/XRT pull request #4852
Opened 2021-03-04 22:54 UTC by chienwei-lan

2021-03-05 04:08 UTC, gbuildx commented
Build Passed!

2021-03-05 05:00 UTC, gbuildx commented
Build Passed!

2021-03-05 18:39 UTC, mamin506 requested changes

2021-03-05 18:39 UTC, mamin506 commented on src/runtime_src/core/pcie/driver/linux/xocl/xocl_drv.h
> +	(XOCL_DSA_IS_VERSAL(xdev) || XOCL_DSA_IS_MPSOC(xdev))
Please use "!XOCL_DSA_MB_SCHE_OFF(xdev) && (XOCL_DSA_IS_VERSAL(xdev) || XOCL_DSA_IS_MPSOC(xdev)
).
As Brain explained, MB_SCHE_OFF should be the top level switch for development or debug purpose.

2021-03-05 22:25 UTC, mamin506 approved these changes
I see there are two minor changes in ert_user.c. This remind me that we need more clean up in ert_cfg_host() and ert_cfg_cmd(). But you can do that in a separate PR.

Like:
1. local variable ert is not used.
2. There are still XOCL_DSA_IS_VERSAL(xdev) and XOCL_DSA_IS_MPSOC(xdev)

2021-03-05 22:35 UTC, xuhz approved these changes

2021-03-06 01:02 UTC, gbuildx commented
Build Passed!

2021-03-06 02:40 UTC, gbuildx commented
Build Passed!

2021-03-06 02:45 UTC, merged