CR-1091194 fix mem leak in probe
Xilinx/XRT pull request #4891
Opened 2021-03-10 11:38 UTC by Himanshu-xilinx

2021-03-10 11:40 UTC, chvamshi-xilinx approved these changes

2021-03-10 15:44 UTC, stsoe requested changes

2021-03-10 15:49 UTC, stsoe commented
Also, is the PR really meant for 2020.2?  Or did you mean 2020.2_PU1?

2021-03-10 17:09 UTC, gbuildx commented
Build Passed!

2021-03-10 19:41 UTC, chvamshi-xilinx commented
> Also, is the PR really meant for 2020.2? Or did you mean 2020.2_PU1?

Yes Soren. This is needed in 2020.2 for SOM use case.

2021-03-22 08:00 UTC, closed without merging

2021-03-22 08:00 UTC, chvamshi-xilinx commented
change is cherry-picked from master already,