PS kernel return code changes
Xilinx/XRT pull request #5024
Opened 2021-03-30 19:51 UTC by sarab96

New API implementation
PS kernel return code changes

2021-03-30 20:01 UTC, stsoe requested changes

2021-03-31 03:13 UTC, gbuildx commented
Build Passed!

2021-03-31 17:40 UTC, sarab96 commented on src/xma/src/xmaplugin/xmaplugin.cpp
> +    XmaHwSessionPrivate *priv1 = (XmaHwSessionPrivate*) s_handle.hw_session.private_do_not_use;
done

2021-03-31 17:40 UTC, sarab96 commented on src/xma/src/xmaplugin/xmaplugin.cpp
> +        *num_cu_errors = num_cu_objs; //Default
Agree. Done

2021-03-31 22:42 UTC, stsoe approved these changes

2021-03-31 22:43 UTC, merged