Fix error condition for mKernelFD
Xilinx/XRT pull request #5146
Opened 2021-04-23 15:14 UTC by fabwu

If the mKernelFD doesn't exist, no error message is shown because open() returns -1 instead of null. Fix this by checking for -1.

2021-04-23 15:16 UTC, gbuildx commented
Can one of the admins verify this patch?

2021-04-26 23:57 UTC, sonals commented
ok to test

2021-04-27 00:07 UTC, stsoe requested changes
@fabwu Thank you for fixing this.  Can you please sign your commit per https://github.com/Xilinx/XRT/blob/master/CONTRIBUTING.rst

2021-04-27 04:07 UTC, gbuildx commented
Build Passed!

2021-04-27 06:21 UTC, gbuildx commented
Build Passed!

2021-04-28 15:14 UTC, stsoe approved these changes

2021-04-28 15:16 UTC, chvamshi-xilinx approved these changes

2021-04-28 15:17 UTC, merged