Coverity fall
Xilinx/XRT pull request #5155
Opened 2021-04-23 23:05 UTC by chienwei-lan

2021-04-24 00:06 UTC, mamin506 commented on src/runtime_src/core/pcie/driver/linux/xocl/userpf/xocl_kds.c
> +
'Tab' in an empty line.

2021-04-24 00:10 UTC, mamin506 commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/ert_user.c
>  	}
The slot_size is in bytes. "cfg->slot_size & 0x1F" here means it is 32 bytes aligned. Right?

2021-04-24 00:18 UTC, mamin506 commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/ert_user.c
> +#define	ERT_MIN_SLOT_SIZE	512
I would suggest do not define this macro.
The minimum slot size is defined by "ert_user->cq_range / ERT_MAX_SLOTS". If there is a shell has different cq_range, use this formula would still work.

2021-04-24 00:20 UTC, mamin506 commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/ert_user.c
> +		slot_size = ert_user->cq_range / MAX_CUS;
Please use ERT_MAX_SLOTS.

2021-04-24 00:25 UTC, mamin506 commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/ert_user.c
> +		slot_size = ERT_MIN_SLOT_SIZE;
See my comment about this macro.

2021-04-24 00:28 UTC, mamin506 requested changes
See my comments.

2021-04-24 05:16 UTC, gbuildx commented
Build Passed!

2021-04-26 18:00 UTC, mamin506 requested changes
Minor change.

2021-04-26 18:35 UTC, gbuildx commented
Build Failed! :(

2021-04-26 19:33 UTC, mamin506 commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/ert_user.c
> +		ERTUSER_ERR(ert_user, "slot_size should be 32-bit aligned, slot_size=%d",
Please update the error message as well, "slot_size should be 4 bytes aligned".

2021-04-26 19:41 UTC, gbuildx commented
Build Failed! :(

2021-04-26 20:21 UTC, dayeh-xilinx commented
retest this please. Pipeline problem with Docker image downloading should be fixed now.

2021-04-26 21:15 UTC, gbuildx commented
Build Passed!

2021-04-26 23:47 UTC, mamin506 approved these changes

2021-04-27 00:24 UTC, gbuildx commented
Build Passed!

2021-04-27 00:34 UTC, merged