CR-1098780 Removed the message regarding the emconfig.json for sw_emu…
Xilinx/XRT pull request #5227
Opened 2021-05-08 12:22 UTC by venkatp-xilinx

CR-1098780 Removed the message regarding the emconfig.json for sw_emu in edge cases

2021-05-08 12:54 UTC, gbuildx commented
Build Failed! :(

2021-05-08 19:42 UTC, dayeh-xilinx commented
retest this please. Build encounter a strange error "'build.bat' is not recognized as an internal or external command". Try to retest.

2021-05-08 20:28 UTC, gbuildx commented
Build Failed! :(

2021-05-10 00:27 UTC, abalasa commented
retest this please

2021-05-10 04:50 UTC, stsoe requested changes
Just one minor comment.  Else good.

2021-05-10 04:50 UTC, stsoe commented on src/runtime_src/core/edge/sw_em/generic_pcie_hal2/halapi.cxx
> +    }*/
Please delete dead code

2021-05-10 16:06 UTC, merged