CR-1095014 ASTeR TS9 - u50 nodma - 'xbutil examine' errors with 'No s…
Xilinx/XRT pull request #5260
Opened 2021-05-17 18:23 UTC by sadasivanshaiju

…uch node (dma_thread_count)'

2021-05-17 18:27 UTC, AShivangi approved these changes
Thanks for readding the code

2021-05-17 21:23 UTC, gbuildx commented
Build Passed!

2021-05-18 05:29 UTC, rozumx requested changes
Please do take the time to clean up the subject and description of this pull request.

When completed, I will approve this pull request.

2021-05-19 21:19 UTC, rozumx approved these changes
Thank you for updating the subject and description.

It does help both the code reviewer AND future developer in truly understanding the purpose behind the pull request.   Also, it shows that you are taking the time and extra step to produce a quality pull request.

2021-05-19 21:28 UTC, merged