CR-1100856 u50 NoDMA PLRAM read using sub-buffers causes panic
Xilinx/XRT pull request #5294
Opened 2021-05-24 20:25 UTC by stsoe

Fix xrt::bo sub buffer sync to handle the case where parent buffer is
a nodma buffer.

Prevent kernel panic in case user land calls sync ioctl on nodma buffer.

2021-05-24 20:31 UTC, maxzhen requested changes

2021-05-24 20:31 UTC, maxzhen commented on src/runtime_src/core/pcie/driver/linux/xocl/userpf/xocl_bo.c
> +	if (!xocl_bo_sync_able(xobj->flags) || !xobj->sgt) {
Wondering if we don't have to change this line? Basically, checking !xocl_bo_sync_able(xobj->flags) might be good enough... It makes sense to first do the !xocl_bo_sync_able(xobj->flags) check before start doing the real job.

2021-05-24 21:23 UTC, gbuildx commented
Build Failed! :(

2021-05-24 22:01 UTC, maxzhen approved these changes

2021-05-24 22:48 UTC, gbuildx commented
Build Failed! :(

2021-05-24 23:24 UTC, gbuildx commented
Build Failed! :(

2021-05-24 23:52 UTC, stsoe commented
retest this please - no idea why it failed, but there were a few force pushes that may have caused this?

2021-05-25 05:01 UTC, xilinxgitops commented
retest this please

2021-05-25 08:59 UTC, gbuildx commented
Build Passed!

2021-05-25 14:41 UTC, merged