CR-1100458: multi device fix poll
Xilinx/XRT pull request #5304
Opened 2021-05-25 20:36 UTC by sarab96

Fix for multiple device to check cu completion on multiple devices

2021-05-25 20:49 UTC, maxzhen approved these changes

2021-05-25 20:53 UTC, maxzhen approved these changes

2021-05-26 04:51 UTC, gbuildx commented
Build Passed!

2021-05-26 15:39 UTC, stsoe requested changes

2021-05-26 15:39 UTC, stsoe commented on src/xma/src/xmaapi/xmaapi.cpp
> +            std::this_thread::sleep_for(std::chrono::milliseconds(100));
What is this third case?   It  no longer calls xclExecWait, what happens in cpu_mode is not MODE2 or MODE1?

2021-05-26 15:39 UTC, stsoe commented on src/xma/src/xmaapi/xmaapi.cpp
> +        tmp_fd.revents = 0;
This is a bit backwards.    Typically one would do:
`all_polldf.emplace_back(pollfd{drv->xclGetFd(), POLLIN, 0});`

2021-05-26 15:39 UTC, stsoe commented on src/xma/src/xmaapi/xmaapi.cpp
> +            ::poll(all_pollfd.data(), all_pollfd.size(), 500);
Just one question.  Are the collected device fds guaranteed to all be valid while this thread is running?

2021-05-26 15:39 UTC, stsoe commented on src/xma/src/xmaapi/xmaapi.cpp
> +    for (XmaHwDevice& hw_device: g_xma_singleton->hwcfg.devices) {
Is g_xma_singleton->hwcfg.devices  unchanged for the lifetime of this thread?

2021-06-03 02:53 UTC, maxzhen commented
Not going to merge.

2021-06-03 02:53 UTC, closed without merging