XGQ hw emu support queue roll over
Xilinx/XRT pull request #5313
Opened 2021-05-26 18:14 UTC by larry9523

1. Get rid off a workaroud (bit 15) to detect new entry in polling mode
2. Add support for queue roll over so that we can support continious incoming/completing commands

2021-05-26 22:32 UTC, maxzhen approved these changes

2021-05-26 23:15 UTC, gbuildx commented
Build Passed!

2021-05-26 23:32 UTC, chienwei-lan approved these changes

2021-05-27 17:16 UTC, maxzhen requested changes
Just talked to @chienwei-lan , we should change the definition of tail pointer value to be the "next free slot", instead of the "latest updated slot". This matches the HW init value.

2021-05-27 20:58 UTC, chienwei-lan approved these changes

2021-05-27 21:05 UTC, maxzhen approved these changes

2021-05-28 01:23 UTC, gbuildx commented
Build Passed!

2021-05-28 02:16 UTC, gbuildx commented
Build Passed!

2021-05-28 02:34 UTC, merged