CR-1093969 support older shell kernels in iops test
Xilinx/XRT pull request #5337
Opened 2021-05-28 12:18 UTC by rajkumar-xilinx

U2 older shell (xilinx_u2_gen3x4_xdma_gc_base_1) has hello kernel's
cu name defined as hello_cu0. So, support this case also in iops test

Signed-off-by: Rajkumar Rampelli <rajkumar@xilinx.com>

2021-05-28 13:20 UTC, gbuildx commented
Build Passed!

2021-05-29 02:28 UTC, mamin506 requested changes

2021-05-29 02:28 UTC, mamin506 commented on tests/validate/xcl_iops_test/src/xcl_api_iops.cpp
> +        // CU name of hello kernel on older shells is "hello:hello_cu0"
hello:hello_cu0 is U2 shell special. Please add this in comment.

2021-05-29 11:19 UTC, gbuildx commented
Build Passed!

2021-06-01 19:53 UTC, mamin506 approved these changes

2021-06-02 03:57 UTC, chvamshi-xilinx approved these changes

2021-06-02 03:58 UTC, merged