CR-1082022 ASTeR TC 26.01 - u50 nodma -validate does not run p2p test
Xilinx/XRT pull request #5406
Opened 2021-06-15 02:39 UTC by sadasivanshaiju

2021-06-15 03:26 UTC, gbuildx commented
Build Passed!

2021-06-15 16:38 UTC, AShivangi requested changes

2021-06-15 16:38 UTC, AShivangi commented on src/runtime_src/core/tools/xbutil2/SubCmdValidate.cpp
> +
remove extra lines

2021-06-15 16:38 UTC, AShivangi commented on src/runtime_src/core/tools/xbutil2/SubCmdValidate.cpp
> +    return 1;
Instead of returning 1 and 0, please return true/false

2021-06-15 16:38 UTC, AShivangi commented on src/runtime_src/core/tools/xbutil2/SubCmdValidate.cpp
> +     run_test.update(++counter);
is the extra space needed?

2021-06-15 16:38 UTC, AShivangi commented on src/runtime_src/core/tools/xbutil2/SubCmdValidate.cpp
> +   }
I don't see a counter update in this block of code. How does the progress bar update when running on a nodma platform? I think we need to revisit this piece of code.

2021-06-15 16:38 UTC, AShivangi commented on src/runtime_src/core/tools/xbutil2/SubCmdValidate.cpp
> +  boptr = (char*) xclMapBO(handle, boh, true);
Please use c++ style casting: `reinterpret_cast<char *>(...)`

2021-06-15 16:38 UTC, AShivangi commented on src/runtime_src/core/tools/xbutil2/SubCmdValidate.cpp
> +  boptr = (char*) xclMapBO(handle, boh, true);
Please use c++ style casting: `reinterpret_cast<char *>(...)`

2021-06-17 22:17 UTC, gbuildx commented
Build Passed!

2021-06-22 15:01 UTC, closed without merging

2021-06-22 15:01 UTC, sadasivanshaiju commented
opened another pull request. This is invalid now