CR-1103270 ERT CQ slot size needs a cap
Xilinx/XRT pull request #5411
Opened 2021-06-16 20:24 UTC by mamin506

We should not support > 4KB ERT CQ slot size.

2021-06-16 20:46 UTC, maxzhen requested changes
please also add a check to reject CU cmd that exceeds the CQ slot size.

2021-06-16 21:16 UTC, gbuildx commented
Build Passed!

2021-06-16 21:40 UTC, maxzhen approved these changes

2021-06-16 22:51 UTC, gbuildx commented
Build Failed! :(

2021-06-16 23:12 UTC, dayeh-xilinx commented
retest this please. I break the boardfarm host by accident. Test again.

2021-06-17 00:02 UTC, gbuildx commented
Build Passed!

2021-06-17 03:24 UTC, merged