Error get last for xcol driver errors
Xilinx/XRT pull request #5536
Opened 2021-07-27 16:31 UTC by sarab96

Error get last for xocl driver
query & xocl_error class for pcie x86 side

2021-07-27 17:26 UTC, gbuildx commented
Build Passed!

2021-07-28 16:54 UTC, larry9523 reviewed
I am not very familiar with this part of code. So forgive me if it is a stupid question. I am wondering why do we need a special query xocl_error? Isn't it be handled automatically among xocl, xclmgmt, zocl? cc @stsoe

2021-07-28 17:00 UTC, stsoe requested changes
This pull request needs a lot more details, please.
It's void of comments as to the purpose of added classes and what the changes do.
Please redo.  And please add @stsoe for any user space core/common changes.

2021-07-30 17:23 UTC, sarab96 commented
Will submit new PR

2021-07-30 17:23 UTC, closed without merging