CR-1097500 ASTeR TS 26 - xbutil2 - fix order of print in validate whe…
Xilinx/XRT pull request #5553
Opened 2021-07-30 18:53 UTC by sadasivanshaiju

…n P2P is enabled

2021-07-30 19:48 UTC, gbuildx commented
Build Passed!

2021-07-30 20:07 UTC, AShivangi requested changes
Please make the requested changes and add sample outputs for:
1. passed test case
2. failed test case
before re-requesting review.

2021-07-30 20:07 UTC, AShivangi commented on src/runtime_src/core/tools/xbutil2/SubCmdValidate.cpp
> +  XBU::ProgressBar run_test("Running Test on ", mem_topo->m_count, XBU::is_escape_codes_disabled(), std::cout);
remove "on"

2021-07-30 20:07 UTC, AShivangi commented on src/runtime_src/core/tools/xbutil2/SubCmdValidate.cpp
> +	}else {
else on a new line

2021-07-30 20:07 UTC, AShivangi commented on src/runtime_src/core/tools/xbutil2/SubCmdValidate.cpp
> +  run_test.finish(true, "");
this needs to be wrapped in an if statement. Please remove `run_test.finish(false, "");` L1032-1033 and do the following:
```suggestion
  if(counter < mem_topo->m_count)
    run_test.finish(false, "");
  else
    run_test.finish(true, "");
```

2021-08-02 18:53 UTC, sadasivanshaiju commented
Running Test on : ..........25%.........50%.........75%....
Test 1 [0000:b1:00.1]     : Peer to peer bar
    Details               : HBM[0] validated
                            HBM[1] validated
                            HBM[2] validated
                            HBM[3] validated
                            HBM[4] validated
                            HBM[5] validated
                            HBM[6] validated
                            HBM[7] validated
                            HBM[8] validated
                            HBM[9] validated
                            HBM[10] validated
                            HBM[11] validated
                            HBM[12] validated
                            HBM[13] validated
                            HBM[14] validated
                            HBM[15] validated
                            HBM[16] validated
                            HBM[17] validated
                            HBM[18] validated
                            HBM[19] validated
                            HBM[20] validated
                            HBM[21] validated
                            HBM[22] validated
                            HBM[23] validated
                            HBM[24] validated
                            HBM[25] validated
                            HBM[26] validated
                            HBM[27] validated
                            HBM[28] validated
                            HBM[29] validated
                            HBM[30] validated
                            HBM[31] validated
                             validated
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Validation completed. Please run the command '--verbose' option

2021-08-02 19:53 UTC, gbuildx commented
Build Passed!

2021-08-03 00:39 UTC, AShivangi commented on src/runtime_src/core/tools/xbutil2/SubCmdValidate.cpp
> +           std::cout << EscapeCodes::cursor().prev_line() << EscapeCodes::cursor().clear_line();
please remove these lines

2021-08-03 20:48 UTC, AShivangi approved these changes

2021-08-03 21:59 UTC, gbuildx commented
Build Passed!

2021-08-03 22:05 UTC, merged