add binary sysfs node to show ERT CQ for easy of debug
Xilinx/XRT pull request #5563
Opened 2021-08-02 21:29 UTC by chienwei-lan

2021-08-02 22:22 UTC, gbuildx commented
Build Failed! :(

2021-08-03 18:00 UTC, dayeh-xilinx commented
retest this please

2021-08-03 19:05 UTC, gbuildx commented
Build Passed!

2021-08-03 22:48 UTC, mamin506 requested changes
Thanks Chien-wei. This is a good to have for debug hang issue.
Just a minor change.

2021-08-03 22:48 UTC, mamin506 commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/command_queue.c
> +		xocl_err(&pdev->dev, "create ert_cq sysfs attrs failed: %d", err);
later on, we might have more and more sysfs node for other purpose. Should we print "Create command queue sysfs node group failed" here?

2021-08-03 23:06 UTC, mamin506 commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/command_queue.c
> +		xocl_err(&pdev->dev, "create ert_cq sysfs attrs failed: %d", err);
ert_cq will be the sub-dev name. Not just the argument.

2021-08-03 23:06 UTC, mamin506 approved these changes

2021-08-03 23:10 UTC, merged