CR-1089460 Add changes to show heartbeat status from xmc through "xbutil examine" command
Xilinx/XRT pull request #5570
Opened 2021-08-04 11:07 UTC by rajkumar-xilinx

Display heartbeat status from xmc subdev using xbutil2 examine command

Signed-off-by: Rajkumar Rampelli <rajkumar@xilinx.com>

2021-08-04 11:09 UTC, rajkumar-xilinx commented
Below is the output observed on U200 setup

```
# xbutil examine -r xmc

-----------------------------------------------------
1/1 [0000:86:00.1] : xilinx_u200_gen3x16_xdma_base_1
-----------------------------------------------------
XMC status
  heartbeat_stall        : false
  heartbeat_count        : 7320
  heartbeat_err_code     : 0x100
  heartbeat_err_time     : 0

```

2021-08-04 11:35 UTC, stsoe approved these changes

2021-08-04 13:20 UTC, chvamshi-xilinx approved these changes
Looks good.

2021-08-04 14:55 UTC, gbuildx commented
Build Failed! :(

2021-08-04 15:53 UTC, AShivangi requested changes
Please address the requested changes and add the json output to the PR desc

2021-08-04 15:53 UTC, AShivangi commented on src/runtime_src/core/tools/common/ReportXmc.cpp
> +ReportXmc::writeReport( const xrt_core::device* /*_pDevice*/,
Please change the name to `ReportXmcStatus`

2021-08-04 15:53 UTC, AShivangi commented on src/runtime_src/core/tools/common/ReportXmc.cpp
> +  } catch(...) {}
Never do this kind of catch. @stsoe has created a new exception `xrt_core::query::error` which catches errors related to query requests (no_such_key, sysfs_error, a few more), but does not catch unrelated "real" errors.

2021-08-04 15:53 UTC, AShivangi commented on src/runtime_src/core/tools/common/ReportXmc.cpp
> +    pt.put("heartbeat_stall", xrt_core::device_query<xrt_core::query::heartbeat_stall>(_pDevice));
Maybe rename "heatbeat_stall" to something more human-readable... I am not sure what is a more suitable tag

2021-08-04 15:53 UTC, AShivangi commented on src/runtime_src/core/tools/common/ReportXmc.cpp
> +    pt.put("heartbeat_stall", xrt_core::device_query<xrt_core::query::heartbeat_stall>(_pDevice));
Maybe rename "heatbeat_stall" to something more human-readable... I am not sure what is a more suitable tag

2021-08-04 23:34 UTC, gbuildx commented
Build Passed!

2021-08-05 01:28 UTC, gbuildx commented
Build Passed!

2021-08-05 11:51 UTC, gbuildx commented
Build Passed!

2021-08-05 15:18 UTC, AShivangi approved these changes
This looks good! Thanks for enhancing the output

2021-08-05 15:36 UTC, merged