CR-1053805 Convert CMC Version No to HEX for XRT output
Xilinx/XRT pull request #5660
Opened 2021-08-20 21:30 UTC by sadasivanshaiju

Here is  the output in hex

  "controller": {
                        "satellite_controller": {
                            "version": "4.6.11",
                            "expected_version": "4.6.11"
                        },
                        "card_mgmt_controller": {
                            "version": "0xc01020f",
                            "serial_number": "21290185T005",
                            "oem_id": "Xilinx"
                        }
                    },

2021-08-20 23:03 UTC, gbuildx commented
Build Failed! :(

2021-08-21 02:48 UTC, dayeh-xilinx commented
retest this please. Build failed for an infra error.

2021-08-21 07:00 UTC, gbuildx commented
Build Failed! :(

2021-08-22 04:19 UTC, dayeh-xilinx commented
retest this please. Build failed for an infra error.

2021-08-22 06:08 UTC, gbuildx commented
Build Passed!

2021-08-23 16:25 UTC, AShivangi requested changes

2021-08-23 16:25 UTC, AShivangi commented on src/runtime_src/core/common/info_platform.cpp
> +    version << "0x" << std::hex << std::stoi(xrt_core::device_query<xq::xmc_version>(device));
1. Why aren't we using `ver = std::stoul(ver, nullptr, 16);` to convert to hex?
2. what if std::stoi fails? Please add a try-catch around it

2021-08-23 20:02 UTC, AShivangi approved these changes

2021-08-23 23:31 UTC, gbuildx commented
Build Failed! :(

2021-08-24 01:10 UTC, dayeh-xilinx commented
retest this please. Build failed for an infra error.

2021-08-24 06:32 UTC, gbuildx commented
Build Passed!

2021-08-24 16:02 UTC, merged