ERT CQ/CU Access Test
Xilinx/XRT pull request #5699
Opened 2021-08-27 21:13 UTC by chienwei-lan

2021-08-27 23:21 UTC, gbuildx commented
Build Passed!

2021-08-30 23:26 UTC, mamin506 approved these changes

2021-08-31 00:46 UTC, AShivangi requested changes

2021-08-31 00:46 UTC, AShivangi commented on src/runtime_src/core/common/query_requests.h
> +  using result_type = uint64_t;
Can you please change this to bool (refer to struct `is_sc_fixed`)?

2021-09-01 20:49 UTC, AShivangi approved these changes
Thanks for making teh changes

2021-09-02 00:14 UTC, gbuildx commented
Build Passed!

2021-09-02 02:51 UTC, merged