CR-1108493 : Fix for multiple zocl load/unload
Xilinx/XRT pull request #5730
Opened 2021-09-05 19:18 UTC by saifuddin-xilinx

CR-1108493 : dfx-manager fails to load overlay after ~32 iterations . Linux OS hangs

**Issue:**
Unloading and loading zocl driver repeatedly over 45 times causes the Linux operating system to hang . 

**Root Cause:**
To get the pcap driver we are searching from device tree using "of_find_node_by_name" Kernel function. 
The params we are passing as "of_root" which is causing the issue. As per petaLinux kernel none of the module/driver used this param. Instead used NULL as a param to traverse all the node in the device tree. 

**Solution:**
Update the param to "NULL" in of_find_node_by_name function resolved the issue.

2021-09-06 01:14 UTC, gbuildx commented
Build Failed! :(

2021-09-06 05:22 UTC, xilinxgitops commented
retest this please

2021-09-06 05:33 UTC, chvamshi-xilinx approved these changes
Looks good to me. Please verify DFx platforms and check whether you are getting the right node or not.

2021-09-06 08:14 UTC, gbuildx commented
Build Passed!

2021-09-07 20:01 UTC, larry9523 requested changes
The fix looks good. But there is a missing part. After we found a match, we need to call of_node_put to decrease the reference count of the node we just got.

P.S. the other way to fix it is to call of_nod_get(of_root) before calling of_find_node_by_name() and keep using of_root instead of NULL. But the "NULL" solution seems cleaner.

2021-09-08 14:14 UTC, gbuildx commented
Build Passed!

2021-09-08 15:48 UTC, larry9523 approved these changes

2021-09-08 15:48 UTC, merged