configure md0 and md1 for floating pt execeptions
Xilinx/XRT pull request #5735
Opened 2021-09-07 19:34 UTC by hackwa

2021-09-07 22:54 UTC, gbuildx commented
Build Passed!

2021-09-08 16:53 UTC, sonals requested changes

2021-09-08 16:53 UTC, sonals commented on src/runtime_src/xdp/profile/plugin/aie_profile/aie_plugin.cpp
> +          // Enable floating point exception events
AIEProfilingPlugin::setMetrics() is about 250 lines long. Please break up this function into logical pieces.

2021-09-08 20:53 UTC, hackwa commented
This change is no longer required. I'll close this PR for now. @sonals will make your suggested change in a new PR.

2021-09-08 20:53 UTC, closed without merging