Reserve host memory regardless address translator presence
Xilinx/XRT pull request #5747
Opened 2021-09-08 22:01 UTC by chienwei-lan

2021-09-08 23:09 UTC, xuhz approved these changes

2021-09-09 05:12 UTC, houlz0507 approved these changes

2021-09-09 06:13 UTC, gbuildx commented
Build Passed!

2021-09-09 15:57 UTC, maxzhen requested changes

2021-09-09 15:57 UTC, maxzhen commented on src/runtime_src/core/pcie/driver/linux/xocl/userpf/xocl_drv.c
> +	uint32_t i, j, num = 256;
please add a #define with some comments for this magic number "256"

2021-09-09 15:57 UTC, maxzhen commented on src/runtime_src/core/pcie/driver/linux/xocl/userpf/xocl_drv.c
> +	uint64_t page_num = 256;
use the #define above

2021-09-09 15:57 UTC, maxzhen commented on src/runtime_src/core/pcie/driver/linux/xocl/userpf/xocl_drv.c
> +	int num = 256;
is this "256" the same as other "256"? if so, pls use the same macro.

2021-09-09 21:55 UTC, xuhz reviewed
BTW, i tested the changes on a u50 nodma shell. 
With the other changes i made, moving m2m and SB from shell to ULP works -- i can run 'xbutil validate' successfully

2021-09-09 21:57 UTC, maxzhen approved these changes

2021-09-10 00:10 UTC, gbuildx commented
Build Passed!

2021-09-10 01:37 UTC, merged