Show reserved HOST MEM in legacy xbutil query
Xilinx/XRT pull request #5779
Opened 2021-09-13 22:25 UTC by chienwei-lan

2021-09-14 06:09 UTC, gbuildx commented
Build Passed!

2021-09-14 17:25 UTC, AShivangi requested changes
Please change it in https://github.com/Xilinx/XRT/blob/929578c23c8f22c14f95134b68952209788a3f91/src/runtime_src/core/pcie/linux/device_linux.cpp#L595 as well

2021-09-15 20:15 UTC, stsoe approved these changes

2021-09-15 20:23 UTC, chienwei-lan commented
> Please change it in
> 
> https://github.com/Xilinx/XRT/blob/929578c23c8f22c14f95134b68952209788a3f91/src/runtime_src/core/pcie/linux/device_linux.cpp#L595
> 
> as well

After this PR https://github.com/Xilinx/XRT/pull/5747, users now can reserve the host memory regardless if the device has address translator IP or not and the value is shown as Shared Host Memory as usual, which behavior does not change.

And the effective host memory size is shown and introduced as a new field as Enable Host Memory, which depends on the capability of the address translator of the device, not always same size as user reserved

`Pcie Info
Shared Host Memory     : 1 GB
Max Shared Host Memory : 16 GB
Enabled Host Memory    : 1 GB`

2021-09-15 20:26 UTC, maxzhen approved these changes

2021-09-15 21:39 UTC, gbuildx commented
Build Passed!

2021-09-20 00:32 UTC, AShivangi approved these changes

2021-09-20 20:31 UTC, rozumx approved these changes

2021-09-20 20:31 UTC, merged