CR-1110239: Fixing ap_ctrl_none issue
Xilinx/XRT pull request #5783
Opened 2021-09-14 10:24 UTC by chvamshi-xilinx

This change fixes the segmentation fault causing for AP_CNTRL_NONE kernels.
We shouldn't create threads for ap_ctrl_none. We are not calling xrt_cu_init also for the ap_ctrl_none kernels.

2021-09-14 12:23 UTC, gbuildx commented
Build Passed!

2021-09-15 01:03 UTC, mamin506 requested changes
This change doesn't make sense to me.

For AP_CTRL_NONE CU, it should not have interrupt capability. In this case, xrt_cu_cfg_update() should return -ENOSYS.

See xrt_cu.c,

int xrt_cu_cfg_update(struct xrt_cu *xcu, int intr)
{
        int (* cu_thread)(void *data);
        int err = 0;

        /* Check if CU support interrupt in hardware */
        if (!xcu->info.intr_enable)
                return -ENOSYS;
                
        ....
}

Could you check if the AP_CTRL_NONE cu has intr_enable set to true? It should be false.
If this is the case, could you check why and fix?

2021-09-16 06:30 UTC, chvamshi-xilinx commented
> This change doesn't make sense to me.
> 
> For AP_CTRL_NONE CU, it should not have interrupt capability. In this case, xrt_cu_cfg_update() should return -ENOSYS.
> 
> See xrt_cu.c,
> 
> int xrt_cu_cfg_update(struct xrt_cu _xcu, int intr) { int (_ cu_thread)(void *data);
> int err = 0;
> 
> ```
>     /* Check if CU support interrupt in hardware */
>     if (!xcu->info.intr_enable)
>             return -ENOSYS;
>             
>     ....
> ```
> 
> }
> 
> Could you check if the AP_CTRL_NONE cu has intr_enable set to true? It should be false.
> If this is the case, could you check why and fix?

That is a good point @mamin506 . I will move CR to filer as this is for RTL kernel. They might have packaged it incorrectly.
I am keeping this PR still open to print DRC instead of crashing the kernel.

2021-09-16 09:27 UTC, gbuildx commented
Build Passed!

2021-09-16 10:36 UTC, gbuildx commented
Build Passed!

2021-09-16 11:43 UTC, gbuildx commented
Build Passed!

2021-09-16 12:09 UTC, gbuildx commented
Build Failed! :(

2021-09-17 00:37 UTC, dayeh-xilinx commented
retest this please. Don't know why this gets build 4 times. Try again.

2021-09-17 04:12 UTC, chvamshi-xilinx commented
@mamin506 , Can you please check the DRC.

2021-09-17 10:21 UTC, gbuildx commented
Build Passed!

2021-09-17 23:35 UTC, mamin506 approved these changes

2021-09-17 23:42 UTC, merged