CR-1110308 xmc: load-config pass true to enable clock scaling feature
Xilinx/XRT pull request #5830
Opened 2021-09-22 15:36 UTC by rajkumar-xilinx

Signed-off-by: Rajkumar Rampelli <rajkumar@xilinx.com>

2021-09-22 16:06 UTC, gbuildx commented
Build Failed! :(

2021-09-22 16:41 UTC, maxzhen commented
Why not change the tool to pass "enable" instead?

2021-09-22 16:48 UTC, rajkumar-xilinx commented
> Why not change the tool to pass "enable" instead? or if we believe "true" / "false" would be more appropriate, why do we need to still support "enable"? There is no backward compatibility requirement b/w driver and tools.

Yes, we can remove "enable" option now. We were using this option only in the sysfs path, but we can start using "true/false" instead of "enable". I will update PR. Thanks.

2021-09-22 16:52 UTC, maxzhen commented
> 
> 
> > Why not change the tool to pass "enable" instead? or if we believe "true" / "false" would be more appropriate, why do we need to still support "enable"? There is no backward compatibility requirement b/w driver and tools.
> 
> Yes, we can remove "enable" option now. We were using this option only in the sysfs path, but we can start using "true/false" instead of "enable". I will update PR. Thanks.

I'm assuming removing support for "enable" does not impact legacy xbmgmt, right?

2021-09-22 16:55 UTC, chvamshi-xilinx commented
> > Why not change the tool to pass "enable" instead? or if we believe "true" / "false" would be more appropriate, why do we need to still support "enable"? There is no backward compatibility requirement b/w driver and tools.
> 
> Yes, we can remove "enable" option now. We were using this option only in the sysfs path, but we can start using "true/false" instead of "enable". I will update PR. Thanks.

I hope xbmgmt dump is printing scaling_support=true/false in ini file.

2021-09-22 17:51 UTC, gbuildx commented
Build Passed!

2021-09-22 20:22 UTC, stsoe requested changes
Hi @rajkumar-xilinx  Could you add a few lines the description of this PR with the highlights of what was changed and why?

Is the PR also for 2021.2 or just for 2022.1?

2021-09-23 03:42 UTC, rajkumar-xilinx commented
> > > Why not change the tool to pass "enable" instead? or if we believe "true" / "false" would be more appropriate, why do we need to still support "enable"? There is no backward compatibility requirement b/w driver and tools.
> > 
> > 
> > Yes, we can remove "enable" option now. We were using this option only in the sysfs path, but we can start using "true/false" instead of "enable". I will update PR. Thanks.
> 
> I'm assuming removing support for "enable" does not impact legacy xbmgmt, right?

No impact on legacy commands as well. Verified this case also.

2021-09-23 04:00 UTC, maxzhen approved these changes

2021-09-23 04:28 UTC, rajkumar-xilinx commented
> Hi @rajkumar-xilinx Could you add a few lines the description of this PR with the highlights of what was changed and why?
> 
> Is the PR also for 2021.2 or just for 2022.1?

I have updated description and it is for 2021.2

2021-09-23 05:19 UTC, stsoe approved these changes
Thanks @rajkumar-xilinx  Unfortunately we are no longer auto merging to 2021.2 so please cherry pick for 2021.2 and create another pull request for that branch.

2021-09-23 06:40 UTC, rajkumar-xilinx commented
2021.2 branch PR https://github.com/Xilinx/XRT/pull/5834

2021-09-23 07:27 UTC, rajkumar-xilinx commented
> Thanks @rajkumar-xilinx Unfortunately we are no longer auto merging to 2021.2 so please cherry pick for 2021.2 and create another pull request for that branch.

2021.2 branch PR #5834

2021-09-23 09:03 UTC, chvamshi-xilinx approved these changes

2021-09-23 09:03 UTC, merged