refactor mailbox test code
Xilinx/XRT pull request #5831
Opened 2021-09-22 17:09 UTC by xuhz

2021-09-22 18:51 UTC, gbuildx commented
Build Passed!

2021-09-22 20:20 UTC, stsoe requested changes
@xuhz  Please add a proper description as to what was done in this pull request, basically the highlights of this PR.

Another question:  Is this for 2021.2 also, or only for 2022.1?

2021-09-22 20:24 UTC, maxzhen approved these changes

2021-09-24 02:22 UTC, stsoe approved these changes

2021-09-24 03:15 UTC, merged