CR-1112068 Sometimes configure command timeout
Xilinx/XRT pull request #5840
Opened 2021-09-23 21:22 UTC by mamin506

See more details in CR.

2021-09-23 21:51 UTC, maxzhen approved these changes

2021-09-24 02:39 UTC, gbuildx commented
Build Passed!

2021-09-24 15:23 UTC, stsoe requested changes
The CR describes the what, but the commit message should explain just briefly the how.  

It doesn't have to be more than a few lines, but since the code isn't really documented to begin with, it is difficult to understand how the changes fixed the CR.

2021-09-24 18:13 UTC, mamin506 commented
> The CR describes the what, but the commit message should explain just briefly the how.
> 
> It doesn't have to be more than a few lines, but since the code isn't really documented to begin with, it is difficult to understand how the changes fixed the CR.

Done. 👍

2021-09-24 18:20 UTC, stsoe approved these changes

2021-09-24 18:52 UTC, merged