CR-1112076 xbutil reset on azure fails with timeout
Xilinx/XRT pull request #5847
Opened 2021-09-24 17:33 UTC by xuhz

2021-09-24 17:44 UTC, houlz0507 approved these changes

2021-09-24 19:31 UTC, maxzhen requested changes

2021-09-24 19:31 UTC, maxzhen commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/mailbox.c
> +	mutex_lock(&ch->sw_chan_mutex);
It is good to have this lock protection. I'm curious if you really ran into a race condition for this?

2021-09-24 19:31 UTC, maxzhen commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/mailbox.c
> +	if ((ch->mbc_cur_msg && ch->mbc_cur_msg->mbm_chan_sw) || MB_SW_ONLY(mbx))
this change will violate the rule we set up (see comment at line 1596). do you really need this change?

2021-09-24 19:42 UTC, gbuildx commented
Build Passed!

2021-09-25 01:13 UTC, maxzhen approved these changes

2021-09-25 10:28 UTC, gbuildx commented
Build Passed!

2021-09-25 15:58 UTC, merged