Updated sk_daemon.cpp to support FFI typed arguments and FFI ABI
Xilinx/XRT pull request #5848
Opened 2021-09-24 19:09 UTC by jeffli-xilinx

This is the updated soft kernel daemon that runs on APU which takes in FFI type arguments and run the soft kernel with FFI call ABI.

2021-09-24 21:24 UTC, gbuildx commented
Build Failed! :(

2021-09-27 15:56 UTC, larry9523 commented on src/runtime_src/core/edge/skd/sk_daemon.cpp
> +
remove extra blank line?

2021-09-27 16:00 UTC, larry9523 commented on src/runtime_src/core/edge/skd/sk_daemon.cpp
> +  if(errstr != NULL) {
space after "if" keyword

2021-09-27 16:06 UTC, larry9523 commented on src/runtime_src/core/edge/skd/sk_daemon.cpp
> +  for(int i=0;i<args.size();i++) {
space after "for" keyword

2021-09-27 16:07 UTC, larry9523 commented on src/runtime_src/core/edge/skd/sk_daemon.cpp
> +	if(args[i].type == xrt_core::pskernel::kernel_argument::argtype::global) {
space, ident

2021-09-27 16:11 UTC, larry9523 requested changes
I need a little bit more time to understand FFI. But for now, just put some comments on c-style. I will make sure to get other parts reviewed today.

2021-09-27 18:05 UTC, gbuildx commented
Build Failed! :(

2021-09-29 16:58 UTC, rozumx requested changes

2021-09-29 16:58 UTC, rozumx commented on src/runtime_src/core/common/pskernel_parse.cpp
> +  const char *var_name;
Variable not initialized.

2021-09-29 16:58 UTC, rozumx commented on src/runtime_src/core/common/pskernel_parse.cpp
> +	Dwarf_Die *func_die = NULL;
Please don't use `NULL`, but instead `nullptr`.

2021-09-29 16:58 UTC, rozumx commented on src/runtime_src/core/common/pskernel_parse.cpp
> +  Dwarf_Die *type = NULL;
Please don't use `NULL`, but instead `nullptr`.

2021-09-29 16:58 UTC, rozumx commented on src/runtime_src/core/common/pskernel_parse.cpp
> +  if (dw != NULL) {
Please don't use `NULL`, but instead `nullptr`.

2021-09-29 16:58 UTC, rozumx commented on src/runtime_src/core/edge/skd/sk_daemon.cpp
> +  if(errstr != NULL) {
Please don't use `NULL`, but instead `nullptr`.

2021-09-29 16:58 UTC, rozumx commented on src/runtime_src/core/common/pskernel_parse.cpp
> +	    if (dwarf_attr (type, DW_AT_encoding, &encoding) == NULL
Unfortunately, I don't know what dwarf_attr returns, if it is a pointer, then this check value should be `nullptr`.

2021-09-29 16:58 UTC, rozumx commented on src/runtime_src/core/common/pskernel_parse.cpp
> +	    if (dwarf_attr (type, DW_AT_byte_size, &bsize) != NULL
Unfortunately, I don't know what dwarf_attr returns, if it is a pointer, then this check value should be `nullptr`.

2021-09-29 16:58 UTC, rozumx commented on src/runtime_src/core/common/pskernel_parse.cpp
> +	    } else if (dwarf_attr (type, DW_AT_bit_size, &bsize) == NULL
Unfortunately, I don't know what dwarf_attr returns, if it is a pointer, then this check value should be `nullptr`.

2021-09-29 16:58 UTC, rozumx commented on src/runtime_src/core/common/pskernel_parse.cpp
> +    return {};
Dead code, should be removed.

2021-09-29 16:58 UTC, rozumx commented on src/runtime_src/core/common/pskernel_parse.cpp
> +  if(!args.empty())
This code should be refactor to something like this:
```
 if(args.empty())
    throw std::runtime_error("No PS kernel arguments found!");

 return args;
```

It just makes it easier to read and straight forward regarding your intent.

2021-09-29 16:58 UTC, rozumx commented on src/runtime_src/core/common/pskernel_parse.cpp
> +    size_t hsize;
Uninitialized variables

2021-09-29 16:58 UTC, rozumx commented on src/runtime_src/core/common/pskernel_parse.cpp
> +  if(!args.empty())
This code should be refactor to something like this:
```
 if(args.empty())
    throw std::runtime_error("No PS kernel arguments found!");

 return args;
```

It just makes it easier to read and straight forward regarding your intent.

2021-09-29 16:58 UTC, rozumx commented on src/runtime_src/core/common/pskernel_parse.h
> +  argtype type;
Uninitialized variables.

2021-09-29 16:58 UTC, rozumx commented on src/runtime_src/core/edge/skd/sk_daemon.cpp
> +  void *kernel;
Uninitialized variables.

2021-09-29 16:58 UTC, rozumx commented on src/runtime_src/core/edge/skd/sk_daemon.cpp
> +  ffi_cif cif;
Uninitialized variables.

2021-09-29 16:58 UTC, rozumx commented on src/runtime_src/core/edge/skd/sk_daemon.cpp
> +    if((args.size()==2 && args[1].name.compare("ops")==0) || args.empty()) {
Comment and command doesn't match up.  Why the args.empty() check?

2021-09-29 16:58 UTC, rozumx commented on src/runtime_src/core/edge/skd/sk_daemon.cpp
> +    if((args.size()==2 && args[1].name.compare("ops")==0) || args.empty()) {
It might be better if the args.empty() is before the other arguments.  It make the code easier to read.

2021-10-02 01:04 UTC, larry9523 approved these changes

2021-10-02 13:57 UTC, gbuildx commented
Build Failed! :(

2021-10-02 16:55 UTC, dayeh-xilinx commented
retest this please. There was a build issue with edge platform.

2021-10-02 21:20 UTC, dayeh-xilinx commented
retest this please. There was a build issue with edge platform.

2021-10-02 23:31 UTC, gbuildx commented
Build Passed!

2022-02-28 18:31 UTC, closed without merging