Vitis-3414 xbflash2: enhance xbflash tool command line options
Xilinx/XRT pull request #5953
Opened 2021-10-25 19:30 UTC by rajkumar-xilinx

Moved and updated xbflash2 tool to make it production ready.

Signed-off-by: Rajkumar Rampelli <rajkumar@xilinx.com>

2021-11-16 11:19 UTC, chvamshi-xilinx commented
Open it again once all changes are done

2021-12-16 20:43 UTC, gbuildx commented
Build Failed! :(

2021-12-16 20:43 UTC, gbuildx commented
Build Failed! :(

2022-01-05 10:48 UTC, gbuildx commented
Build Failed! :(

2022-01-06 04:24 UTC, rajkumar-xilinx commented
retest this please

2022-01-07 01:24 UTC, gbuildx commented
Build Passed!

2022-01-07 09:24 UTC, rajkumar-xilinx commented
**On U2**
root@rahul:/home/rahul/raj/XRT/build/Release/usr/local/bin# ./xbflash2 program --flash spi --image /lib/firmware/xilinx/625b99fa75b56d8353ff2a7a999c8bbb/partition.mcs --device 0000:62:00.0 --image /lib/firmware/xilinx/625b99fa75b56d8353ff2a7a999c8bbb/partition.mcs
About to flash below MCS bitstream onto device 0000:62:00.0:
Are you sure you wish to proceed? [y/n]: y
Successfully opened /dev/xfpga/flash.m25088.0
flashing via QSPI driver
Bitstream guard installed on both flashes @0x801000
Extracting bitstream from MCS data:
.........
Extracted 9245382 bytes from bitstream @0x801000
Writing bitstream to flash 0:
.........
Extracting bitstream from MCS data:
.........
Extracted 9245382 bytes from bitstream @0x801000
Writing bitstream to flash 1:
.........
Bitstream guard removed from both flashes
root@rahul:/home/rahul/raj/XRT/build/Release/usr/local/bin#

2022-01-08 14:47 UTC, gbuildx commented
Build Passed!

2022-01-17 18:32 UTC, gbuildx commented
Build Failed! :(

2022-01-17 18:50 UTC, chvamshi-xilinx requested changes
Disable it for edge also. Looks like build is failing for edge.

2022-01-18 07:36 UTC, gbuildx commented
Build Failed! :(

2022-01-18 11:03 UTC, chvamshi-xilinx commented on src/runtime_src/core/tools/CMakeLists.txt
> +if(NOT XRT_EDGE)
Please use XRT_NATIVE_BUILD flag for consistency. look at xbmgmt2

2022-01-18 19:10 UTC, AShivangi approved these changes

2022-01-19 04:42 UTC, dayeh-xilinx commented
retest this please.

2022-01-19 13:56 UTC, gbuildx commented
Build Failed! :(

2022-01-19 18:49 UTC, gbuildx commented
Build Failed! :(

2022-01-20 01:00 UTC, rozumx requested changes
Unfortunately, I only got through half of the code regarding this code review and had to stop.

Take aways:
1. The code is base upon C coding styles and not C++.  For example:
  a. Return error codes instead of throwing exceptions.
  b. Pass by pointers instead of pass by reference.
  c. Repeating common functionality between methods 
  d. Multiple exit points.
2. I understand that this code was based upon earlier code, unfortunately it wasn't cleaned up.  It should be.
3. Common helper code in core/tools/common is not being used.  This code has a lot of duplicate functionality.
4. Compiler OS directives are being used.  This should not occur of any code in core/tools, with the exception of pragmas to turn off some compiler warnings.
5. Helper code to report the boost program_options is not being used for help like functionality.

2022-01-20 10:18 UTC, rajkumar-xilinx commented on src/runtime_src/core/tools/xbflash2/cmd_dump.cpp
> +    } catch (...) {
these are optional arguments to the tool, so we are not returning any error if these args are not found in the command line.

2022-01-20 11:14 UTC, rajkumar-xilinx commented on src/runtime_src/core/tools/xbflash2/firmware_image.cpp
> +        std::cout << "Can't open " << file << std::endl;
code sets state to "fail" and caller function will check the state before proceeding.

**caller function code:**

firmwareImage pri(primary_file[0].c_str());
if (pri.fail())
      return -EINVAL;

2022-01-20 11:22 UTC, rajkumar-xilinx commented on src/runtime_src/core/tools/xbflash2/main.cpp
> +bool canProceed()
xbflash2 may not reuse these functionality due to xrt core lib dependency. This tool has to be work without xrt.

2022-01-20 11:23 UTC, rajkumar-xilinx commented on src/runtime_src/core/tools/xbflash2/main.cpp
> +void printSubCmdHelp(const std::string& subCmd)
xbflash2 may not reuse these functionality due to xrt core lib dependency. This tool has to be work without xrt.

2022-01-20 12:41 UTC, rajkumar-xilinx commented on src/runtime_src/core/tools/xbflash2/cmd_dump.cpp
> +const char *subCmdDumpUsage =
I have not explored it actually as I was told enhancement scope of this tool is very limited in future. So, I mostly copied from old code.

2022-01-20 13:25 UTC, rajkumar-xilinx commented on src/runtime_src/core/tools/xbflash2/cmd_program.cpp
> +
Will add check to read if the offset is valid and assign it to offset. No need to return error as it is an optional command line arg.

2022-01-20 13:31 UTC, rajkumar-xilinx commented
Hi @rozumx , thank you for reviewing the PR.

>>>What is this code here. It excludes windows. It should be refactor down to a common API that is implemented in Linux and windows.
Work is in progress to refactor the code to support windows API as well. But, it will take time to complete it. So, we are going to enable this feature on linux for now

2022-01-20 17:50 UTC, dayeh-xilinx commented
retest this please. Cancelled from queue to give way to PR#6149

2022-01-21 02:35 UTC, gbuildx commented
Build Passed!

2022-01-21 18:51 UTC, gbuildx commented
Build Passed!

2022-02-27 08:26 UTC, closed without merging

2022-02-27 08:27 UTC, chvamshi-xilinx commented
Naresh will send a new PR with suggested changes.