Cr 1113771 -  Add command line auto-completion to xbutil and xbmgmt
Xilinx/XRT pull request #6045
Opened 2021-12-04 23:18 UTC by dbenusov-xilinx

#### Problem solved by the commit
[https://jira.xilinx.com/browse/CR-1113771](url)
xbutil and xbmgmt sub-commands becomes longer than before. To help users use these utilities, please add second level sub-commands auto-completion feature for bash.

#### How problem was solved, alternative solutions (if any) and why they were rejected
Added Bash and tcsh autocomplete scripts in to the codebase. The setup scripts were changed to source the added scripts to enable the autocomplete features.

#### Risks (if any) associated the changes in the commit
Changes to the setup script may cause issues on some systems if they have the PATH set to previous installations of XRT and run the setup scripts. This could potential offer commands that are not available to the older version of XRT. This can be mitigated by recommending all users to source the setup scripts (as they should).

#### What has been tested and how, request additional testing if necessary
tcsh example
```
xsjpranjal01:~% source /proj/xsjhdstaff6/dbenusov/XRT/build/Debug/opt/xilinx/xrt/setup.csh
/usr/local/bin/mis_env: No such file or directory.
Autocomplete enabled for the xbutil command
Autocomplete enabled for the xbmgmt command
XILINX_XRT        : /proj/xsjhdstaff6/dbenusov/XRT/build/Debug/opt/xilinx/xrt/
PATH              : /proj/xsjhdstaff6/dbenusov/XRT/build/Debug/opt/xilinx/xrt//bin:/usr/sbin:/proj/xsjhdstaff6/dbenusov/XRT/build/Debug/opt/xilinx/xrt//bin:/usr/sbin:/proj/xsjhdstaff6/dbenusov/XRT/build/Debug/opt/xilinx/xrt//bin:/usr/sbin:/usr/sbin:/proj/xsjhdstaff6/dbenusov/XRT/build/Debug/opt/xilinx/xrt//bin:/usr/sbin:/opt/xilinx/xrt/bin:/usr/sbin:/usr/sbin:/opt/xilinx/xrt/bin:/usr/sbin:/home/dbenusov/bin:/usr/local/bin:/mis/TREE/bin:/usr/bin:/bin:/usr/ucb
LD_LIBRARY_PATH   : /proj/xsjhdstaff6/dbenusov/XRT/build/Debug/opt/xilinx/xrt//lib:/proj/xsjhdstaff6/dbenusov/XRT/build/Debug/opt/xilinx/xrt//lib:/proj/xsjhdstaff6/dbenusov/XRT/build/Debug/opt/xilinx/xrt//lib:/proj/xsjhdstaff6/dbenusov/XRT/build/Debug/opt/xilinx/xrt//lib:/opt/xilinx/xrt/lib:/opt/xilinx/xrt/lib:/usr/local/lib:/usr/lib
PYTHONPATH        : /proj/xsjhdstaff6/dbenusov/XRT/build/Debug/opt/xilinx/xrt//python:/proj/xsjhdstaff6/dbenusov/XRT/build/Debug/opt/xilinx/xrt//python:/proj/xsjhdstaff6/dbenusov/XRT/build/Debug/opt/xilinx/xrt//python:/proj/xsjhdstaff6/dbenusov/XRT/build/Debug/opt/xilinx/xrt//python:/opt/xilinx/xrt/python:/opt/xilinx/xrt/python
xsjpranjal01:~% xbmgmt
--batch   examine   -h        program   --verbose
dump      --force   --help    reset     --version
xsjpranjal01:~% xbmgmt program
--base             --force            --revert-to-golden --verbose
--batch            -h                 --shell            --version
-d                 --help             -u
--device           --image            --user
xsjpranjal01:~% xbmgmt program -
--base             --force            --revert-to-golden --verbose
--batch            -h                 --shell            --version
-d                 --help             -u
--device           --image            --user
xsjpranjal01:~% xbutil
configure examine   program   reset     validate
xsjpranjal01:~% xbutil
configure examine   program   reset     validate
xsjpranjal01:~% xbutil program
--batch   --device  -h        -u        --verbose
-d        --force   --help    --user    --version
xsjpranjal01:~% xbutil program --
--batch   --device  --force   --help    --user    --verbose --version
xsjpranjal01:~% xbutil program --ver
--verbose --version
xsjpranjal01:~% xbutil program --version
--batch   --device  -h        -u        --verbose
-d        --force   --help    --user    --version
xsjpranjal01:~% xbutil program --version -
```
bash example
```
dbenusov@xsjpranjal01:~$ source /proj/xsjhdstaff6/dbenusov/XRT/build/Debug/opt/xilinx/xrt/setup.sh
Autocomplete enabled for the xbutil command
Autocomplete enabled for the xbmgmt command
XILINX_XRT        : /proj/xsjhdstaff6/dbenusov/XRT/build/Debug/opt/xilinx/xrt
PATH              : /proj/xsjhdstaff6/dbenusov/XRT/build/Debug/opt/xilinx/xrt/bin:/proj/xsjhdstaff6/dbenusov/XRT/build/Debug/opt/xilinx/xrt//bin:/usr/sbin:/home/dbenusov/bin:/usr/local/bin:/mis/TREE/bin:/usr/bin:/bin:/usr/ucb
LD_LIBRARY_PATH   : /proj/xsjhdstaff6/dbenusov/XRT/build/Debug/opt/xilinx/xrt/lib:/proj/xsjhdstaff6/dbenusov/XRT/build/Debug/opt/xilinx/xrt//lib:/usr/local/lib:/usr/lib
PYTHONPATH        : /proj/xsjhdstaff6/dbenusov/XRT/build/Debug/opt/xilinx/xrt/python:/proj/xsjhdstaff6/dbenusov/XRT/build/Debug/opt/xilinx/xrt//python
dbenusov@xsjpranjal01:~$ xbutil
program    examine    reset      --batch    --help     --version
validate   configure  --verbose  --force    -h
dbenusov@xsjpranjal01:~$ xbutil validate -
--run      --format   --output   --device   --verbose  --force    -h
-r         -f         -o         -d         --batch    --help     --version
dbenusov@xsjpranjal01:~$ xbutil validate -
--run      --format   --output   --device   --verbose  --force    -h
-r         -f         -o         -d         --batch    --help     --version
dbenusov@xsjpranjal01:~$ xbutil validate --
--run      --output   --verbose  --force    --version
--format   --device   --batch    --help
dbenusov@xsjpranjal01:~$ xbutil validate -
--run      --format   --output   --device   --verbose  --force    -h
-r         -f         -o         -d         --batch    --help     --version
dbenusov@xsjpranjal01:~$ xbutil validate --
--run      --output   --verbose  --force    --version
--format   --device   --batch    --help
dbenusov@xsjpranjal01:~$ xbutil validate --ver
--verbose  --version
dbenusov@xsjpranjal01:~$ xbutil validate --ver
--verbose  --version
dbenusov@xsjpranjal01:~$ xbutil validate --version -
--run      --format   --output   --device   --verbose  --force    -h
-r         -f         -o         -d         --batch    --help     --version
dbenusov@xsjpranjal01:~$ xbmgmt
dump       program    --verbose  --force    -h
examine    reset      --batch    --help     --version
dbenusov@xsjpranjal01:~$ xbmgmt examine -
--report   --format   --output   --device   --verbose  --force    -h
-r         -f         -o         -d         --batch    --help     --version
dbenusov@xsjpranjal01:~$ xbmgmt examine -
--report   --format   --output   --device   --verbose  --force    -h
-r         -f         -o         -d         --batch    --help     --version
dbenusov@xsjpranjal01:~$ xbmgmt examine --
--report   --output   --verbose  --force    --version
--format   --device   --batch    --help
dbenusov@xsjpranjal01:~$ xbmgmt examine --for
--format  --force
dbenusov@xsjpranjal01:~$ xbmgmt examine --for
--format  --force
dbenusov@xsjpranjal01:~$ xbmgmt examine --format asdf -
--report   --format   --output   --device   --verbose  --force    -h
-r         -f         -o         -d         --batch    --help     --version
dbenusov@xsjpranjal01:~$ xbmgmt examine --format asdf -
```
#### Documentation impact (if any)
Would need to write into the documentation that this is available.

2021-12-05 00:43 UTC, gbuildx commented
Build Failed! :(

2021-12-05 02:37 UTC, dayeh-xilinx commented
retest this please. Looks like an infra error.

2021-12-05 04:04 UTC, gbuildx commented
Build Failed! :(

2021-12-06 11:13 UTC, xilinxgitops commented
retest this looks like infra error.

2021-12-06 18:37 UTC, AShivangi requested changes
Minor changes requested, but the code looks good overall! Thanks for adding extensive comments :) 

@stsoe, should we advertise this in the changelog?

2021-12-06 18:37 UTC, AShivangi commented on src/runtime_src/core/tools/CMakeLists.txt
> +endif()
Add an empty line after this

2021-12-06 18:37 UTC, AShivangi commented on src/runtime_src/core/tools/xbmgmt2/xbmgmt-bash-completion
> +# Copyright (C) 2019-2021 Xilinx, Inc. All rights reserved.
```suggestion
# Copyright (C) 2021 Xilinx, Inc. All rights reserved.
```

2021-12-06 18:37 UTC, AShivangi commented on src/runtime_src/core/tools/xbmgmt2/xbmgmt-bash-completion
> +# ex: filetype=sh
Add empty line

2021-12-06 18:37 UTC, AShivangi commented on src/runtime_src/core/tools/xbmgmt2/xbmgmt-csh-completion
> +# Copyright (C) 2019-2021 Xilinx, Inc. All rights reserved.
```suggestion
# Copyright (C) 2021 Xilinx, Inc. All rights reserved.
```

2021-12-06 18:37 UTC, AShivangi commented on src/runtime_src/core/tools/xbmgmt2/xbmgmt-csh-completion-wrapper
> +# Copyright (C) 2019-2021 Xilinx, Inc. All rights reserved.
```suggestion
# Copyright (C) 2021 Xilinx, Inc. All rights reserved.
```

2021-12-06 18:37 UTC, AShivangi commented on src/runtime_src/core/tools/xbutil2/xbutil-bash-completion
> +# Copyright (C) 2019-2021 Xilinx, Inc. All rights reserved.
```suggestion
# Copyright (C) 2021 Xilinx, Inc. All rights reserved.
```

2021-12-07 01:25 UTC, keryell commented
Interesting feature! :-)
Are there equivalent features for, say, Vitis or Vivado?

2021-12-07 16:07 UTC, stsoe approved these changes
Interesting indeed.  I was not aware of this mechanism.  Doesn't look very scalable, but cool indeed.   

@keryell, no Vitis and Vivado does not have this at the command line level, but does have same completion (libedit) at the Tcl shell level at least.

2021-12-08 00:55 UTC, AShivangi approved these changes
Looks good!

2021-12-08 05:49 UTC, gbuildx commented
Build Failed! :(

2021-12-08 16:21 UTC, rozumx approved these changes
Good good.
Thank you for making these changes.

2021-12-09 23:54 UTC, dbenusov-xilinx commented
retest this please.

2021-12-10 11:49 UTC, gbuildx commented
Build Failed! :(

2021-12-10 14:37 UTC, xilinxgitops commented
retest this please

2021-12-10 22:10 UTC, gbuildx commented
Build Failed! :(

2021-12-11 08:16 UTC, gbuildx commented
Build Passed!

2021-12-11 15:23 UTC, sonals commented
Simply awesome! It was on my personal wish list for so long...

2021-12-13 18:42 UTC, merged