CR-1116870: 1.Emu driver uses xclbin_parser logic 2. Canary is neat
Xilinx/XRT pull request #6091
Opened 2021-12-22 09:51 UTC by udaybhas-xilinx

Description::
1.Emu driver uses xclbin_parser logic 

CR's:: 1. https://jira.xilinx.com/browse/CR-1116870
          2. https://jira.xilinx.com/browse/CR-1116752

Problem solved: Emu driver uses xclbin parser logic instead of parsing the xml file

Risk: Low

Tests: 1. Canary is neat.
          2. Verified with these examples:: hello_world, mult_compute_units, streaming_k2k_mm and kernel_swap examples

2021-12-22 10:06 UTC, stsoe requested changes
I don't think changes / addition to xclbin_parser.cpp to parse xml data are necessary.
Please leverage xrt::xclbin APIs, both public (include/experimental/xrt_xclbin.h) and internal ones (core/common/api/xclbin_int.h).  The xrt::xclbin objects capture all meta data associated with an xclbin.

Secondly, none of the code in this PR is documented, if any new code is added, please make sure to add good comments for new functions and explain what the code is doing and why.

I suggest this PR is closed, and reworked per above suggestions.

2021-12-22 10:50 UTC, stsoe requested changes

2021-12-22 10:50 UTC, stsoe commented on src/runtime_src/core/common/xclbin_parser.cpp
> +get_kernel_instance_map( const char* xml_data, size_t xml_size) {
This is xrt::xclbin::get_ips() and variants.  The xrt::xclbin::ip has member functions for accessing most of the data you need,  if some data is missing, please let @stsoe know.

2021-12-22 10:50 UTC, stsoe commented on src/runtime_src/core/common/xclbin_parser.cpp
> +get_device_name(const char* xmlFile,size_t xmlFileSize)
The device name per XML is not currently extracted by xrt::xclbin, but please use same approach as used for project name (see common/api/xclbin_int.h, xrt_xclbin.cpp).

2021-12-22 10:50 UTC, stsoe commented on src/runtime_src/core/common/xclbin_parser.cpp
> +check_if_multiple_platform_exists(const char* xml_data, size_t xml_size)
This is always false, no where in XRT do we support multiple platforms per xml

2021-12-22 10:50 UTC, stsoe commented on src/runtime_src/core/common/xclbin_parser.cpp
> +{
Also false, the xml will never have multiple cores, that is not supported nor will it ever be supported via XML core element.

2021-12-22 10:50 UTC, stsoe commented on src/runtime_src/core/common/xclbin_parser.cpp
> +{
This is a kernel property which is accessible via core/common/api/xclbin_int.h:get_properties(kernel).

2021-12-22 10:50 UTC, stsoe commented on src/runtime_src/core/common/xclbin_parser.h
> +};
Should not be needed.

2021-12-22 16:50 UTC, gbuildx commented
Can one of the admins verify this patch?

2022-01-05 13:54 UTC, closed without merging

2022-01-05 13:55 UTC, udaybhas-xilinx commented
Creating a new pull request with changes made..