CR-1116717 ASTER TC 18.01 - xbutil dmatest: "ERROR: DMA failed: No such file or directory" when running test for 256MB
Xilinx/XRT pull request #6184
Opened 2022-01-27 00:09 UTC by chienwei-lan

#### Problem solved by the commit
Run xclSyncBo with non-exist BO handle, we have one BO and two DMA threads in this case, adjust_e will be b+2 which is invalid and should be b+1 since we only have one BO, choose the smaller number between BO list and DMA threads

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
#4971

2022-01-27 02:39 UTC, xuhz approved these changes

2022-01-27 02:50 UTC, gbuildx commented
Build Failed! :(

2022-01-28 16:14 UTC, chienwei-lan commented
retest this please

2022-01-29 07:11 UTC, gbuildx commented
Build Failed! :(

2022-01-31 00:05 UTC, gbuildx commented
Build Passed!

2022-02-01 03:43 UTC, stsoe requested changes

2022-02-01 03:43 UTC, stsoe commented on src/runtime_src/core/pcie/common/dmatest.h
> +            const auto ajust_e = b + len * std::min(count, (unsigned)len);
```suggestion
            const auto ajust_e = b + len * std::min<unsigned int>(count, len);
```

2022-02-02 09:28 UTC, gbuildx commented
Build Failed! :(

2022-02-03 19:08 UTC, stsoe approved these changes

2022-02-03 21:14 UTC, gbuildx commented
Build Failed! :(

2022-02-04 08:10 UTC, gbuildx commented
Build Failed! :(

2022-02-04 21:08 UTC, dayeh-xilinx commented
retest this please. Infra error caused by github.com fetch.

2022-02-05 07:49 UTC, gbuildx commented
Build Failed! :(

2022-02-05 13:52 UTC, sabarinaxil commented
retest this please

2022-02-05 14:26 UTC, xilinxgitops commented
retest this please

2022-02-05 16:29 UTC, gbuildx commented
Build Passed!

2022-02-05 18:23 UTC, merged