xclbinutil: Added new OVERLAY section
Xilinx/XRT pull request #6190
Opened 2022-01-27 16:58 UTC by rozumx

New Functionality
Added a new OVERLAY section section for SOM overlays

#### Risks (if any) associated the changes in the commit
Low to none

#### What has been tested and how, request additional testing if necessary
1. Added new unit regression test for this OVERLAY buffer. 
2. Manual testing

#### Documentation impact (if any)
N/A

2022-01-27 17:01 UTC, AShivangi approved these changes

2022-01-27 18:18 UTC, stsoe requested changes
It would be helpful if the PR description explained what an overlay is and how it is used.

2022-01-27 23:01 UTC, stsoe approved these changes

2022-01-28 02:07 UTC, rozumx commented
retest this please

2022-01-28 09:38 UTC, gbuildx commented
Build Failed! :(

2022-01-28 18:43 UTC, rozumx commented
retest this please

2022-01-29 06:40 UTC, gbuildx commented
Build Passed!

2022-01-29 06:49 UTC, merged