CR-1119089 Add init script to inform apu booted successfully
Xilinx/XRT pull request #6195
Opened 2022-01-28 06:25 UTC by rbramand-xilinx

> Added changes in build_edge.sh to create a init script that will run after apu boot
> This init script will write to sysfs entry exposed by zocl to indicate apu booted successfully
> Fixed build_edge.sh -full compilation error
> Minor fix: Added -n option to sbuild to print log to stdout

2022-01-28 06:41 UTC, chvamshi-xilinx requested changes
Hi @rbramand-xilinx , Can you please create a file in separate directory and maintain instead of creating file inside script.

2022-01-28 16:51 UTC, rozumx approved these changes
Looks reasonable.  

Side Note
The formatted indention of this file should be re-examined for it makes the code somewhat obfuscated and difficult to follow the intent.  Being that data files are being produced by it, there might not be anything that can be done.

2022-01-28 16:51 UTC, rozumx commented on build/build_edge.sh
> +    # Create script to check apu boot
Format regarding the indention looks weird.

2022-01-28 17:32 UTC, chvamshi-xilinx requested changes
We shouldnt have full rootfs config file here. Just update only configs which u r updating.

2022-01-29 02:24 UTC, gbuildx commented
Build Passed!

2022-01-31 15:24 UTC, chvamshi-xilinx approved these changes
Looks good.
Can you please send this recipe to yocto sothat we dont need to maintain in future.

2022-01-31 15:25 UTC, rbramand-xilinx commented
> Looks good. Can you please send this recipe to yocto sothat we dont need to maintain in future.

sure @chvamshi-xilinx

2022-01-31 15:59 UTC, gbuildx commented
Build Failed! :(

2022-01-31 16:59 UTC, houlz0507 approved these changes

2022-01-31 21:00 UTC, dayeh-xilinx commented
retest this please. Fixed the centos8 repo issue.

2022-02-02 08:47 UTC, gbuildx commented
Build Passed!

2022-02-02 08:51 UTC, merged