VITIS 2383: xbutil to show usage stats for all BO types
Xilinx/XRT pull request #6196
Opened 2022-01-28 13:03 UTC by sarab96

Example Output:
Verbose: Enabling Verbosity
Verbose: SubCommand: advanced
Verbose: SubCommand option: Show usage stats of all BO types
Verbose: Device: 0000:b3:00.1
Verbose: BO type: Regular    , Total size(KB): 0       , Num of BOs: 0    
Verbose: BO type: UserPointer, Total size(KB): 0       , Num of BOs: 0    
Verbose: BO type: P2P        , Total size(KB): 0       , Num of BOs: 0    
Verbose: BO type: DeviceOnly , Total size(KB): 0       , Num of BOs: 0    
Verbose: BO type: Imported   , Total size(KB): 0       , Num of BOs: 0    
Verbose: BO type: ExecBuf    , Total size(KB): 0       , Num of BOs: 0    
Verbose: BO type: CMA        , Total size(KB): 0       , Num of BOs: 0    
Verbose: Show BO stats succeeded

#### Problem solved by the commit
None. Early access feature for xbutil to show usage stats of BOs
#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
None
#### What has been tested and how, request additional testing if necessary
Tested locally
#### Documentation impact (if any)
To be done as early access

2022-01-28 17:32 UTC, rozumx reviewed
Why isn't this functionality a report?

2022-01-29 00:19 UTC, gbuildx commented
Build Failed! :(

2022-01-29 02:32 UTC, dayeh-xilinx commented
retest this please. Infra error. gitenterprise.xilinx.com went down for maintainance.

2022-01-29 16:00 UTC, sarab96 commented on src/runtime_src/core/tools/xbutil2/CMakeLists.txt
>    "OO_P2P.cpp"
done

2022-01-29 16:01 UTC, sarab96 commented on src/runtime_src/core/tools/xbutil2/OO_BOStats.cpp
> +          % bo_info[0].substr(1, bo_info[0].length()-2)
updated

2022-01-29 18:38 UTC, gbuildx commented
Build Passed!

2022-01-29 20:29 UTC, gbuildx commented
Build Failed! :(

2022-01-30 07:30 UTC, salindac commented
retest this please. Infra error, xtc data dir got removed

2022-01-30 11:34 UTC, gbuildx commented
Build Passed!

2022-01-31 17:38 UTC, AShivangi requested changes
A few changes requested

2022-02-02 22:39 UTC, rozumx requested changes
Sarabjeet and I have discussed this PR.  
It has been decided to move this functionality from a custom "advance" subcommand to a "hidden" report.  As such, this PR should be closed out.

2022-02-03 11:59 UTC, sarab96 commented
As discussed will submit new PR

2022-02-03 11:59 UTC, closed without merging