MB ERT XGQ indentify cmd
Xilinx/XRT pull request #6199
Opened 2022-01-28 18:59 UTC by chienwei-lan

#### Problem solved by the commit
Add XGQ_CMD_OP_INDENTIFY

2022-01-29 06:48 UTC, stsoe requested changes
The description of this PR is not good.  The change is trivial but what on earth is XGQ_CMD_OP_INDENTIFY command.  First the title and description is misspelled, but even then I don't know what "identify" command is.?  In short just add a better description.

2022-01-29 08:58 UTC, gbuildx commented
Build Passed!

2022-01-31 17:43 UTC, mamin506 approved these changes
Look good to me.

2022-02-01 00:25 UTC, mamin506 approved these changes

2022-02-01 00:32 UTC, chienwei-lan commented
> The description of this PR is not good. The change is trivial but what on earth is XGQ_CMD_OP_INDENTIFY command. First the title and description is misspelled, but even then I don't know what "identify" command is.? In short just add a better description.

Sorry, I was not paying enough attention and didn't even notice that I misspelt the word.

I add description for people to better understand what's the PR actually does improve/solve

2022-02-01 00:45 UTC, stsoe approved these changes
Thank you!

2022-02-02 01:57 UTC, gbuildx commented
Build Passed!

2022-02-02 02:52 UTC, merged