CR 1117644 Generated the static libs for hw_emu and sw_emu driver cod…
Xilinx/XRT pull request #6217
Opened 2022-02-02 06:13 UTC by venkatp-xilinx

…e base

Enhancement request to have the Static HAL libs for hw_emu and sw_emu

This is an issue filed with the CR 1117644

As requested, created the static HAL libraries for hw_emu and sw_emu which helps  to have statically compiled host code for hw/sw emulation

No Risk

Verified the existing scenarios. All are looking good

No

2022-02-02 07:20 UTC, chvamshi-xilinx approved these changes
Looks good. Hope you have verified one simple test with these static libraries.

2022-02-03 07:48 UTC, gbuildx commented
Build Failed! :(

2022-02-03 17:20 UTC, stsoe requested changes

2022-02-03 17:20 UTC, stsoe commented on src/runtime_src/core/pcie/emulation/cpu_em/CMakeLists.txt
> +  PRIVATE
INTERFACE, please see comment in core/pcie/linux/CMakeLists.txt

2022-02-03 17:20 UTC, stsoe commented on src/runtime_src/core/pcie/emulation/hw_em/CMakeLists.txt
> +  PRIVATE
Ditto

2022-02-03 17:20 UTC, stsoe commented on src/runtime_src/core/pcie/emulation/common_em/CMakeLists.txt
> +)
I would suggest to include common_em_objects in the static shim emulation libraries and not release common_em library.

2022-02-08 18:22 UTC, gbuildx commented
Build Passed!

2022-02-09 04:50 UTC, stsoe approved these changes

2022-02-09 04:50 UTC, merged