CR-1118707::Python based host code design support for emulationflow
Xilinx/XRT pull request #6218
Opened 2022-02-02 13:14 UTC by udaybhas-xilinx

Problem solved by the commit
Python based host code design support for emulationflow

#### Bug / issue (if any) fixed, 
https://jira.xilinx.com/browse/CR-1118707

#### How problem was solved, alternative solutions (if any) and why they were rejected
Made changes to load the proper library based on “XCL_EMULATION_MODE” 

#### Risks (if any) associated the changes in the commit
Low Risk

#### What has been tested and how, request additional testing if necessary
Verified sw_emu and hw_emu examples  for u250 paltform

#### Documentation impact (if any)
NA

2022-02-02 13:16 UTC, gbuildx commented
Can one of the admins verify this patch?

2022-02-02 14:49 UTC, chvamshi-xilinx reviewed
Please update the print messages. These messages looks like debug messages..
Is sw_emu crash issue fixed? If no, are there more changes required?

2022-02-02 14:49 UTC, chvamshi-xilinx commented
ok to test

2022-02-02 15:09 UTC, udaybhas-xilinx commented
> Looks good. Please update the print messages. These messages looks like debug messages.. Is sw_emu crash issue fixed? If no, are there more changes required?

No crash is observed in sw_emu...

2022-02-02 15:14 UTC, chvamshi-xilinx commented
> > Looks good. Please update the print messages. These messages looks like debug messages.. Is sw_emu crash issue fixed? If no, are there more changes required?
> 
> No crash is observed in sw_emu...

Good to know.

2022-02-02 15:50 UTC, chvamshi-xilinx approved these changes

2022-02-03 13:39 UTC, gbuildx commented
Build Failed! :(

2022-02-03 16:24 UTC, stsoe reviewed
I thought we were moving exclusively to pybind11?
Are we sure these ctypes bindings are what we want?

2022-02-03 20:11 UTC, AShivangi commented
Good point Soren. I see python test cases including xrt_binding.py, etc. as well as pyxrt. That doesn't make sense. I think we need to refactor the test cases to not rely on *_binding.py and get rid of those files all together

2022-02-04 02:49 UTC, dayeh-xilinx commented
retest this please. Infra error caused by branching work.

2022-02-04 08:37 UTC, gbuildx commented
Build Failed! :(

2022-02-04 21:09 UTC, dayeh-xilinx commented
retest this please. Infra error caused by github.com fetch.

2022-02-05 02:23 UTC, gbuildx commented
Build Failed! :(

2022-02-05 18:18 UTC, dayeh-xilinx commented
retest this please. Infra error caused by windows role account lockout.

2022-02-06 16:41 UTC, gbuildx commented
Build Passed!

2022-02-07 17:28 UTC, AShivangi approved these changes

2022-02-08 16:10 UTC, stsoe requested changes
Hi @udaybhas-xilinx.  Please respond to my comment about pybind11 and why you are using ctypes.

2022-02-09 04:52 UTC, venkatp-xilinx commented
> Hi @udaybhas-xilinx. Please respond to my comment about pybind11 and why you are using ctypes.

@stsoe, some legacy test cases are using ctypes still, just to address those legacy designs, we need to do these modifications. I could see the test case in the CR is using the xrt_bindings and pybind11 together. We tried commenting the ctypes usage in the test case, yet resulted the same issue. However with these changes we could see test is passing.

2022-02-09 04:59 UTC, stsoe requested changes
I don't think we should change the ctypes bindings. I updated the CR.

2022-02-09 05:03 UTC, stsoe commented
> @stsoe, some legacy test cases are using ctypes still, just to address those legacy designs, we need to do these modifications. I could see the test case in the CR is using the xrt_bindings and pybind11 together. We tried commenting the ctypes usage in the test case, yet resulted the same issue. However with these changes we could see test is passing.

Let not cater to legacy tests that should be updated.  It's not a good idea to add obsolete code to the system.

2022-02-09 05:04 UTC, stsoe commented
> @stsoe, some legacy test cases are using ctypes still, just to address those legacy designs, we need to do these modifications. I could see the test case in the CR is using the xrt_bindings and pybind11 together. We tried commenting the ctypes usage in the test case, yet resulted the same issue. However with these changes we could see test is passing.

Let not cater to legacy tests that should be updated.  It's not a good idea to add obsolete code to the system.

2022-02-09 05:49 UTC, stsoe commented
Hi @AShivangi Do you think you can help understand why these the changes proposed in this PR would be necessary if the application is using pyxrt pybind11?   I am not understanding why xrt_bindings. needs to be modified to check an XCL_EMULATION_MODE when xrt_coreutil does this and when pyxrt is linked with this library.

2022-02-10 10:50 UTC, venkatp-xilinx commented
> > Hi @AShivangi Do you think you can help understand why these the changes proposed in this PR would be necessary if the application is using pyxrt pybind11? I am not understanding why xrt_bindings. needs to be modified to check an XCL_EMULATION_MODE when xrt_coreutil does this and when pyxrt is linked with this library.
> 
> Hi @stsoe, I believe that the python test cases are still dependent on xclbin_binding.py and ert_binding.py. For eg: in `tests/python/utils_binding.py` we have `wrap_get_axlf_section(..)` which comes from xclbin_binding.py. I agree with you that we shouldn't be supporting the ctypes anymore, but adding xclbin and ert bindings through pybind is a much bigger task.

@stsoe, I can see a label do-not-merge added to this PR. However with the latest comments from @AShivangi, seems its necessary to change the xclbin_bindings and ert bindings even though users use just the pybind11. Are we going to merge this change?

2022-02-10 19:30 UTC, AShivangi commented
@stsoe, I hadn't looked at python tests for a while, so wasn't aware of what is not being used anymore. Thanks for looking into it. I agree with you that we should improve the python test cases to not use the bindings anymore. This leads me to question the ctypes bindings altogether. Should we still expose them to the user?
Also, who will be fixing the tests? I do not have the bandwidth to do it for this release.

2022-03-23 04:26 UTC, chvamshi-xilinx commented
Closing as emulations tests working with pyxrt(native xrt apis)

2022-03-23 04:26 UTC, closed without merging