CR-1120510 : AIE report produces non-UTF-8 characters in error_msg
Xilinx/XRT pull request #6275
Opened 2022-02-15 12:12 UTC by saifuddin-xilinx

Issue : 
While generating aie_status_edge.json which comes from the XRT device info reports under the hood. The third line of the file contains an error_msg string. However, this string contains characters that are not UTF-8 and therefore, parsing this file throws an exception.

CR:
https://jira.xilinx.com/browse/CR-1120510

Added a destructor as "zynq_device" class and reset the sysfs file name. 
Without that sysfs file is holding some garbage value and the same is reflected on the report.

2022-02-15 14:35 UTC, gbuildx commented
Build Failed! :(

2022-02-15 19:04 UTC, dayeh-xilinx commented
retest this please.

2022-02-15 20:22 UTC, keryell commented
While I understand that this might fix a bug, you initialize a member variable in the destructor, and just after the call to the destructor, the variable member will be destructed anyway so this initialization should be useless.
Except if the bug is somewhere else and someone has captured the address of this zombie string and is using it later...
I am also curious about why XRT should produce UTF-8 at the first place. Is there any UTF-8 support at all?

2022-02-15 22:49 UTC, stsoe requested changes
This change does not make any sense.  Why would sysfs_root be accessed after the zynq_device has been closed?

2022-02-15 22:52 UTC, gbuildx commented
Build Passed!

2022-02-16 02:33 UTC, salindac commented
retest please

2022-02-16 02:57 UTC, chvamshi-xilinx commented
Same here. Please close the PR and check who is holding the device handle after close. I assume, this must be from XDP somewhere.

2022-02-17 04:41 UTC, closed without merging