Use new xbutil commands to enable host memory
Xilinx/XRT pull request #6276
Opened 2022-02-15 19:42 UTC by mariodruiz

#### Problem solved by the commit

Update the documentation to use new `xbutil` commands 

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered

#### How problem was solved, alternative solutions (if any) and why they were rejected

#### Risks (if any) associated the changes in the commit

None

#### What has been tested and how, request additional testing if necessary

#### Documentation impact (if any)

2022-02-15 19:44 UTC, gbuildx commented
Can one of the admins verify this patch?

2022-02-15 22:47 UTC, stsoe commented
@mariodruiz The source for the edited page is actually this one: https://github.com/Xilinx/XRT/blob/master/src/runtime_src/doc/toc/hm.rst

@uday610 FYI

2022-02-15 22:47 UTC, stsoe requested changes
Per comment

2022-02-16 08:38 UTC, closed without merging

2022-02-16 08:40 UTC, mariodruiz commented
I knew I was doing something wrong. I'll open a new PR, I somehow broke the history