CR-1123904 XRT - Request a hot reset if XMC packet error received during SC upgrade
Xilinx/XRT pull request #6417
Opened 2022-03-15 06:20 UTC by chienwei-lan

#### Problem solved by the commit
During an SC upgrade, if XRT receives a CMC_HOST_MSG_SAT_FW_WRITE_FAIL(XMC Packet Error 4), it will resend the failed segment again which is not ideal. We should halt the upgrade and hot reset the board instead of resending the firmware segment.

#### How problem was solved, alternative solutions (if any) and why they were rejected
XRT provides two ways to upgrade SC, one is via host by mapping the bar, the other one is via xmc driver.

1. Remove the retry part, when error happens during SC upgrade, we should stop upgrading SC instead of resending 
2. Set xmc state to XMC_STATE_ERROR in xmc driver and promote hot reset in dmesg

2022-03-15 15:30 UTC, maxzhen approved these changes

2022-03-15 16:18 UTC, AShivangi approved these changes
one comment, the rest looks good.

2022-03-15 18:01 UTC, rozumx requested changes
Some minor changes.

2022-03-15 20:13 UTC, gbuildx commented
Build Failed! :(

2022-03-15 20:13 UTC, gbuildx commented
Build Failed! :(

2022-03-16 07:39 UTC, gbuildx commented
Build Passed!

2022-03-16 22:07 UTC, rozumx approved these changes

2022-03-16 22:07 UTC, merged