CR-1122697 xbmgmt examine returns incorrect code when missing nodes
Xilinx/XRT pull request #6443
Opened 2022-03-18 01:20 UTC by dbenusov-xilinx

#### Problem solved by the commit
https://jira.xilinx.com/browse/CR-1122697
Running "xbmgmt -new examine -r all -d <bdf>" provides an incorrect return code when the card is in the manufacturing state.

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
Running an xbmgmt examine command on a device with a golden image would result in certain reports failing to complete, generating a non-zero return code. Also the CMC report is not displaying correctly. XRT should account for the missing node and display that the information is available rather than giving a non-zero return code.
```
root@xsjpranjal01:~# xbmgmt examine  -d 17:00 -r all
System Configuration
  OS Name              : Linux
  Release              : 5.4.0-100-generic
  Version              : #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022
  Machine              : x86_64
  CPU Cores            : 16
  Memory               : 15695 MB
  Distribution         : Ubuntu 20.04 LTS
  GLIBC                : 2.31
  Model                : Precision 5820 Tower

XRT
  Version              : 2.13.0
  Branch               : CR-1119432
  Hash                 : 503b24648d48cddf7ef4780845c21e2b5a33b6fc
  Hash Date            : 2022-03-16 17:27:53
  XOCL                 : 2.13.0, d3575d38cd0ca898ee3f0fb39cc43c9affd2814c
  XCLMGMT              : 2.13.0, d3575d38cd0ca898ee3f0fb39cc43c9affd2814c

Devices present
BDF             :  Shell                      Platform UUID  Device ID
[0000:65:00.0]  :  xilinx_u280_xdma_201920_3  0x5e278820     mgmt(inst=25856)
[0000:17:00.0]  :  xilinx_u250_GOLDEN_5       n/a            n/a

----------------------------------------
1/1 [0000:17:00.0] : xilinx_u250_GOLDEN
----------------------------------------
Flash properties
  Type                 : spi
  Serial Number        : N/A

Device properties
  Type                 : u250
  Name                 : N/A
  Config Mode          : 4231162064
  Max Power            : N/A

Flashable partitions running on FPGA
  Platform             : xilinx_u250_GOLDEN_5
  SC Version           : INACTIVE
  Platform ID          : N/A

Flashable partitions installed in system
  <none found>

WARNING  : No shell is installed on the system.

Mechanical
  Fans
    Not present

Firewall
  Level -- --: -- --

Mailbox
  ERROR: Failed to find subdirectory for mailbox under /sys/bus/pci/devices/0000:17:00.0

CMC
Vmr Status
  Information Unavailable
root@xsjpranjal01:~# echo $?
1
```

#### How problem was solved, alternative solutions (if any) and why they were rejected
Fixed error in mailbox report for missing node and updated the message in to to display information unavailable. Also updated message in cmc to display information missing when nodes are not accessible.

#### Risks (if any) associated the changes in the commit
None, should be safer than before!

#### What has been tested and how, request additional testing if necessary
On functional u280:
```
root@xsjpranjal01:~# xbmgmt examine  -d 65:00 -r all
System Configuration
  OS Name              : Linux
  Release              : 5.4.0-100-generic
  Version              : #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022
  Machine              : x86_64
  CPU Cores            : 16
  Memory               : 15695 MB
  Distribution         : Ubuntu 20.04 LTS
  GLIBC                : 2.31
  Model                : Precision 5820 Tower

XRT
  Version              : 2.13.0
  Branch               : CR-1122697
  Hash                 : 0167e209412320729348b2db638d980947bb35aa
  Hash Date            : 2022-03-17 17:49:48
  XOCL                 : 2.13.0, d3575d38cd0ca898ee3f0fb39cc43c9affd2814c
  XCLMGMT              : 2.13.0, d3575d38cd0ca898ee3f0fb39cc43c9affd2814c

Devices present
BDF             :  Shell                      Platform UUID  Device ID
[0000:65:00.0]  :  xilinx_u280_xdma_201920_3  0x5e278820     mgmt(inst=25856)
[0000:17:00.0]  :  xilinx_u250_GOLDEN_5       n/a            n/a

-----------------------------------------------
1/1 [0000:65:00.0] : xilinx_u280_xdma_201920_3
-----------------------------------------------
Flash properties
  Type                 : spi
  Serial Number        : 21760394400G

Device properties
  Type                 : N/A
  Name                 : ALVEO U280 PQ
  Config Mode          : 7
  Max Power            : 225W

Flashable partitions running on FPGA
  Platform             : xilinx_u280_xdma_201920_3
  SC Version           : 4.3.15
  Platform ID          : 0x5e278820

Flashable partitions installed in system
  Platform             : xilinx_u280_xdma_201920_3
  SC Version           : 4.3.15
  Platform ID          : 0x5e278820

  Mac Address          : 01:02:03:04:05:06
                       : 01:02:03:04:05:07

Mechanical
  Fans
    FPGA Fan 1
      Critical Trigger Temp : 44 C
      Speed                 : 1335 RPM

Firewall
  Level 0 : 0x0 (GOOD)

Mailbox
  Total bytes received   : 1185664 Bytes
  Unknown                : 0
  Test msg ready         : 0
  Test msg fetch         : 0
  Lock bitstream         : 0
  Unlock bitstream       : 0
  Hot reset              : 2
  Firewall trip          : 0
  Download xclbin kaddr  : 2
  Download xclbin        : 0
  Reclock                : 0
  Peer data read         : 9260
  User probe             : 2
  Mgmt state             : 0
  Change shell           : 0
  Reprogram shell        : 0
  P2P bar addr           : 0
                         : 0

CMC
  Status : 0x0 (GOOD)
  Runtime Clock Scaling :
    Supported : false
    Enabled : false
    Critical threshold (clock shutdown) limits:
      Power : 0 W
      Temperature : 0 C
    Throttling threshold limits:
      Power : 0 W
      Temperature : 0 C
    Power threshold override:
      Override : false
      Override limit : 0 W
    Temperature threshold override:
      Override : false
      Override limit : 0 C
Vmr Status
  Information Unavailable
root@xsjpranjal01:~# echo $?
0
```
On golden u250:
```
root@xsjpranjal01:~# xbmgmt examine  -d 17:00 -r all
System Configuration
  OS Name              : Linux
  Release              : 5.4.0-100-generic
  Version              : #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022
  Machine              : x86_64
  CPU Cores            : 16
  Memory               : 15695 MB
  Distribution         : Ubuntu 20.04 LTS
  GLIBC                : 2.31
  Model                : Precision 5820 Tower

XRT
  Version              : 2.13.0
  Branch               : CR-1122697
  Hash                 : 0167e209412320729348b2db638d980947bb35aa
  Hash Date            : 2022-03-17 17:49:48
  XOCL                 : 2.13.0, d3575d38cd0ca898ee3f0fb39cc43c9affd2814c
  XCLMGMT              : 2.13.0, d3575d38cd0ca898ee3f0fb39cc43c9affd2814c

Devices present
BDF             :  Shell                      Platform UUID  Device ID
[0000:65:00.0]  :  xilinx_u280_xdma_201920_3  0x5e278820     mgmt(inst=25856)
[0000:17:00.0]  :  xilinx_u250_GOLDEN_5       n/a            n/a

----------------------------------------
1/1 [0000:17:00.0] : xilinx_u250_GOLDEN
----------------------------------------
Flash properties
  Type                 : spi
  Serial Number        : N/A

Device properties
  Type                 : u250
  Name                 : N/A
  Config Mode          : 3710603232
  Max Power            : N/A

Flashable partitions running on FPGA
  Platform             : xilinx_u250_GOLDEN_5
  SC Version           : INACTIVE
  Platform ID          : N/A

Flashable partitions installed in system
  <none found>

WARNING  : No shell is installed on the system.

Mechanical
  Fans
    Not present

Firewall
  Level -- --: -- --

Mailbox
  Information unavailable
CMC
  Heartbeat information unavailable
  Runtime Clock Scaling :
    Information unavailable
Vmr Status
  Information Unavailable
root@xsjpranjal01:~# echo $?
0
```
On functional u200:
```
root@xsjsagarw50:~# xbmgmt examine -d b3:00 -r all
System Configuration
  OS Name              : Linux
  Release              : 5.4.0-100-generic
  Version              : #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022
  [...]

2022-03-18 03:04 UTC, gbuildx commented
Build Passed!

2022-03-18 16:16 UTC, AShivangi approved these changes

2022-03-18 17:51 UTC, rozumx requested changes

2022-03-18 17:51 UTC, rozumx commented on src/runtime_src/core/tools/common/ReportCmcStatus.cpp
>  {
Copyright date needs to updated (line 2).  In this case, a new line needs to be added:
`Copyright (c) 2022 Advanced Micro Devices, Inc.`

2022-03-18 17:51 UTC, rozumx commented on src/runtime_src/core/tools/common/ReportCmcStatus.cpp
> +  boost::property_tree::ptree pts;
We have extra characters available, please make your variables a little bit more description.

2022-03-18 17:51 UTC, rozumx commented on src/runtime_src/core/tools/common/ReportMailbox.cpp
>                                         boost::property_tree::ptree &pt) const
Copyright date needs to updated (line 2). In this case, a new line needs to be added:
`Copyright (c) 2022 Advanced Micro Devices, Inc.`

2022-03-21 20:35 UTC, gbuildx commented
Build Passed!

2022-03-21 23:20 UTC, rozumx approved these changes

2022-03-22 00:08 UTC, merged