CR-1123097 ASTeR basic sanity - vck5000 - VMR version not displayed in xbutil/xbmgmt examine
Xilinx/XRT pull request #6471
Opened 2022-03-22 21:46 UTC by AShivangi

#### Problem solved by the commit
Add vmr version support to reporting

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered

#### How problem was solved, alternative solutions (if any) and why they were rejected
A lot of these flags are for debugging so I decided to hide them under verbose. Unless `--verbose` is specified, only the vmr version will be displayed. 
Subject to change based on ux

#### Risks (if any) associated the changes in the commit
None

#### What has been tested and how, request additional testing if necessary
Locally
Non verbose:
```
# xbmgmt examine -d -r vmr

-------------------------------------------------------
1/1 [0000:09:00.0] : xilinx_vck5000_gen4x8_xdma_base_2
-------------------------------------------------------
Vmr Status
  Build flags          :  default full build
  Vitis version        :  2022.1
  Git hash             :  390ee9310e6fb948077d7497f6bb71b3ebe8516d
  Git branch           :  apu
  Git hash date        :  Mon, 21 Mar 2022 11
```
Verbose:
```
# xbmgmt examine -d -r vmr --verbose
Verbose: Enabling Verbosity
Verbose: SubCommand: examine

-------------------------------------------------------
1/1 [0000:09:00.0] : xilinx_vck5000_gen4x8_xdma_base_2
-------------------------------------------------------
Vmr Status
  Build flags          :  default full build
  Vitis version        :  2022.1
  Git hash             :  390ee9310e6fb948077d7497f6bb71b3ebe8516d
  Git branch           :  apu
  Git hash date        :  Mon, 21 Mar 2022 11
  Is ps ready          :  1
  Default image offset :  0x48000
  Default image size   :  0x6fec60
  Default image capacity :  0x5fb8000
  Backup image offset  :  0x6008000
  Backup image size    :  0x6fec60
  Backup image capacity :  0x5fb8000
  Sc firmware size     :  0x630f3
  Has fpt              : 1
  Has fpt recovery     : 1
  Boot on default      : 1
  Boot on backup       : 0
  Boot on recovery     : 0
  Multi boot offset    : 0x9
  Has extfpt           : 1
  Has ext meta xsabin  : 1
  Has ext sc fw        : 1
  Has ext system dtb   : 1
  Debug level          : 0
  Program progress     : 100
  Pl is ready          : 1
  Ps is ready          : 1
```

#### Documentation impact (if any)

2022-03-22 21:51 UTC, xdavidz approved these changes
Looks good to me.

2022-03-22 22:01 UTC, stsoe approved these changes

2022-03-23 00:36 UTC, gbuildx commented
Build Failed! :(

2022-03-23 17:51 UTC, gbuildx commented
Build Failed! :(

2022-03-23 21:19 UTC, gbuildx commented
Build Failed! :(

2022-03-23 21:38 UTC, dayeh-xilinx commented
retest this please.

2022-03-23 21:47 UTC, rozumx requested changes

2022-03-23 21:47 UTC, rozumx commented on src/runtime_src/core/common/info_vmr.cpp
> +  label[0] = static_cast<char>(toupper(label[0]));
What happens if the label is empty?

2022-03-23 21:47 UTC, rozumx commented on src/runtime_src/core/common/info_vmr.cpp
> +  label[0] = static_cast<char>(toupper(label[0]));
```suggestion
  if (!label.empty())
     label[0] = static_cast<char>(toupper(label[0]));
```

2022-03-23 21:47 UTC, rozumx commented on src/runtime_src/core/tools/common/ReportVmrStatus.cpp
> +  const std::vector<std::string> non_verbose_labels = { "build flags", "vitis version",
You might wish to reformat this list.  Maybe 1 item per line.

2022-03-24 01:50 UTC, gbuildx commented
Build Passed!

2022-03-24 04:28 UTC, gbuildx commented
Build Passed!

2022-03-24 17:10 UTC, rozumx approved these changes

2022-03-24 17:19 UTC, merged