New mailbox protocol implementation in XRT
Xilinx/XRT pull request #6486
Opened 2022-03-24 05:41 UTC by vboggara-xilinx

#### Problem solved by the commit
Implemented new mailbox protocol in XRT, Below is the change
`
**Mailbox Read:**

•	Mbox.read()
                 Check read acknowledgement is low or not, if low continue else throw error.
                 Release , setting mailbox output control register to 1
•	get_arg()
                 Waiting for read acknowledgement in while loop until this bit gets low 
                 Acquiring mailbox for read by setting mailbox output control register to 0
                 Reading arg value

**Mailbox write:**

•	Mbox.Write()
                Check write acknowledgement is low or not, if low continue else throw error.
                Release , setting mailbox input control register to 1
•	set_arg()
                Waiting for write acknowledgement in while loop until this bit gets low 
                Acquiring mailbox for write by setting mailbox input control register to 0
                Writing arg value
`
#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
https://jira.xilinx.com/browse/CR-1123104
#### How problem was solved, alternative solutions (if any) and why they were rejected
n/a
#### Risks (if any) associated the changes in the commit
n/a
#### What has been tested and how, request additional testing if necessary
Tested bugcases locally with the change, all are passing
#### Documentation impact (if any)
n/a

2022-03-24 05:57 UTC, chvamshi-xilinx requested changes
Thanks Naresh. Overall it Looks good. Some minor changes requested.

2022-03-24 05:57 UTC, chvamshi-xilinx commented on src/runtime_src/core/common/api/xrt_kernel.cpp
> +  mailbox_idle_or_error(mailbox_operation mbop)
const reference

2022-03-24 05:57 UTC, chvamshi-xilinx commented on src/runtime_src/core/common/api/xrt_kernel.cpp
> +    constexpr size_t counter_offset = mailbox_auto_restart_cntr;
We dont need this extra variable. Directly use mailbox_auto_restart_cntr in set_offset_value function

2022-03-24 05:57 UTC, chvamshi-xilinx commented on src/runtime_src/core/common/api/xrt_kernel.cpp
> +    constexpr size_t counter_offset = mailbox_auto_restart_cntr;
We dont need this extra variable. Directly use mailbox_auto_restart_cntr in set_offset_value function

2022-03-24 05:57 UTC, chvamshi-xilinx commented on src/runtime_src/core/common/api/xrt_kernel.cpp
> +  poll(mailbox_operation mbop)
const reference

2022-03-24 05:57 UTC, chvamshi-xilinx commented on src/runtime_src/core/common/api/xrt_kernel.cpp
> +           return;
This return is not required. 
Better to write 
if (m_busy_write) throw an error

2022-03-24 05:57 UTC, chvamshi-xilinx commented on src/runtime_src/core/common/api/xrt_kernel.cpp
> +          uint32_t ctrlreg_write = kernel->read_register(mailbox_input_ctrl_reg);
acquire if not acquired already. We can save one reg read/reg write with it.

2022-03-24 05:57 UTC, chvamshi-xilinx commented on src/runtime_src/core/common/api/xrt_kernel.cpp
> +          uint32_t ctrlreg_read = kernel->read_register(mailbox_output_ctrl_reg);
acquire if not acquired already. We can save one reg read/reg write with it.

2022-03-24 05:57 UTC, chvamshi-xilinx commented on src/runtime_src/core/common/api/xrt_kernel.cpp
> +constexpr uint32_t mailbox_input_ack = 2;
use 1<<1 which explains which bit representing ack bit.

2022-03-24 05:57 UTC, chvamshi-xilinx commented on src/runtime_src/core/common/api/xrt_kernel.cpp
> +constexpr size_t mailbox_auto_restart_cntr = 16; //0x10;
I know, we are facing some issue if we use 0x10 instead of 16. Lets add a comment . We can fix it in next PR.

2022-03-24 05:57 UTC, chvamshi-xilinx commented on src/runtime_src/core/common/api/xrt_kernel.cpp
> +constexpr size_t mailbox_output_ctrl_reg = 24; // 0x18;
some are size_t and some are uint32_t. Please use same.

2022-03-24 05:57 UTC, chvamshi-xilinx commented on src/runtime_src/core/common/api/xrt_kernel.cpp
> +       poll(mailbox_operation::write);
You can call poll on the top with mbop directly.

2022-03-24 08:17 UTC, chvamshi-xilinx requested changes

2022-03-24 08:17 UTC, chvamshi-xilinx commented on src/runtime_src/core/common/api/xrt_kernel.cpp
> +        if (!m_aquire_read) {
early exit

2022-03-24 08:17 UTC, chvamshi-xilinx commented on src/runtime_src/core/common/api/xrt_kernel.cpp
> +       if (!m_aquire_write) {
early exit

2022-03-24 08:17 UTC, chvamshi-xilinx commented on src/runtime_src/core/common/api/xrt_kernel.cpp
> +enum class mailbox_operation {
move this enum to inside mailbox_impl class

2022-03-24 09:12 UTC, gbuildx commented
Build Passed!

2022-03-24 09:57 UTC, chvamshi-xilinx approved these changes
Looks good now. Approved.
Please add some comments on acquire and release logic

2022-03-24 11:33 UTC, gbuildx commented
Build Failed! :(

2022-03-24 15:53 UTC, vboggara-xilinx commented
@stsoe , please review the changes and merge if everything looks good.

2022-03-24 16:31 UTC, chvamshi-xilinx commented
retest this please

2022-03-24 16:36 UTC, stsoe approved these changes
Thank you for making these changes.  LGTM.

2022-03-24 18:39 UTC, gbuildx commented
Build Failed! :(

2022-03-24 20:36 UTC, dayeh-xilinx commented
retest this please.

2022-03-24 23:38 UTC, gbuildx commented
Build Failed! :(

2022-03-25 02:09 UTC, dayeh-xilinx commented
retest this please.

2022-03-25 06:55 UTC, gbuildx commented
Build Passed!

2022-03-25 07:44 UTC, merged