shim: add flag to exit dev_offline status check loop forcibly
Xilinx/XRT pull request #6632
Opened 2022-04-25 12:08 UTC by rajkumar-xilinx

Signed-off-by: Rajkumar Rampelli <rajkumar@xilinx.com>

#### Problem solved by the commit
xbutil reset test hangs indefinitely on Microsoft Azure multi-cards test environment when multiple tests run simultaneously.
It is due to device is not coming online after reset.

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered

#### How problem was solved, alternative solutions (if any) and why they were rejected

#### Risks (if any) associated the changes in the commit

#### What has been tested and how, request additional testing if necessary

#### Documentation impact (if any)

2022-04-25 12:09 UTC, rajkumar-xilinx commented
I will add Stephen and Soren once the change approved by Vamshi & Arpit.

2022-04-25 12:32 UTC, gbuildx commented
Build Failed! :(

2022-04-25 14:57 UTC, stsoe requested changes
Please update the PR description and fill out all the items.

2022-04-25 14:57 UTC, stsoe commented on src/runtime_src/core/pcie/linux/shim.cpp
> +    std::chrono::time_point<std::chrono::system_clock> start, end;
```suggestion
```

2022-04-25 14:57 UTC, stsoe commented on src/runtime_src/core/common/config_reader.h
> +inline bool
```suggestion
inline unsigned int
```

2022-04-25 14:57 UTC, stsoe commented on src/runtime_src/core/pcie/linux/shim.cpp
> +    start = std::chrono::system_clock::now();
```suggestion
    auto start = std::chrono::system_clock::now();
```

2022-04-25 14:57 UTC, stsoe commented on src/runtime_src/core/pcie/linux/shim.cpp
>          std::this_thread::sleep_for(std::chrono::milliseconds(500));
Magic constant and no comments.  This logic, regardless of magic or not, must be commented; it is not obvious.

2022-04-25 14:57 UTC, stsoe commented on src/runtime_src/core/pcie/linux/shim.cpp
> +        end = std::chrono::system_clock::now();
```suggestion
        auto end = std::chrono::system_clock::now();
```

2022-04-25 14:57 UTC, stsoe commented on src/runtime_src/core/pcie/linux/shim.cpp
> +            xrt_logmsg(XRT_WARNING, "%s: device unable to come online, so exiting", __func__);
exiting what?   breaking the while loop, but otherwise just proceeding as normal.

2022-04-25 17:39 UTC, gbuildx commented
Build Passed!

2022-04-26 04:24 UTC, chvamshi-xilinx approved these changes

2022-04-26 21:07 UTC, arpitxilinx approved these changes
@rajkumar-xilinx I am assuming you or Durga have tested this changes and now xbutil at least exits. I think the underlying issue of why reset is failing still needs to be debugged.

2022-04-28 10:39 UTC, rajkumar-xilinx commented
> @rajkumar-xilinx I am assuming you or Durga have tested this changes and now xbutil at least exits. I think the underlying issue of why reset is failing still needs to be debugged.

Hi @arpitxilinx yes, we validated this change.

2022-04-28 10:56 UTC, gbuildx commented
Build Failed! :(

2022-04-28 12:26 UTC, gbuildx commented
Build Failed! :(

2022-04-28 14:38 UTC, gbuildx commented
Build Failed! :(

2022-04-28 16:08 UTC, rajkumar-xilinx commented
retest this please

2022-04-28 17:40 UTC, gbuildx commented
Build Passed!

2022-05-02 05:34 UTC, chvamshi-xilinx approved these changes

2022-05-02 07:15 UTC, rajkumar-xilinx commented
Hi @stsoe , could you please review this change ? thank you.

2022-05-02 14:54 UTC, stsoe requested changes

2022-05-02 14:54 UTC, stsoe commented on src/runtime_src/core/pcie/linux/shim.cpp
> +     */
C++ inline commenting style is `//`.  Please follow the convention as much as possible.

2022-05-02 14:54 UTC, stsoe commented on src/runtime_src/core/pcie/linux/shim.cpp
> +    ret = mDev->ioctl(mUserHandle, DRM_IOCTL_XOCL_HOT_RESET);
Why was declaration moved to 1101?  Declare and defined variables where they are first used.

2022-05-02 17:06 UTC, stsoe approved these changes

2022-05-02 18:24 UTC, gbuildx commented
Build Failed! :(

2022-05-02 21:46 UTC, dayeh-xilinx commented
retest this please.

2022-05-02 23:21 UTC, gbuildx commented
Build Passed!

2022-05-03 07:06 UTC, merged

2022-05-03 07:07 UTC, chvamshi-xilinx commented
@rajkumar-xilinx , Cherry pick this to 2022.1