Make XRT compile on Ubuntu 22.04
Xilinx/XRT pull request #6665
Opened 2022-05-05 00:29 UTC by Ralender

- Fix cmake for finding python libs
  findPythonLibs is deprecated since cmake 3.12
  replace it with findPython3 for newer versions
- silence OpenSSL 3 deprecation warnings
  MD5 used in container.cpp
  and SHA256 in azure.cpp

I didn't analyze if MD5 was used for security purposes. If it is the case it should be replaced by SHA2 or better.

2022-05-05 00:30 UTC, gbuildx commented
Can one of the admins verify this patch?

2022-05-05 00:31 UTC, stsoe approved these changes
Thank you for making these changes.

2022-05-05 00:31 UTC, stsoe commented
ok to test

2022-05-05 00:58 UTC, gbuildx commented
Build Failed! :(

2022-05-05 19:04 UTC, Ralender commented
I noticed that dbg.sh doesn't work on Ubuntu 22.04.

2022-05-05 20:27 UTC, gbuildx commented
Build Passed!

2022-05-06 06:17 UTC, keryell requested changes
That sounds good but you should take some rationale from your PR description into some comments in the code.

2022-05-06 06:17 UTC, keryell commented on src/runtime_src/tools/xclbinutil/CMakeLists.txt
> +  cmake_policy(SET CMP0110 NEW)
Explain the magic with some comments.

2022-05-06 06:17 UTC, keryell commented on src/python/pybind11/CMakeLists.txt
> +if (${CMAKE_VERSION} VERSION_LESS "3.12")
Explain the magic with some comments.

2022-05-06 18:18 UTC, gbuildx commented
Build Passed!

2022-05-06 18:31 UTC, merged

2022-05-06 19:07 UTC, keryell reviewed
Thanks

2022-05-06 19:07 UTC, keryell commented on src/python/pybind11/CMakeLists.txt
> +# find_package(PythonLibs is depracted as of cmake 3.12.
Using a spell-checker is even better :-)