New API xrt::hw_context
Xilinx/XRT pull request #6698
Opened 2022-05-13 22:21 UTC by stsoe

New concept to represent hardware resources (columns, regions, PS
processes) used by an xclbin.  A hardware context is used by an
application to control where execution takes place.  In a multi-xclbin
scenario, the hardware context is specific to one xclbin even if that
xclbin is loaded multiple times.

The feature is optional for legacy applications / platforms.

Constructed from a device and an xclbin uuid that has been registered
with the device (driver)

A context is 1-1 with a slot index. A resource resolver assigns a
hardware context to hardware resources, maybe sharing, or fails.
On success, the driver assigns a unique slot index to the context.

A kernel object is created from a hardware context. CU context
creation no longer needs EAGAIN as opening of CU context always
succeeds if the hardware context was successfully created. The rather
complicated code for EAGAIN per #6421 has been removed in this PR.

A hardware context can be shared between threads. A process
can construct multiple hardware contexts.

2022-05-13 23:55 UTC, gbuildx commented
Build Failed! :(

2022-05-14 03:16 UTC, keryell requested changes
Quite interesting feature!

2022-05-14 03:16 UTC, keryell commented on tests/xrt/multi_xclbin/simple.cpp
> +#include <thread>
Eek! Be modest in your inclusions. :-) Or is this from the `#include <C++>` diversity&inclusion group?

2022-05-14 03:16 UTC, keryell commented on tests/xrt/multi_xclbin/simple.cpp
> +static constexpr size_t elements = 16;
Do you really need all these `static` everywhere in a such single-file example? Same for the functions.
Nowadays the anonymous `namespace` might be more fashionable for this anyway.

2022-05-14 03:16 UTC, keryell commented on tests/xrt/multi_xclbin/simple.cpp
> +static constexpr size_t maxcus = 8;
```suggestion
constexpr size_t max_cus = 8;
```

2022-05-14 03:18 UTC, keryell commented
@Ralender context! How does this impact the future of https://github.com/triSYCL/sycl/pull/170 ?

2022-05-15 20:13 UTC, gbuildx commented
Build Failed! :(

2022-05-15 22:30 UTC, gbuildx commented
Build Passed!

2022-05-16 04:12 UTC, stsoe commented
@saifuddin-xilinx @chvamshi-xilinx   I added you both as reviewer, most FYI.  I don't think the changes in this PR affects vck5000 or builtin xclbin right now.   We will meet some time this week to summarize the new APIs.  The slides (spec) are a bit like work-in-progress, but you should get the the idea by checking the slide about the new xcl APIs that are being added.

2022-05-16 11:41 UTC, saifuddin-xilinx approved these changes

2022-05-16 14:44 UTC, merged