Code fix
Xilinx/XRT pull request #6740
Opened 2022-05-31 15:33 UTC by sgundime-xilinx

Fix : Currently application hangs once simulator exits. Ideally the application should exits if no simulator is running. The application does polling on connected socket periodically and exits when it lost the connection (pollin failure).

Risk : very Low.

Tests : Canary tun. Results are clean.

Reviewer : sgundime

2022-05-31 15:48 UTC, stsoe requested changes
Cannot review the logic in detail since emulation code is far too convoluted and not very well documented.

Some code style suggestions.

2022-05-31 15:48 UTC, stsoe commented on src/runtime_src/core/pcie/emulation/common_em/unix_socket.cxx
> +  if (not server_started || (false == simprocess_socket_live) ) {
A mix of everything, why not just `!`.  

Inconsistent use of store() and load().  I thought you mentioned (and I agreed) that maybe store and load make it explicit that we are dealing with atomicity, but the use is inconsistent.  Personally, I can live without store() and load().

2022-05-31 15:48 UTC, stsoe commented on src/runtime_src/core/pcie/emulation/common_em/utility.cxx
> +}
missing new line

2022-05-31 15:48 UTC, stsoe commented on src/runtime_src/core/pcie/emulation/common_em/utility.cxx
> +        }
fopen is not C+ and what if in-between code throws an exception.
NULL is not C++.
What if strtok is nullptr?

2022-05-31 15:48 UTC, stsoe commented on src/runtime_src/core/pcie/emulation/common_em/utility.h
> +#define _UTILITY_H_
Not sufficient.  Are you sure this is this only utility file?

2022-05-31 15:48 UTC, stsoe commented on src/runtime_src/core/pcie/emulation/common_em/utility.h
> +#include <vector>
Sort and don't include `.h`.  `cstring` and `cstdint`

2022-05-31 15:48 UTC, stsoe commented on src/runtime_src/core/pcie/emulation/common_em/utility.h
> +#endif
Why a class?  These should be namespaced functions

2022-05-31 16:55 UTC, gbuildx commented
Build Failed! :(

2022-06-07 16:27 UTC, sgundime-xilinx commented
https://github.com/sgundime-xilinx/XRT/tree/socket-issue branch will address hang issue for external IO examples.

2022-06-07 16:27 UTC, closed without merging