CR-1127959 TC18.01 - u55c - validate dma test reporting high bandwidth figure with 256MB block size
Xilinx/XRT pull request #6752
Opened 2022-06-07 21:24 UTC by chienwei-lan

#### Problem solved by the commit
Miscalculate the DMA workers number  to be performed, only submits half of the BOs.

So the throughput is twice as fast as theoretical limit.

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
https://github.com/Xilinx/XRT/pull/6184
'

2022-06-07 23:21 UTC, gbuildx commented
Build Passed!

2022-06-09 03:01 UTC, maxzhen approved these changes

2022-06-09 20:52 UTC, stsoe requested changes
Just one quick change.

2022-06-09 20:52 UTC, stsoe commented on src/runtime_src/core/pcie/common/dmatest.h
> +            unsigned int bo_cnt = ((unsigned int)(e - b));
```suggestion
            auto bo_cnt = static_cast<unsigned int>(e - b);
```

2022-06-09 21:50 UTC, stsoe approved these changes

2022-06-09 22:32 UTC, gbuildx commented
Build Passed!

2022-06-09 22:58 UTC, merged