CR-1125485 keep reference count in driver to allow multiple context
Xilinx/XRT pull request #6756
Opened 2022-06-08 23:01 UTC by Zenfendson

#### Problem solved by the commit 
CR-1125485 keep reference count in driver to allow multiple context

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
This is not a bug 

#### How problem was solved, alternative solutions (if any) and why they were rejected
Add per client cu and scu refcnt

#### Risks (if any) associated the changes in the commit
Low

#### What has been tested and how, request additional testing if necessary
Run testcase in CR-1125485 on U50

#### Documentation impact (if any)
No

2022-06-08 23:02 UTC, gbuildx commented
Can one of the admins verify this patch?

2022-06-08 23:17 UTC, stsoe commented
add to whitelist

2022-06-08 23:17 UTC, stsoe commented
ok to test

2022-06-08 23:43 UTC, mamin506 approved these changes
LGTM

2022-06-08 23:46 UTC, mamin506 commented
@Zenfendson Can you compare the result of "xbutil validate -d <bdf> -u iops" w/ and w/o your change?

2022-06-09 00:46 UTC, gbuildx commented
Build Passed!

2022-06-09 02:59 UTC, maxzhen requested changes

2022-06-09 02:59 UTC, maxzhen commented on src/runtime_src/core/common/drv/kds_core.c
> +		refs = client->refcnt->scu_refs;
The code here seems to assume that there can only be two type of domains. I'd think that it'll be better to explicitly check against domains you can handle here and return / print errors, if you see unexpected domains. Next time when we extend domain types, we'll not silently corrupt scu array.

2022-06-09 02:59 UTC, maxzhen commented on src/runtime_src/core/common/drv/kds_core.c
> +	if (domain == DOMAIN_PL || domain == DOMAIN_VIRT)
do we have a specific domain for virtual cu? if we do, we map cu_refs to it. But in line 271, we map scu_refs to it? Maybe we should have a function to map cu_/scu_refs to domain and be consistent with our design?

2022-06-09 02:59 UTC, maxzhen commented on src/runtime_src/core/common/drv/kds_core.c
> +		return -ENOMEM;
leaking client->stats?

2022-06-09 18:46 UTC, Zenfendson commented
@mamin506 after running 10 times of the command, the median iops with my driver is 538170 and the median iops without my driver is 541908, which have no significantly impact on iops.

2022-06-09 22:20 UTC, gbuildx commented
Build Passed!

2022-06-13 18:38 UTC, gbuildx commented
Build Failed! :(

2022-06-13 19:03 UTC, salindac commented
retest this please

2022-06-13 22:18 UTC, gbuildx commented
Build Passed!

2022-06-14 00:27 UTC, gbuildx commented
Build Passed!

2022-06-14 00:54 UTC, maxzhen approved these changes

2022-06-14 16:18 UTC, jeffli-xilinx approved these changes

2022-06-14 20:19 UTC, rozumx approved these changes

2022-06-14 21:52 UTC, Zenfendson commented
> Looks good. I can't tell if maybe already covered. But it would be helpful to a logged message when the reference count is unexpected different from 0 at process exit.

Well, when the process exits, the reference count per client will be eliminated and set to 0. The memory will then be released so I think such exception will not happen.

2022-06-14 22:41 UTC, stsoe commented
> > Looks good. I can't tell if maybe already covered. But it would be helpful to a logged message when the reference count is unexpected different from 0 at process exit.
> 
> Well, when the process exits, the reference count per client will be eliminated and set to 0. The memory will then be released so I think such exception will not happen.

My point was that if you find yourself having to reset to 0, then something is wrong in user land.  Of course in abnormal termination you need to do this reset, but in the normal case, user space should always release a CU context it has acquire.  That's why a warning to this effect could be useful.

2022-06-14 23:15 UTC, gbuildx commented
Build Passed!

2022-06-15 17:28 UTC, mamin506 commented
> 

Hi @stsoe , if user space doesn't release a CU context it has acquired. There is a warning in dmesg, for example:
  " Client pid(1001) has 2 opening context for 0 slot"
  
Is this what you want? Or do you suggest to print more details, like
" Client pid(1001) has 2 opening context for 0 slot
      CU(0) refcnt is 2
      CU(1) refcnt is 1
"

2022-06-15 21:02 UTC, merged