CR-1120194: Addressed hang issue for external IO example, specific thread polls the client file descriptor periodically
Xilinx/XRT pull request #6769
Opened 2022-06-15 10:44 UTC by sgundime-xilinx

Fix : Currently XRT is hanging once simulator is connected and exits after time. So XRT should be notified if socket is no more active. But XRT cannot except a graceful exit from simulator so a polling mechanism is introduced to track the state change of client socket periodically.

Risk: very Low.
Tests: Canary run. Results are clean.
Reviewer: venkatp

2022-06-15 12:12 UTC, gbuildx commented
Build Passed!

2022-06-15 16:38 UTC, venkatp-xilinx approved these changes

2022-06-15 18:26 UTC, lforg37 commented
Wouldn't this PR be the occasion of get rid of the `AQUIRE_MUTEX` and `RELEASE_MUTEX` macro ?
The second one is no more used here, so instead of having an empty body it can be removed everywhere, and maybe it would be time to replace the first one with a more stable construct ?

Because there is a danger that if for some reason the AQUIRE_MUTEX was called in a subscope, the section protected by the mutex changed.

Dummy example code:

```
{
// ...
  {
    // Do some sub-scope local things
    AQUIRE_MUTEX()
    // Other sub-scope local things that needs to be mutex protected
  }
  // Other things that needs to be mutex protected
  RELEASE_MUTEX()
}
```

The other things that needs to be mutex protected will not be anymore with this change.

I am not aying that such code exists in the code base, but keeping the macro name to acquire and release does not communicate the fact that a context manager is created, so could be misleading.

2022-06-15 20:10 UTC, kbhardwa-xilinx commented
retest this please

2022-06-15 20:15 UTC, dayeh-xilinx commented
kbhardwa-xilinx is re-testing this to verify some infra change.

2022-06-15 21:49 UTC, gbuildx commented
Build Failed! :(

2022-06-15 23:00 UTC, kbhardwa-xilinx commented
retest this please

2022-06-16 00:29 UTC, gbuildx commented
Build Passed!

2022-06-20 16:38 UTC, sgundime-xilinx commented on src/runtime_src/core/include/xcl_api_macros.h
> +    if(rv == false){std::cerr<<"FATAL ERROR:protobuf SerializeToArray failed"<<std::endl; exit(1);} \
The errors were different. So updated with appropriate failures and no new function is introduced to captrure the generic failure in macro.

2022-06-20 16:40 UTC, sgundime-xilinx commented on src/runtime_src/core/pcie/emulation/common_em/unix_socket.cxx
> +      std::this_thread::sleep_for(5s);                          // provide some time so that spawned threads will terminate themselves messagesThread.
The sleep statement is not mandatory to present and it is not a synchronize methodology followed. So removing it. thread.join() would take care of it as you mentioned.

2022-06-20 16:48 UTC, sgundime-xilinx commented on src/runtime_src/core/pcie/emulation/common_em/unix_socket.cxx
> +    auto retval = poll(&mpoll_on_filedescriptor, 1, 500);       // Let's do polling on it for utmost 500 ms
The monitoring functionality requires to be run in parallel and any state change should be notified. So a thread is a good to opt for or std::launch::async would justify the requirement.

1. this poll can be merged with the select in sk_write and sk_read
answer: Agree partially. But what if there is no simulator running and no RPC calls made? The current thread notifies XRT about socket state change and exit the application when next RPC call is made.

2022-06-20 16:48 UTC, sgundime-xilinx commented on src/runtime_src/core/pcie/emulation/hw_em/generic_pcie_hal2/shim.cxx
> +    if (sock->m_is_socket_live != false) {
Agreed. updated code accordingly.

2022-06-20 18:15 UTC, gbuildx commented
Build Passed!

2022-06-21 17:18 UTC, sgundime-xilinx commented
@Ralender : Can the code be reviewed now please?

2022-06-22 13:11 UTC, chvamshi-xilinx approved these changes

2022-06-22 22:53 UTC, lforg37 requested changes
Please see the review comments.

2022-06-24 10:49 UTC, merged

2022-06-24 12:48 UTC, lforg37 commented
While I can understand that we postpone the remarks related to refactoring, the part of the code related to "non blocking" IO with actively restarting the wait without timings is clearly suspicious, and will probably introduce waste of cpu time.

I don't think merging a PR that adds technical debt, do quite complex modification without a high level comment  explaining that and even keep old code into comment is something we should do. 

Especially in this part of the system which, as has been mentionned by someone else, is already complex enough to be responsible of a good part of the bugs we identified in the emulator.

2022-06-24 18:50 UTC, keryell commented
@sonals @stsoe at the end I do not think it is useful to add more buggy code like this PR to XRT.
Perhaps it seems even better to not merge these kinds of random PR and just live with the current situation which does not seem to impact the AMD financial results anyway.
I suggest AMD AECG Research Labs stopping wasting time on reviewing XRT.

2022-06-24 19:16 UTC, stsoe commented
@keryell I agree with you and @lforg37 that this PR should not have been merged if it has known bugs / deficiencies / debt.  Your reviews are much appreciated so please keep doing this.   The emulation code is in a very poor state and apparently difficult to fix without a complete rewrite.

2022-06-27 06:38 UTC, chvamshi-xilinx commented
Hi @keryell / @lforg37 , I really didn't mean to ignore your suggestions. I have merged it as PR filer created a CR to address your comments and asked us to merge this change.
As Soren mentioned, your review and feedback is very useful . Please keep doing this.
if things are blocked due to any PR, We merge the change and suggests PR filer to create CR to track the comments.

2022-06-27 08:39 UTC, keryell reviewed
It is unclear this solves anything.
Perhaps the race condition did not append with the new code by chance?

2022-06-27 08:39 UTC, keryell commented on src/runtime_src/core/include/xcl_api_macros.h
> +if ( sock->server_started == false ) { std::cerr<<"\n socket communication is not possible now!"; exit(0);  }\
Why `exit(0)` here ?
Is this to celebrate some happiness with such a success?