Add sc_pid to SCU subdevice sysfs to support PS kernel stat gathering
Xilinx/XRT pull request #6838
Opened 2022-07-11 23:47 UTC by jeffli-xilinx

#### Problem solved by the commit
Allows query of PS kernel pid

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
None

#### How problem was solved, alternative solutions (if any) and why they were rejected
Expose pid through sysfs node on SCU platform subdevice

#### Risks (if any) associated the changes in the commit
None

#### What has been tested and how, request additional testing if necessary
PS kernel validate tests

#### Documentation impact (if any)

2022-07-12 01:32 UTC, gbuildx commented
Build Passed!

2022-07-12 03:21 UTC, rozumx reviewed
Jeff,
Could you update the PR description with an example directory structure.

2022-07-16 03:49 UTC, dbenusov-xilinx requested changes

2022-07-16 03:49 UTC, dbenusov-xilinx commented on src/runtime_src/core/edge/drm/zocl/scu.c
> +	char *fmt = "%u\n";
```suggestion
	char *fmt = "PID:%u\n";
```
To match all the other files would it be a good idea to have the format like this? Even if it is one element.

2022-07-16 03:49 UTC, dbenusov-xilinx commented on src/runtime_src/core/edge/drm/zocl/scu.c
> +static DEVICE_ATTR_RO(sc_pid);
```suggestion
static DEVICE_ATTR_RO(status);
```
If there is every additional data would we want to create a different node? We could place it all into one attribute file to reduce the amount of files to access. Renaming the attribute to `status` mimics the behavior of the `/proc/` entries. The PID of the process in `/proc/` is also stored in the `status` attribute so the logic matches up. Any additional information we would ever need to add could be easily parsed into the PS kernel I am developing by adding another row of data.

2022-07-18 08:54 UTC, chvamshi-xilinx approved these changes

2022-07-19 09:27 UTC, gbuildx commented
Build Passed!

2022-07-19 23:18 UTC, dbenusov-xilinx approved these changes
Thank you!

2022-07-27 20:51 UTC, merged