Update PS kernel return code location to end of arguments
Xilinx/XRT pull request #6839
Opened 2022-07-12 00:08 UTC by jeffli-xilinx

#### Problem solved by the commit
Move PS kernel return code after arguments in the command buffer

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
Prevents overwrite of PS kernel command buffer

#### How problem was solved, alternative solutions (if any) and why they were rejected
Calculate offset for return code at end of argument list

#### Risks (if any) associated the changes in the commit

#### What has been tested and how, request additional testing if necessary
PS kernel validate tests

#### Documentation impact (if any)

2022-07-12 03:11 UTC, gbuildx commented
Build Passed!

2022-07-12 16:45 UTC, mamin506 approved these changes
The change in cu_scu.c looks good to me. Didn't review the skd code.

2022-07-15 21:08 UTC, rozumx requested changes
Some obfuscated code needs to be refactored along with adding some comments to the code.

2022-07-15 21:08 UTC, rozumx commented on src/runtime_src/core/edge/skd/xrt_skd.cpp
> +      return_offset = (args[num_args-1].offset+PS_KERNEL_REG_OFFSET+16)/4;
Magic numbers.   
Lots happening in this line. A comment for future developers would be helpful.

2022-07-15 21:08 UTC, rozumx commented on src/runtime_src/core/edge/skd/xrt_skd.cpp
> +      return_offset = (args[num_args-1].offset+PS_KERNEL_REG_OFFSET+((args[num_args-1].size>4)?8:4))/4;
Magic numbers.
Lots happening in this line. A comment for future developers would be helpful.

2022-07-19 08:05 UTC, gbuildx commented
Build Passed!

2022-08-03 14:56 UTC, rozumx approved these changes
Overall this looks good.  That said, there are a few opportunity to add some more comments :^).

2022-08-03 14:56 UTC, rozumx commented on src/runtime_src/core/edge/drm/zocl/cu_scu.c
> +	scu->num_reg = (cmd->hdr.count - (sizeof(struct xgq_cmd_start_cuidx)
There is a lot going on on this line.  A comment would be helpful for future developers.

2022-08-03 14:56 UTC, rozumx commented on src/runtime_src/core/edge/drm/zocl/cu_scu.c
> +	scu->num_reg = (cmd->hdr.count - (sizeof(struct xgq_cmd_start_cuidx)
How are you guaranteeing that cmd->hdr.count will always be larger then the size of the structure.   If this should occur, then band things are going to happen.

2022-08-09 11:51 UTC, chvamshi-xilinx commented
Hi @jeffli-xilinx  , Can you please resolve the conflicts.

2022-08-09 11:52 UTC, chvamshi-xilinx approved these changes

2022-08-15 21:00 UTC, gbuildx commented
Build Failed! :(

2022-08-20 00:09 UTC, salindac commented
retest this please

2022-08-20 02:19 UTC, gbuildx commented
Build Passed!

2022-08-26 20:16 UTC, merged