CR-1131075 Support CU interrupt to APU
Xilinx/XRT pull request #6862
Opened 2022-07-19 18:51 UTC by mamin506

#### Problem solved by the commit
Support CU completion interrupt on APU

#### Risks (if any) associated the changes in the commit
No

#### What has been tested and how, request additional testing if necessary
vck5000 xbutil validate test, zcu104

#### Documentation impact (if any)
No

============================================
vck5000 xbutil validate iops result
```
$xbutil validate -d 04:00 -r iops
Starting validation for 1 devices

Validate Device           : [0000:04:00.1]
    Platform              : xilinx_vck5000_gen4x8_qdma_base_1
    SC Version            : 4.4.33
    Platform ID           : 2A6AB1C4-DFA1-27FD-7F24-E8F121039A2E
-------------------------------------------------------------------------------
Test 1 [0000:04:00.1]     : iops
    Details               : IOPS: 483580 (verify)
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Validation completed. Please run the command '--verbose' option for more details
```

2022-07-19 18:53 UTC, mamin506 commented
@stsoe , This is almost pure driver change. Maybe it is because `include/xgq_cmd_ert.h` is changed, so you are one of the reviewer.

2022-07-19 23:20 UTC, gbuildx commented
Build Failed! :(

2022-07-20 01:41 UTC, dayeh-xilinx commented
retest this please. Known singletask.lock issue.

2022-07-20 10:58 UTC, gbuildx commented
Build Passed!

2022-07-20 20:07 UTC, maxzhen requested changes
Please add AMD copyright to the changed file.

2022-07-20 20:07 UTC, maxzhen commented on src/runtime_src/core/edge/drm/zocl/zocl_ctrl_ert.c
> +	return 0;
missing kfree(irqs)?

2022-07-21 00:04 UTC, maxzhen approved these changes

2022-07-21 03:50 UTC, gbuildx commented
Build Failed! :(

2022-07-21 05:40 UTC, dayeh-xilinx commented
retest this please. one of EDGE_HW tests time out.

2022-07-21 06:38 UTC, gbuildx commented
Build Passed!

2022-07-21 16:14 UTC, chvamshi-xilinx approved these changes

2022-07-21 16:14 UTC, merged