Added AIE Trace PS Kernels for trace on the VCK5000
Xilinx/XRT pull request #6892
Opened 2022-08-04 22:17 UTC by nishraptor

Added 2 PS kernels to support event trace on the VCK5000. The aie_trace_config kernel configures the runtime trace performance counters and trace stream, and the aie_trace_gmio kernel configures the GMIO offload of the trace stream.

2022-08-05 00:15 UTC, gbuildx commented
Build Passed!

2022-08-05 02:27 UTC, gbuildx commented
Build Passed!

2022-08-05 22:27 UTC, gbuildx commented
Build Failed! :(

2022-08-06 01:50 UTC, gbuildx commented
Build Passed!

2022-08-09 22:01 UTC, rozumx requested changes
Some minor changes requested.

Side Note
Thank you for taking the time to do a self-code review prior to submitting the pull-request.   It shows and helps the code reviewers focus on what matters.

2022-08-09 22:01 UTC, rozumx commented on src/runtime_src/xdp/profile/plugin/aie_trace_new/x86/aie_trace_kernel_config.h
> +      uint32_t start_event = 28;
Comment on what the magic number represents would be nice.

2022-08-09 22:01 UTC, rozumx commented on src/runtime_src/xdp/profile/plugin/aie_trace_new/x86/aie_trace_kernel_config.h
> +      uint32_t numTileCoreTraceEvents[9] = {0};
```suggestion
      uint32_t numTileCoreTraceEvents[9] = {};
```

2022-08-09 22:01 UTC, rozumx commented on src/runtime_src/xdp/profile/plugin/aie_trace_new/x86/aie_trace_kernel_config.h
> +      uint32_t numTileMemoryTraceEvents[9] = {0};
```suggestion
      uint32_t numTileMemoryTraceEvents[9] = {};
```

2022-08-10 17:25 UTC, nishraptor commented on src/runtime_src/core/edge/ps_kernels/profiling/aie_trace_config/aie_trace_config.cpp
> +      // TODO: Send detailed message back to host code
All the TODO's are work that we are going to implement in the next PR, where we send the string data back to the host. , we are just marking it currently as we want to preserve the messages that we had on the edge (VCK190) implementation.

2022-08-11 00:06 UTC, gbuildx commented
Build Passed!

2022-08-11 16:02 UTC, nishraptor commented on src/runtime_src/core/edge/ps_kernels/profiling/aie_trace_config/aie_trace_config.cpp
> +        // TODO: Send success message back to host
When we implement it, we will have all the messaging within a function, but don't know the functionality of the mechanism we are going to use. The next PR will pull it into a function and clean all of them up.

2022-08-11 18:13 UTC, jvillarre approved these changes

2022-08-15 16:43 UTC, rozumx approved these changes

2022-08-15 17:17 UTC, merged