Update skd.service to automatically restart on failure
Xilinx/XRT pull request #7009
Opened 2022-09-08 21:36 UTC by jeffli-xilinx

#### Problem solved by the commit
skd not running after petalinux boot in some cases.

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
Noticed sometimes skd do not start after petalinux boot

#### How problem was solved, alternative solutions (if any) and why they were rejected
Updated skd.service to restart skd on exit

#### Risks (if any) associated the changes in the commit
None

#### What has been tested and how, request additional testing if necessary
vck5000 / v70

#### Documentation impact (if any)
None

2022-09-09 06:21 UTC, gbuildx commented
Build Passed!

2022-09-17 18:57 UTC, rozumx requested changes
With regards to the Daemon starting up with the APU makes sense and this should always occur.

As for restarting the SDK if it should crash / fail, I understand why you would like to do this, but I don't think this is a good idea.  Let me explain further.

The SDK code base needs to perform without ANY issues.  If there is an issue, we need to know about it and address it.   This change in behavior will "mask" SDK issues as users PS Kernel issues. 
 This will resulting in days of lost productive and possible SDK issues not being reported.

At our next opportunity lets to discuss why we should enable this service.

2022-09-22 22:21 UTC, gbuildx commented
Build Passed!

2022-09-22 22:54 UTC, gbuildx commented
Build Passed!

2022-09-23 05:07 UTC, rozumx approved these changes
Thank you not automatically restarting the daemon.

2022-09-26 16:50 UTC, dayeh-xilinx commented
retest this please.

2022-09-26 19:20 UTC, gbuildx commented
Build Passed!

2022-09-26 22:25 UTC, merged