xclbinutil - development add fingerprint support in aie_partition
Xilinx/XRT pull request #7073
Opened 2022-09-26 23:46 UTC by xfreid

#### Problem solved by the commit
Add fingerprint support in AIE_PARTITION

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
N/A

#### How problem was solved, alternative solutions (if any) and why they were rejected
N/A

#### Risks (if any) associated the changes in the commit
None

#### What has been tested and how, request additional testing if necessary
Manual and unit test

#### Documentation impact (if any)
None

2022-09-26 23:48 UTC, gbuildx commented
Can one of the admins verify this patch?

2022-09-26 23:48 UTC, larry9523 commented
ok to test

2022-09-26 23:57 UTC, rozumx requested changes

2022-09-26 23:57 UTC, rozumx commented on src/runtime_src/core/include/xclbin.h
> +    XCLBIN_STATIC_ASSERT(sizeof(struct aie_partition) == 184, "aie_partition structure no longer is 168 bytes in size");
The error string doesn't represent the number of bytes being checked.
```suggestion
    XCLBIN_STATIC_ASSERT(sizeof(struct aie_partition) == 184, "aie_partition structure no longer is 184 bytes in size");
```

2022-09-26 23:57 UTC, rozumx commented on src/runtime_src/core/include/xclbin.h
> +        uint64_t inference_fingerprint;
Could you add a one line comment description describing what this variable represents.
```suggestion
        uint64_t inference_fingerprint;  // The unique hash value of the inference function
```

2022-09-26 23:57 UTC, rozumx commented on src/runtime_src/core/include/xclbin.h
> +        uint64_t pre_post_fingerprint;
Could you add a comment here as well.

2022-09-27 01:04 UTC, gbuildx commented
Build Failed! :(

2022-09-27 02:24 UTC, xfreid commented on src/runtime_src/core/include/xclbin.h
> +        uint64_t pre_post_fingerprint;
add comment for pre_post_fingerprint

2022-09-27 08:23 UTC, gbuildx commented
Build Passed!

2022-09-27 17:25 UTC, rozumx approved these changes

2022-09-27 17:25 UTC, merged