CR-1142217 xball xbutil validate throws error KeyError: 'XILINX_XRT'
Xilinx/XRT pull request #7090
Opened 2022-10-05 21:17 UTC by rchane

#### Problem solved by the commit
https://jira.xilinx.com/browse/CR-1142217 Using sudo xball (not just validate) was throwing an error when looking for XILINX_XRT variable.
#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
This is a specific use case where xrt is installed in a /bin dir that can be found by sudo, where all tools except for xball work with sudo (otherwise, we expect to see `sudo: xball: command not found`). The issue arose [here](https://github.com/Xilinx/XRT/commit/ff35e8a78cba106779e842cda213b3c38ed1e64f) when XILINX_XRT was used instead of XRT_BIN_DIR.
#### How problem was solved, alternative solutions (if any) and why they were rejected
XRT_BIN_DIR is used again as an argument.
#### Risks (if any) associated the changes in the commit
N/A
#### What has been tested and how, request additional testing if necessary
Testing was done on a vck5000.
```
rchane@xsjsagarw50:/proj/rdi/staff/rchane/XRT$ export PATH=$PATH:$RCHOME/build/Debug/opt/xilinx/xrt/bin
rchane@xsjsagarw50:/proj/rdi/staff/rchane/XRT$ echo $PATH
/proj/xsjhdstaff4/rchane/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/bin/remote-cli:/home/rchane/bin:/usr/local/bin:/mis/TREE/bin:/usr/bin:/bin:/usr/ucb:/proj/rdi/staff/rchane/XRT/build/Debug/opt/xilinx/xrt/bin
rchane@xsjsagarw50:/proj/rdi/staff/rchane/XRT$ sudo env "PATH=$PATH" xball xbutil examine
[sudo] password for rchane: 
Discovering installed devices....

=====================================================================
1 / 3 [0000:65:00.1] : xilinx_vck5000_gen4x8_qdma_base_2
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Command: /proj/rdi/staff/rchane/XRT/build/Debug/opt/xilinx/xrt/bin/xbutil --device 0000:65:00.1 examine

WARNING: Unexpected xocl version (2.14.340) was found. Expected 2.15.0, to match XRT tools.

---------------------------------------------------
[0000:65:00.1] : xilinx_vck5000_gen4x8_qdma_base_2
---------------------------------------------------
Platform
  XSA Name               : xilinx_vck5000_gen4x8_qdma_base_2 
  Platform UUID          : 8A0D97AA-4F00-6E56-3818-1EF41366138A 
  FPGA Name              :  
```
(more examine info...)
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Summary:
   Installed device(s) : 3
          Shell Filter : '.'
      Number Evaluated : 3
                Passed : 3
                Failed : 0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
#### Documentation impact (if any)
N/A

2022-10-05 23:45 UTC, gbuildx commented
Build Passed!

2022-10-06 05:18 UTC, chvamshi-xilinx approved these changes
Looks good.

2022-10-06 16:27 UTC, rozumx requested changes
Obsolete Comment
> @rchane,
> The description indicates that the xbutil is being used for sudo (instead of xbmgmt).  In addition, the XILINX_BIN_DIR value is being used to solve this issue (which it shouldn't).
> 
> If the underlying issue has to do with not having a validate XILINX_XRT environment variable when using sudo, then why not update the script to have the user specify the -E option.

2022-10-06 16:27 UTC, rozumx commented on src/runtime_src/core/tools/common/xball
> +python3 $0 "${temp_python_status}" "${temp_json_file}" "${device_filter}" "${xrt_app}" "$prog_args" "${XRT_BIN_DIR}"
How is the XRT_BIN_DIR set.  I ask for it isn't being set by setup.sh.

In fact, this is something that is performed by the loader, where xball doesn't (and shouldn't) have one.

2022-10-06 16:27 UTC, rozumx commented on src/runtime_src/core/tools/common/xball
> +  cmd = xrt_bin_dir + "/" + xrt_app + " --device " + device["bdf"] + " " + prog_args
This seems to be a lot of work and rather kludgy for it no longer depends on the XILINX_XRT environment.

Why can't the user use the following command:
`$ sudo -E xball xbmgmt examine`

Note
I can see this script being updated to detect if XILINX_XRT is valid and if not requesting the user to either set it or use the -E option.

2022-10-06 16:32 UTC, rchane commented on src/runtime_src/core/tools/common/xball
> +python3 $0 "${temp_python_status}" "${temp_json_file}" "${device_filter}" "${xrt_app}" "$prog_args" "${XRT_BIN_DIR}"
Thank you for your insight, @rozumx! I used `env "PATH=$PATH` to simulate the user's environment, where they could use sudo with xball (I was getting `sudo: xball: command not found` without it). The user was using sudo with xbutil in previous releases, should we advise them not to and close this PR?

2022-10-06 16:48 UTC, rozumx approved these changes
Approved.
My questions were answered and I am good with these changes.

2022-10-06 16:49 UTC, merged