Enable cgroup v2 in petalinux
Xilinx/XRT pull request #7096
Opened 2022-10-06 21:38 UTC by jeffli-xilinx

Added cgroup CPUShare and MemoryLimit to skd.service

Signed-off-by: Jeff Lin <jeffylin@xilinx.com>

#### Problem solved by the commit
Enabled cgroup v2 and added CPUShare of 1024 and MemoryLimit of 1GB for skd

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
None.  This is enhancement for skd.

#### How problem was solved, alternative solutions (if any) and why they were rejected

#### Risks (if any) associated the changes in the commit
None

#### What has been tested and how, request additional testing if necessary
Test skd on vck5000 and v70

#### Documentation impact (if any)
None

2022-10-07 01:23 UTC, gbuildx commented
Build Passed!

2022-10-09 01:29 UTC, rozumx requested changes
Could you help me understand what we needed to enable cgroups?

I ask that being that this is being enabled for the first time, I wonder if the other daemons / processes have CPUShared set for this value is relative to each other.  What is the impact on the VDU drivers?

Also, how did you determine the memory limit of the soft kernel daemon (SKD)?  Being that this SKD creates and starts the PS kernels, does the sum of all of the  PS kernel memory need to be lower then the MemoryLimit value?

Note
Can these values be obtain an OS call (instead of examining the service file)?  If so, then you should work with @dbenusov-xilinx  to update the PS Kernel report to recode this information (along with how much memory is currently being consumed).

2022-10-11 01:47 UTC, gbuildx commented
Build Passed!

2022-10-11 16:31 UTC, rozumx approved these changes

2022-10-11 19:19 UTC, chvamshi-xilinx approved these changes

2022-10-12 07:04 UTC, merged