Set log level for skd syslog to not print debug messages
Xilinx/XRT pull request #7097
Opened 2022-10-07 09:25 UTC by rbramand-xilinx

Signed-off-by: rbramand <rbramand@xilinx.com>

#### Problem solved by the commit
syslog for skd prints all kind of messages, setting log level to disable debug prints.
minor fix - multiple instances of allegro decoder ip are present, so changing permissions on all nodes 

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
Log message "Got new kernel command" in skd::run is printed multiple times so changed its log level to debug and made changes to not print debug messages

#### How problem was solved, alternative solutions (if any) and why they were rejected

#### Risks (if any) associated the changes in the commit
Low

#### What has been tested and how, request additional testing if necessary
Maruti tested apu package created on V70 and it is working as expected

#### Documentation impact (if any)
NA

2022-10-07 09:52 UTC, chvamshi-xilinx approved these changes

2022-10-07 11:54 UTC, gbuildx commented
Build Passed!

2022-10-07 21:08 UTC, jeffli-xilinx requested changes
I have a PR that changes skd from syslog to xrt messages in another PR that is about to be merged.
https://github.com/Xilinx/XRT/pull/7032

Please remove the syslog change from this PR.
Thanks!

2022-10-11 06:49 UTC, rbramand-xilinx commented
Closing this PR as code is revamped to use xrt messages from syslog mechanism. Will send new PR for multiple allegro decoder IP's fix

2022-10-11 06:49 UTC, closed without merging