Minor updates related to skd crash handling
Xilinx/XRT pull request #7154
Opened 2022-11-04 23:20 UTC by jeffli-xilinx

#### Problem solved by the commit
Missed last commit for PR comments

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered

#### How problem was solved, alternative solutions (if any) and why they were rejected

#### Risks (if any) associated the changes in the commit

#### What has been tested and how, request additional testing if necessary

#### Documentation impact (if any)

2022-11-05 01:38 UTC, gbuildx commented
Build Passed!

2022-11-05 05:20 UTC, sonals requested changes
1. Please update signatures of all relevant functions to use `enum kds_status` instead of `int status`
2. Remove all the `status` range checks like `if ((status >=  0) && (status < KDS_STAT_MAX))`

2022-11-05 05:22 UTC, sonals commented on src/runtime_src/core/edge/drm/zocl/zocl_cu_xgq.c
> +		if (unlikely(status == KDS_SKCRASHED))
`r.hdr.cstate = (status == KDS_SKCRASHED) ? XGQ_CMD_STATE_ABORTED : XGQ_CMD_STATE_COMPLETED`

and remove the previous r.hdr.cstate assignment.

2022-11-05 05:23 UTC, sonals commented on src/runtime_src/core/edge/skd/sk_daemon.cpp
> +	int exit_code = 128 + sig; // Linux exit code is always 128 + signal number
This does not add any value. Please remove.

2022-11-05 09:20 UTC, gbuildx commented
Build Passed!

2022-11-05 15:36 UTC, sonals commented on src/runtime_src/core/pcie/driver/linux/xocl/userpf/xocl_kds.c
> +		int error = (status == KDS_COMPLETED)?0:-EFAULT;
Add white space before/after operators:
` (status == KDS_COMPLETED) ? 0 : -EFAULT;`

2022-11-05 15:37 UTC, sonals commented on src/runtime_src/core/pcie/driver/linux/xocl/userpf/xocl_kds.c
> +		int error = (status == KDS_COMPLETED)?0:-EFAULT;
Add white space as above...

2022-11-05 15:43 UTC, sonals commented on src/runtime_src/core/edge/drm/zocl/zocl_cu_xgq.c
> +		r.rcode = ret;
rcode is unsigned int and we are storing signed int.
Should **rcode** be **s32**?

2022-11-07 22:49 UTC, gbuildx commented
Build Passed!

2022-11-11 04:50 UTC, sonals approved these changes

2022-11-11 19:47 UTC, rozumx approved these changes
Approved with some minor future pull request recommentations.

2022-11-11 19:47 UTC, rozumx commented on src/runtime_src/core/edge/drm/zocl/zocl_cu_xgq.c
> +	struct xgq_com_queue_entry r = {0};
Zero not needed
```suggestion
	struct xgq_com_queue_entry r = {};
```

2022-11-11 19:47 UTC, rozumx commented on src/runtime_src/core/edge/drm/zocl/zocl_cu_xgq.c
> +	int mask_idx = 0;
Thank you for initializing the variables.

2022-11-11 19:47 UTC, rozumx commented on src/runtime_src/core/edge/drm/zocl/zocl_cu_xgq.c
>  #if 0
Is this #if statement still needed.  If not, then maybe this code should be removed.

2022-11-11 19:47 UTC, rozumx commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/cu_xgq.c
>  	status->new_status = (cu_status == KDS_SKCRASHED) ? CU_AP_CRASHED : CU_AP_IDLE;
Add a new line before this statement to help prevent future developers from thinking that this line is associated with the above while loop.
```suggestion
	
	status->new_status = (cu_status == KDS_SKCRASHED) ? CU_AP_CRASHED : CU_AP_IDLE;
```

2022-11-11 19:48 UTC, merged