CR-1145195 & CR-1145192 xgq: retrieve clock scaling configs properly
Xilinx/XRT pull request #7184
Opened 2022-11-23 10:58 UTC by rajkumar-xilinx

Signed-off-by: Rajkumar Rampelli <rampelli@amd.com>

#### Problem solved by the commit
xgq driver requesting for clock scaling configs only once during it's init sequence and copied to scaling payload. But, this payload getting override by other sensor payload request/response data. 
Fix is to request clock scaling configs whenever required in xgq driver and read the configs from the scaling payload.
#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
CR-1145195 & CR-1145192
#### How problem was solved, alternative solutions (if any) and why they were rejected
Added changes in XGQ driver to issue clock scaling configs read request to VMR wherever required.
#### Risks (if any) associated the changes in the commit
NA
#### What has been tested and how, request additional testing if necessary
xbmgmt's cmc report & config commands, and access xgq's scaling sysfs nodes
#### Documentation impact (if any)
NA

2022-11-23 13:25 UTC, gbuildx commented
Build Failed! :(

2022-11-28 10:29 UTC, gbuildx commented
Build Passed!

2022-11-28 11:15 UTC, rajkumar-xilinx commented
VMR PR https://github.com/Xilinx/VMR/pull/265 is also under review.

2022-11-29 05:11 UTC, rajkumar-xilinx commented
Hi all, 
VMR changes are merged https://github.com/Xilinx/VMR/pull/265 . 
Please review this PR, thank you.

2022-11-29 18:10 UTC, chvamshi-xilinx approved these changes

2022-11-29 23:04 UTC, maxzhen requested changes

2022-11-29 23:04 UTC, maxzhen commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/xgq_vmr.c
> +	ret = clk_scaling_status_query(xgq->xgq_pdev);
don't you need to grab the lock (lock &xgq->clk_scaling_lock)?

2022-11-29 23:04 UTC, maxzhen commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/xgq_vmr.c
> +	ret = clk_scaling_status_query(xgq->xgq_pdev);
don't you need to grab the lock (lock &xgq->clk_scaling_lock)?

2022-11-29 23:04 UTC, maxzhen commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/xgq_vmr.c
> +	ret = clk_scaling_status_query(xgq->xgq_pdev);
don't you need to grab the lock (lock &xgq->clk_scaling_lock)?

2022-11-29 23:04 UTC, maxzhen commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/xgq_vmr.c
> +	ret = clk_scaling_status_query(xgq->xgq_pdev);
don't you need to grab the lock (lock &xgq->clk_scaling_lock)?

2022-11-29 23:04 UTC, maxzhen commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/xgq_vmr.c
> +	ret = clk_scaling_status_query(xgq->xgq_pdev);
don't you need to grab the lock (lock &xgq->clk_scaling_lock)?

2022-11-29 23:04 UTC, maxzhen commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/xgq_vmr.c
> +	ret = clk_scaling_status_query(xgq->xgq_pdev);
don't you need to grab the lock (lock &xgq->clk_scaling_lock)?

2022-11-29 23:04 UTC, maxzhen commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/xgq_vmr.c
> +	ret = clk_scaling_status_query(xgq->xgq_pdev);
don't you need to grab the lock (lock &xgq->clk_scaling_lock)?

2022-11-29 23:04 UTC, maxzhen commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/xgq_vmr.c
> +	ret = clk_scaling_status_query(xgq->xgq_pdev);
don't you need to grab the lock (lock &xgq->clk_scaling_lock)?

2022-11-30 11:24 UTC, gbuildx commented
Build Passed!

2022-11-30 18:09 UTC, rajkumar-xilinx commented
Hi @maxzhen 
I have taken care of your review comments, could you please review it again and let me know? Thank you.

2022-11-30 21:44 UTC, gbuildx commented
Build Failed! :(

2022-11-30 22:43 UTC, maxzhen approved these changes

2022-12-01 06:20 UTC, rajkumar-xilinx commented
retest this please

2022-12-01 10:14 UTC, gbuildx commented
Build Passed!

2022-12-01 10:25 UTC, merged