Cr 1145449 tolerance freq scaling
Xilinx/XRT pull request #7297
Opened 2023-01-20 20:16 UTC by prapulkrishnamurthy

#### Problem solved by the commit
Added Tolerance check against frequency counter to report error at dmesg
Change added in xgq driver

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
none

#### How problem was solved, alternative solutions (if any) and why they were rejected
Tolerance is read from VMR and compared with frequency counter for given target frequencies.

#### Risks (if any) associated the changes in the commit
There is a false failure reported in dmesg which can be ignored.

#### What has been tested and how, request additional testing if necessary
Tested on VCK5000 and V70

#### Documentation impact (if any)

2023-01-20 20:18 UTC, xdavidz commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/xgq_vmr.c
> +	int i = 0,ret = 0;
please add a space before ret
int i = 0, ret = 0;

2023-01-20 20:19 UTC, xdavidz requested changes
the indent is messed up, please fix all indents then I can start review the code.

2023-01-20 23:24 UTC, xdavidz commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/xgq_vmr.c
> +	ret = set_and_verify_freqs(pdev, target_freqs, ARRAY_SIZE(target_freqs),verify);
This function name doesn't make sense. If we look at the original code. for example:
https://github.com/Xilinx/XRT/blob/master/src/runtime_src/core/pcie/driver/linux/xocl/subdev/clock_wiz.c#L1005
The name should be clock_scaling. Recommend to not change this code. Remain unchanged.

2023-01-20 23:32 UTC, xdavidz commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/xgq_vmr.c
> +static int set_and_verify_freqs(struct platform_device *pdev,unsigned short *target_freqs, int num_freqs, int verify)
- change the existing xgq_freq_scaling to xgq_freq_scaling_impl
- add xgq_freq_scaling(... int verify)
  example
```
xgq_freq_scaling(...int verify)
{
      xgq_freq_scaling_impl()

     if (verify) {
         xgq_freq_verify() //add your new code in this function
    }
}
```

2023-01-22 00:43 UTC, xdavidz commented on src/runtime_src/core/pcie/driver/linux/xocl/xocl_xclbin.c
> +		ret = xocl_xgq_freq_scaling_by_topo(xdev, topo, 1);
since we changed the behavior on both vck5000 and v70. we'd better test it in case current valid might fail.

2023-01-22 00:45 UTC, xdavidz commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/xgq_vmr.c
> +	int i = 0, ret = 0;
There is a lint error. The ret is not being used anymore.

Please run
make clean;make -j

we should get a cleaner result without warnings. If you prefer, please fix those too.
if you prefer not to do so, you can ignore other developers's code. We will clean those up later.

2023-01-22 00:46 UTC, xdavidz commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/xgq_vmr.c
> +	ret = xgq_freq_scaling_impl(pdev, freqs, num_freqs);
this code has weird coding pattern, suggestions
```
	
        ret = xgq_freq_scaling_impl(pdev, freqs, num_freqs);
	if (ret) {
		XGQ_ERR(xgq, "ret %d", ret);
		return ret;
	}

	if (verify) {
		ret = xgq_freq_verify(pdev, freqs, num_freqs);
	}

	return ret;
```

2023-01-22 00:46 UTC, xdavidz commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/xgq_vmr.c
> +    return ret;
indent issue.

2023-01-22 00:48 UTC, xdavidz commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/xgq_vmr.c
> +	int ret = 0,i;
int ret = 0, i = 0;

or 
int ret = 0;
int i = 0;

2023-01-22 00:52 UTC, xdavidz commented on src/runtime_src/core/pcie/driver/linux/xocl/subdev/xgq_vmr.c
> +	enum data_kind kinds[3] = {FREQ_COUNTER_0,FREQ_COUNTER_1,FREQ_COUNTER_2};
we should not hardcode kinds here, instead, please check example code:
xocl_clock_get_freq_counter -> clock_counter_get_freq

2023-01-22 23:30 UTC, gbuildx commented
Build Passed!

2023-01-26 03:57 UTC, gbuildx commented
Build Failed! :(

2023-01-26 05:04 UTC, xdavidz approved these changes

2023-01-26 18:53 UTC, manikandan-xilinx commented
retest this please.

2023-01-26 21:36 UTC, gbuildx commented
Build Passed!

2023-01-26 21:49 UTC, maxzhen approved these changes

2023-01-26 21:49 UTC, merged