Remove libxrt_core from xbutil/xbmgmt
Xilinx/XRT pull request #7333
Opened 2023-02-02 00:51 UTC by dbenusov-xilinx

#### Problem solved by the commit
MCDM and future repository implementations will not provide libxrt_core for compilation. xbutil/xbmgmt should rely only on libxrt_coreutil, and libxrt_coreutil communicates with libxrt_core. Before integrating XRT into MCDM and others we must remove this dependency first.

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
XRT-MCDM does not export xrt_core functions and it should not. As a result, xbutil cannot compile in that environment even though it should,

#### How problem was solved, alternative solutions (if any) and why they were rejected
Removed xrt_core from xbutil/xbmgmt CMake files. Replace xrt_core function calls with xrt_coreutil functions calls.

#### Risks (if any) associated the changes in the commit
None, assuming I did it right

#### What has been tested and how, request additional testing if necessary
Ubuntu 20.04 
xbutil examine
```
dbenusov@xsjdbenusov50:/proj/rdi/staff/dbenusov/XRT$ xbutil examine
WARNING: Unexpected xocl version (2.14.0) was found. Expected 2.15.0, to match XRT tools.
System Configuration
  OS Name              : Linux
  Release              : 5.4.0-126-generic
  Version              : #142-Ubuntu SMP Fri Aug 26 12:12:57 UTC 2022
  Machine              : x86_64
  CPU Cores            : 16
  Memory               : 64007 MB
  Distribution         : Ubuntu 20.04.1 LTS
  GLIBC                : 2.31
  Model                : Precision 5820 Tower

XRT
  Version              : 2.15.0
  Branch               : remove-libxrtcore
  Hash                 : c56f8615c7ae3b908b3f3a15f4e3b1fd9562c95f
  Hash Date            : 2023-02-01 15:37:07
  XOCL                 : 2.14.0, a3befd1ac0b78555ee7150a3199795ed9b49887a
  XCLMGMT              : 2.14.0, a3befd1ac0b78555ee7150a3199795ed9b49887a

Devices present
BDF             :  Shell                              Platform UUID                         Device ID       Device Ready*
---------------------------------------------------------------------------------------------------------------------------
[0000:17:00.1]  :  xilinx_vck5000_gen4x8_qdma_base_2  05DCA096-76CB-730B-8D19-EC1192FBAE3F  user(inst=129)  Yes
```
xbutil validate
```
dbenusov@xsjdbenusov50:/proj/rdi/staff/dbenusov/XRT$ xbutil validate -d 17:00
WARNING: Unexpected xocl version (2.14.0) was found. Expected 2.15.0, to match XRT tools.
***********************************************************
*        WARNING          WARNING          WARNING        *
*  SC version data missing. Expected: N/A Current: 4.4.35 *
***********************************************************
Validate Device           : [0000:17:00.1]
    Platform              : xilinx_vck5000_gen4x8_qdma_base_2
    SC Version            : 4.4.35
    Platform ID           : 05DCA096-76CB-730B-8D19-EC1192FBAE3F
-------------------------------------------------------------------------------
Test 1 [0000:17:00.1]     : pcie-link
    Warning(s)            : Link is active
                            Please make sure that the device is plugged into Gen 4x8,
                            instead of Gen 3x8. Lower performance maybe experienced.
    Test Status           : [PASSED WITH WARNINGS]
-------------------------------------------------------------------------------
Test 2 [0000:17:00.1]     : sc-version
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Test 3 [0000:17:00.1]     : verify
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Test 4 [0000:17:00.1]     : dma
    Details               : Buffer size - '16 MB'
                            Host -> PCIe -> FPGA write bandwidth = 6527.5 MB/s
                            Host <- PCIe <- FPGA read bandwidth = 6616.9 MB/s
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Test 5 [0000:17:00.1]     : iops
    Details               : IOPS: 132921 (verify)
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Test 6 [0000:17:00.1]     : mem-bw
    Details               : Throughput (Type: DDR) (Bank count: 1) : 20729.7MB/s
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Test 7 [0000:17:00.1]     : p2p
Test 8 [0000:17:00.1]     : vcu
Test 9 [0000:17:00.1]     : aie-pl
    Test Status           : [PASSED]
-------------------------------------------------------------------------------
Validation completed, but with warnings. Please run the command '--verbose' option for more details
```
xbmgmt examine
```
dbenusov@xsjdbenusov50:/proj/rdi/staff/dbenusov/XRT$ xbmgmt examine
WARNING: Unexpected xclmgmt version (2.14.0) was found. Expected 2.15.0, to match XRT tools.
System Configuration
  OS Name              : Linux
  Release              : 5.4.0-126-generic
  Version              : #142-Ubuntu SMP Fri Aug 26 12:12:57 UTC 2022
  Machine              : x86_64
  CPU Cores            : 16
  Memory               : 64007 MB
  Distribution         : Ubuntu 20.04.1 LTS
  GLIBC                : 2.31
  Model                : Precision 5820 Tower

XRT
  Version              : 2.15.0
  Branch               : remove-libxrtcore
  Hash                 : c56f8615c7ae3b908b3f3a15f4e3b1fd9562c95f
  Hash Date            : 2023-02-01 15:37:07
  XOCL                 : 2.14.0, a3befd1ac0b78555ee7150a3199795ed9b49887a
  XCLMGMT              : 2.14.0, a3befd1ac0b78555ee7150a3199795ed9b49887a

Devices present
BDF             :  Shell                              Platform UUID                         Device ID        Device Ready*
----------------------------------------------------------------------------------------------------------------------------
[0000:17:00.0]  :  xilinx_vck5000_gen4x8_qdma_base_2  05DCA096-76CB-730B-8D19-EC1192FBAE3F  mgmt(inst=5888)  Yes
```
#### Documentation impact (if any)
None

2023-02-02 04:55 UTC, gbuildx commented
Build Failed! :(

2023-02-02 22:46 UTC, gbuildx commented
Build Failed! :(

2023-02-03 00:34 UTC, dayeh-xilinx commented
retest this please.

2023-02-03 05:53 UTC, gbuildx commented
Build Failed! :(

2023-02-03 10:53 UTC, chvamshi-xilinx approved these changes
Looks good.

2023-02-03 17:51 UTC, stsoe requested changes
This is a good first step.  I see a bunch of alloc_bo() calls, can they not be replaced with xrt::bo?
I would also recommend passing `const xrt_core::device*` in place of shared_ptr if ownership is guaranteed by caller and not shared with callee.

2023-02-03 17:51 UTC, stsoe commented on src/runtime_src/core/pcie/common/dmatest.h
> +                } catch (const std::exception&) {
```suggestion
                } 
                catch (const std::exception&) {
```

2023-02-04 01:57 UTC, gbuildx commented
Build Passed!

2023-02-07 23:13 UTC, gbuildx commented
Build Passed!

2023-02-08 01:28 UTC, stsoe approved these changes

2023-02-08 01:29 UTC, merged