CR-1135808 Some improvement suggestions for throttling feature
Xilinx/XRT pull request #7346
Opened 2023-02-07 01:01 UTC by rchane

#### Problem solved by the commit
https://jira.xilinx.com/browse/CR-1135808 Output for user could use clarification for cmc report. "Scaling" should be renamed to "throttling."
#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
Implemented suggestions 1 and 2. Suggestions 3 and 4 were taken care of previously.
#### How problem was solved, alternative solutions (if any) and why they were rejected
xbutil no longer outputs cmc status, as one should use xbmgmt to check and enable/disable CTS (clock throttling/shutdown). xbmgmt will not show status without an xclbin.
#### Risks (if any) associated the changes in the commit
ptree structure for the report was changed slightly with another subtree (additional `device_stats` child added to `cmc_tree`).
#### What has been tested and how, request additional testing if necessary
xbutil will not show cmc status.
```
rchane@xsjsagarw50:/proj/rdi/staff/rchane/XRT$ xbutil examine -d 17:00 -r cmc
XRT build version: 2.15.0
Build hash: 3445fc127610829976a7da2f43488d4e2c6e1de9
Build date: 2023-02-06 16:27:56
Git branch: CR-1135808
PID: 319994
UID: 90979
[Tue Feb  7 00:34:24 2023 GMT]
HOST: xsjsagarw50
EXE: /proj/xsjhdstaff4/rchane/XRT/build/Debug/opt/xilinx/xrt/bin/unwrapped/xbutil2
[xbutil] ERROR: No report generator found for report: 'cmc'
: Invalid argument
```
Runtime Clock Scaling is now Clock Throttling and Shutdown:
```
rchane@xsjsagarw50:/proj/rdi/staff/rchane/XRT$ xbmgmt examine -d 17:00 -r cmc

------------------------------------------
[0000:17:00.0] : xilinx_u30_gen3x4_base_2
------------------------------------------
CMC
  Heartbeat information unavailable
  Clock Throttling and Shutdown:
    Not supported
```
Without a loaded xclbin, Clock Throttling and Shutdown now warns the user:
```
  Clock Throttling and Shutdown:
    Unable to show status without XCLBIN
```
#### Documentation impact (if any)
The github.io page should reflect the changes to the cmc report. https://jira.xilinx.com/browse/CR-1150767 will include documentation update to describe how to enable/disable CTS.

2023-02-07 04:11 UTC, gbuildx commented
Build Passed!

2023-02-07 07:49 UTC, chvamshi-xilinx commented
Hi @rchane , Overall, changes are looking good, Can you please compare the json output with and without your changes.
There are more changes required to rename all the ini options from "scaling" to "throttling" in subCmdConfigure.cpp. Please make those changes in separate PR

2023-02-07 19:06 UTC, dbenusov-xilinx requested changes

2023-02-07 19:06 UTC, dbenusov-xilinx commented on src/runtime_src/core/tools/common/ReportCmcStatus.cpp
> +  cmc_tree.add_child("device_stats", device_stat_tree);
We definitely should not be placing the entire dynamic region report into the cmc property tree.

If we want the xclbin uuid there are better ways of getting it other than going the dynamic region report.
```suggestion
  cmc_tree.add_child("xclbin_uuid", _pDevice->get_xclbin_uuid());
```
We could also just state if the xclbin is valid through the property tree
```suggestion
  cmc_tree.add_child("cmc_status_valid", boost::iequals(_pDevice->get_xclbin_uuid(), N/A"));
```

2023-02-18 00:01 UTC, gbuildx commented
Build Passed!

2023-02-18 00:20 UTC, dbenusov-xilinx approved these changes
Minor changes, nothing to stop merging though. Looks great!

2023-02-18 00:20 UTC, dbenusov-xilinx commented on src/runtime_src/core/tools/common/ReportCmcStatus.cpp
> +	  auto clk_scaling_data = xrt_core::device_query<xrt_core::query::clk_scaling_info>(_pDevice);
Weird spacing here?

2023-02-18 00:20 UTC, dbenusov-xilinx commented on src/runtime_src/core/tools/common/ReportCmcStatus.cpp
> +    if (!cmc_throttle.get<bool>("enabled")) {
Add a new line to separate the if statements. I thought they were an if/elseif grouping!

2023-02-18 07:38 UTC, chvamshi-xilinx approved these changes

2023-02-18 07:39 UTC, chvamshi-xilinx commented
Hi @rchane , Please fix formatting issues raised by Daniel in next PR.

2023-02-18 07:39 UTC, merged