src/runtime_src/tools/scripts: Add setup.zsh for use with the zsh shell
Xilinx/XRT pull request #7368
Opened 2023-02-15 08:47 UTC by mgehre-amd

#### Problem solved by the commit
Provides a setup.zsh that can be used when using the zsh shell.

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
Fixes #7366

#### How problem was solved, alternative solutions (if any) and why they were rejected
Alternatively, we could modify setup.sh to detect which shell is being used,
to provide a single script.

#### Risks (if any) associated the changes in the commit

#### What has been tested and how, request additional testing if necessary

#### Documentation impact (if any)

2023-02-15 08:48 UTC, gbuildx commented
Can one of the admins verify this patch?

2023-03-08 01:38 UTC, keryell requested changes
As you said:
> Alternatively, we could modify setup.sh to detect which shell is being used,
to provide a single script.

That sounds like a great idea to avoid adding to the existing technical debt. :-)

2023-03-08 01:38 UTC, keryell commented on src/runtime_src/tools/scripts/setup.zsh
> +fi
I thought the goal of `/etc/os-release` was to just source it, not parse it...

2023-03-08 01:38 UTC, keryell commented on src/runtime_src/tools/scripts/setup.zsh
> +# be sourced from that location
Which means the line 1 should not exist for a second reason.

2023-03-08 01:38 UTC, keryell commented on src/runtime_src/tools/scripts/setup.zsh
> +if [[ $- != *e* ]] && [[ "$BASH" == *"/bash" ]] && [ -f "${COMP_FILE}" ]; then
I am a little bit lost here. I thought this was about `zsh`. Is there anything specific to `zsh` here anyway?

2023-03-08 09:04 UTC, mgehre-amd commented
@keryell, thanks for your review. The only difference between setup.zsh and setup.sh is
```
--- src/runtime_src/tools/scripts/setup.zsh     2023-02-15 09:45:01.145363000 +0100
+++ src/runtime_src/tools/scripts/setup.sh      2023-02-15 09:43:31.447311000 +0100
@@ -30,7 +30,7 @@
     fi
 fi

-XILINX_XRT=$(readlink -f $(dirname ${(%):-%N}))
+XILINX_XRT=$(readlink -f $(dirname ${BASH_SOURCE[0]:-${(%):-%x}}))

 if [[ $XILINX_XRT != *"/opt/xilinx/xrt" ]]; then
     echo "Invalid location: $XILINX_XRT"
```
so your other comments apply equally to the setup.sh script.

As a next step, I will merge my changes into the setup.sh script, so we have only one that works for both bash and zsh.

2023-03-08 18:11 UTC, keryell approved these changes
Thanks.
Feel free to fix the rest of script if you are motivated. :-)

2023-03-09 08:06 UTC, mgehre-amd commented on src/runtime_src/tools/scripts/setup.sh
> +    echo "ERROR: Unsupported shell. Only bash and zsh are supported"
Sorry, I'm not sure if you would like me to change my commit?

2023-03-10 02:44 UTC, keryell commented on src/runtime_src/tools/scripts/setup.sh
> +    echo "ERROR: Unsupported shell. Only bash and zsh are supported"
Nothing. I was just some wondering.

2023-03-14 09:59 UTC, chvamshi-xilinx commented
ok to test

2023-03-14 20:17 UTC, gbuildx commented
Build Failed! :(

2023-03-15 01:38 UTC, dayeh-xilinx commented
retest this please.

2023-03-15 07:12 UTC, gbuildx commented
Build Passed!

2023-03-20 16:16 UTC, mgehre-amd commented
Ping @rozumx & @stsoe for review.

2023-03-20 17:46 UTC, stsoe approved these changes

2023-04-04 02:48 UTC, merged