aie status dump support for vek280
Xilinx/XRT pull request #7393
Opened 2023-02-23 14:36 UTC by saumyag-xilinx

#### Problem solved by the commit
Enabling aie status dump support for vek280
#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered

#### How problem was solved, alternative solutions (if any) and why they were rejected

#### Risks (if any) associated the changes in the commit

#### What has been tested and how, request additional testing if necessary
Tested aie and aie_mem report on vek280 (attaching the output of 1 mem tile below)

> versal-rootfs-common-20231:/mnt# xbutil examine -r aie -d 
Aie
  Aie_Metadata
  GRAPH[ 0] Name      : aie_graph
            Status    : unknown
    SNo.  Core [C:R]          Iteration_Memory [C:R]        Iteration_Memory_Addresses    
    [ 0]   18:0                18:0                          4                             

Core [ 0]
    Column                : 18
    Row                   : 0
    Core:
        Status                : enable, reset
        Program Counter       : 0x00000000
        Link Register         : 0x00000000
        Stack Pointer         : 0x00000000
    DMA:
        MM2S:
            Channel:
                Id                    : 0
                Channel Status        : idle
                Queue Size            : 0
                Queue Status          : okay
                Current BD            : 0

                Id                    : 1
                Channel Status        : idle
                Queue Size            : 0
                Queue Status          : okay
                Current BD            : 0

        S2MM:
            Channel:
                Id                    : 0
                Channel Status        : idle
                Queue Size            : 0
                Queue Status          : okay
                Current BD            : 0

                Id                    : 1
                Channel Status        : idle
                Queue Size            : 0
                Queue Status          : okay
                Current BD            : 0

    Locks:
        0                     : 0
        1                     : 0
        2                     : 0
        3                     : 0
        4                     : 0
        5                     : 0
        6                     : 0
        7                     : 0
        8                     : 0
        9                     : 0
        10                    : 0
        11                    : 0
        12                    : 0
        13                    : 0
        14                    : 0
        15                    : 0

    Events:
        core                  : 1
        memory                : 1

versal-rootfs-common-20231:/mnt# xbutil examine -r aie_mem -d

> AIE
  Mem Status
Tile[ 0]
    Column                : 0
    Row                   : 1
    DMA:
        FIFO:
        MM2S:
            Channel:
                Id                    : 0
                Channel Status        : idle
                Queue Size            : 0
                Queue Status          : okay
                Current BD            : 0

                Id                    : 1
                Channel Status        : idle
                Queue Size            : 0
                Queue Status          : okay
                Current BD            : 0

                Id                    : 2
                Channel Status        : idle
                Queue Size            : 0
                Queue Status          : okay
                Current BD            : 0

                Id                    : 3
                Channel Status        : idle
                Queue Size            : 0
                Queue Status          : okay
                Current BD            : 0

                Id                    : 4
                Channel Status        : idle
                Queue Size            : 0
                Queue Status          : okay
                Current BD            : 0

                Id                    : 5
                Channel Status        : idle
                Queue Size            : 0
                Queue Status          : okay
                Current BD            : 0

        S2MM:
            Channel:
                Id                    : 0
                Channel Status        : idle
                Queue Size            : 0
                Queue Status          : okay
                Current BD            : 0

                Id                    : 1
                Channel Status        : idle
                Queue Size            : 0
                Queue Status          : okay
                Current BD            : 0

                Id                    : 2
                Channel Status        : idle
                Queue Size            : 0
                Queue Status          : okay
                Current BD            : 0

                Id                    : 3
                Channel Status        : idle
                Queue Size            : 0
                Queue Status          : okay
                Current BD            : 0

                Id                    : 4
                Channel Status        : idle
                Queue Size            : 0
                Queue Status          : okay
                Current BD            : 0

                Id                    : 5
                Channel Status        : idle
                Queue Size            : 0
                Queue Status          : okay
                Current BD            : 0

    Locks:
        0                     : 0
        1                     : 0
        2                     : 0
        3                     : 0
        4                     : 0
        5                     : 0
        6                     : 0
        7                     : 0
        8                     : 0
        9                     : 0
        10                    : 0
        11                    : 0
        12                    : 0
        13                    : 0
        14                    : 0
        15                    : 0
        16                    : 0
        17                    : 0
        18                    : 0
        19                    : 0
        20                    : 0
        21                    : 0
        22                    : 0
        23                    : 0
        24                    : 0
        25                    : 0
        26                    : 0
        27                    : 0
        28                    : 0
        29                    : 0
        30                    : 0
        31                    : 0
        32                    : 0
        33                    : 0
        34                    : 0
        35                    : 0
        36                    : 0
        37                    : 0
        38                    : 0
        39                    : 0
        40                    : 0
        41                    : 0
        42                    : 0
        43                    : 0
        44                    : 0
        45                    : 0
        46                    : 0
        47                    : 0
        48                    : 0
        49                    : 0
        50                    : 0
        51                    : 0
        52                    : 0
        53                    : 0
        54                    : 0
        55                    : 0
        56                    : 0
        57                    : 0
        58                    : 0
        59                    : 0
        60                    : 0
        61                    : 0
        62                    : 0
        63                    : 0

    Events:
        memory_tile           : 

#### Documentation impact (if any)

2023-02-23 15:33 UTC, gbuildx commented
Build Failed! :(

2023-02-23 16:26 UTC, stsoe requested changes
Just a few style comments, please fix those I didn't note.

2023-02-23 16:26 UTC, stsoe commented on src/runtime_src/core/edge/user/device_linux.cpp
> +get_aie_row_col(const xrt_core::device* device, aie_metadata_info &aie_meta)
```suggestion
get_aie_row_col(const xrt_core::device* device, aie_metadata_info& aie_meta)
```
The function name indicates a return value.  If aie_metadata_info is appended, the the function name should be `add_aie_row_col`.   If aie_metadata_info is completely filled by this function, then it should be constructed and returned by this function.

2023-02-23 16:26 UTC, stsoe commented on src/runtime_src/core/edge/user/device_linux.cpp
> +    for(int i=0;i<aie_meta.num_cols;i++)
```suggestion
    for  (int i = 0; i < aie_meta.num_cols; ++i)
```
Double nesting suggests refactor.

2023-02-23 16:26 UTC, stsoe commented on src/runtime_src/core/edge/user/device_linux.cpp
> +      for(int j=0; j<(aie_meta.num_rows-1);j++)
```suggestion
      for (int j = 0;  j < (aie_meta.num_rows-1); ++j)
```

2023-02-23 16:26 UTC, stsoe commented on src/runtime_src/core/edge/user/device_linux.cpp
> +      ptarray.push_back(std::make_pair("", aie_sys_parser::get_parser(aiepart)->aie_sys_read(i,aie_meta.shim_row)));
```suggestion
    for (int i = 0; i < aie_meta.num_cols; ++i) {
      ptarray.push_back(std::make_pair("", aie_sys_parser::get_parser(aiepart)->aie_sys_read(i, aie_meta.shim_row)));
```

2023-02-23 16:26 UTC, stsoe commented on src/runtime_src/core/edge/user/device_linux.cpp
> +    std::string aiepart = std::to_string(aie_meta.shim_row)+"_"+std::to_string(aie_meta.num_cols);
```suggestion
    std::string aiepart = std::to_string(aie_meta.shim_row) + "_" + std::to_string(aie_meta.num_cols);
```

2023-02-27 11:12 UTC, chvamshi-xilinx commented on src/runtime_src/core/edge/user/device_linux.cpp
> +get_aie_row_col(const xrt_core::device* device, aie_metadata_info& aie_meta)
We dont need the second argument anymore.
Also , change the function name to something like get_aie_metadata

2023-02-27 11:13 UTC, chvamshi-xilinx requested changes

2023-02-27 11:13 UTC, chvamshi-xilinx commented on src/runtime_src/core/edge/user/device_linux.cpp
> +    std::string aiepart = std::to_string(aie_meta.shim_row) + "_" + std::to_string(aie_meta.num_cols);
const std::string

2023-02-27 11:13 UTC, chvamshi-xilinx commented on src/runtime_src/core/edge/user/device_linux.cpp
> +    std::string aiepart = std::to_string(aie_meta.shim_row) + "_" + std::to_string(aie_meta.num_cols);
const std:;string

2023-02-27 11:13 UTC, chvamshi-xilinx commented on src/runtime_src/core/edge/user/device_linux.cpp
> +    std::string aiepart = std::to_string(aie_meta.shim_row) + "_" + std::to_string(aie_meta.num_cols);
const std::string

2023-02-27 11:39 UTC, gbuildx commented
Build Passed!

2023-02-27 16:57 UTC, gbuildx commented
Build Passed!

2023-02-27 19:07 UTC, gbuildx commented
Build Passed!

2023-02-28 06:29 UTC, chvamshi-xilinx approved these changes
Looks good

2023-03-01 05:33 UTC, saumyag-xilinx commented
Hi @stsoe, thank you for your suggestions. I have made the requested changes, can you please review it.

2023-03-01 16:50 UTC, stsoe approved these changes

2023-03-01 16:50 UTC, merged