Fix for CR-1154512: xbmgmt reset does not work
Xilinx/XRT pull request #7430
Opened 2023-03-08 15:47 UTC by saumyag-xilinx

#### Problem solved by the commit
https://jira.xilinx.com/browse/CR-1154512
#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
https://github.com/Xilinx/XRT/pull/7293
#### How problem was solved, alternative solutions (if any) and why they were rejected

#### Risks (if any) associated the changes in the commit
na
#### What has been tested and how, request additional testing if necessary
Verified the fix on v70 setup:
bash-4.2# xbmgmt reset -d 0000:3b:00.0
***********************************************************
*        WARNING          WARNING          WARNING        *
*   SC version data missing. Expected: N/A Current: N/A   *
***********************************************************
Performing 'HOT Reset' on 
  -[0000:3b:00.0]
WARNING: Please make sure xocl driver is unloaded.
Are you sure you wish to proceed? [Y/n]: y
Successfully reset Device[0000:3b:00.0]

#### Documentation impact (if any)
na

2023-03-08 21:17 UTC, dbenusov-xilinx requested changes

2023-03-08 21:17 UTC, dbenusov-xilinx commented on src/runtime_src/core/tools/xbmgmt2/SubCmdReset.cpp
>  }
```suggestion
  m_hiddenOptions.add_options()
    ("type,t", boost::program_options::value<decltype(m_resetType)>(&m_resetType)->notifier(supported), "The type of reset to perform. Types resets available:\n"
                                                                        "  kernel       - Kernel communication links\n" 
                                                                        "  ert          - Reset management processor\n"
                                                                        "  ecc          - Reset ecc memory\n"
                                                                        "  soft-kernel  - Reset soft kernel")
  ;
}
```
This is missing the hidden type parameter from the original SubCmdReset

2023-03-08 21:53 UTC, dbenusov-xilinx commented on src/runtime_src/core/tools/xbmgmt2/SubCmdReset.cpp
>  }
This is the supported function:
```
static void
supported(std::string resetType) {
  std::vector<std::string> vec { "user" };
  std::vector<std::string>::iterator it;
  it = std::find (vec.begin(), vec.end(), resetType); 
  if (it == vec.end()) {
    throw xrt_core::error(-ENODEV, "reset not supported");
  }
}
```

2023-03-09 02:53 UTC, dayeh-xilinx commented
retest this please.

2023-03-09 10:38 UTC, gbuildx commented
Build Passed!

2023-03-09 17:38 UTC, dbenusov-xilinx approved these changes
Perfect! Thank you :)

2023-03-09 19:41 UTC, chvamshi-xilinx approved these changes

2023-03-09 21:18 UTC, gbuildx commented
Build Failed! :(

2023-03-10 02:11 UTC, dayeh-xilinx commented
retest this please.

2023-03-10 09:26 UTC, gbuildx commented
Build Passed!

2023-03-10 09:34 UTC, merged