AIE reset support. Slot separation for PL and AIE only XCLBIN
Xilinx/XRT pull request #7440
Opened 2023-03-13 20:28 UTC by saifuddin-xilinx

#### Problem solved by the commit

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered

#### How problem was solved, alternative solutions (if any) and why they were rejected

#### Risks (if any) associated the changes in the commit

#### What has been tested and how, request additional testing if necessary

#### Documentation impact (if any)

2023-03-13 21:07 UTC, gbuildx commented
Build Failed! :(

2023-03-13 21:35 UTC, saifuddin-xilinx commented
retest this please

2023-03-14 08:18 UTC, chvamshi-xilinx requested changes

2023-03-14 08:18 UTC, chvamshi-xilinx commented on src/runtime_src/core/edge/drm/zocl/zocl_drv.c
> +		zocl_slot->slot_type = ZOCL_PL_ONLY_XCLBIN;
DOMAIN_PL and ZOCL_PL_ONLY_XCLBINs are differrent. I didnt understand how u r mapping this.

2023-03-14 08:18 UTC, chvamshi-xilinx commented on src/runtime_src/core/edge/drm/zocl/zocl_drv.c
> +		zocl_slot->slot_type = ZOCL_PS_ONLY_XCLBIN;
Ditto.

2023-03-14 08:18 UTC, chvamshi-xilinx commented on src/runtime_src/core/edge/drm/zocl/zocl_xclbin.c
> +	for (i = 0; i < MAX_PR_SLOT_NUM; i++) {
why to iterate over MAX_PR_SLOT_NUM?

2023-03-14 08:18 UTC, chvamshi-xilinx commented on src/runtime_src/core/edge/drm/zocl/zocl_xclbin.c
> +	if (!xrt_xclbin_get_section_num(axlf, IP_LAYOUT) &&
have the old check also, axlf->m_header.m_actionMask & AM_LOAD_AIE OR new condition

2023-03-14 09:53 UTC, chvamshi-xilinx commented
retest this please

2023-03-14 11:44 UTC, chvamshi-xilinx commented
Hi @saifuddin-xilinx , Adding "do not review" tag. Please fix all the issues which are discussed offline.

2023-03-14 21:27 UTC, gbuildx commented
Build Failed! :(

2023-03-14 23:40 UTC, gbuildx commented
Build Failed! :(

2023-03-17 05:38 UTC, chvamshi-xilinx approved these changes
Looks good

2023-03-17 06:15 UTC, gbuildx commented
Build Failed! :(

2023-03-17 12:24 UTC, saifuddin-xilinx commented
retest this please

2023-03-17 16:11 UTC, gbuildx commented
Build Passed!

2023-03-17 17:45 UTC, mamin506 approved these changes

2023-03-21 09:18 UTC, merged