VITIS-6885: Adding buffer descriptor information for core and mem tiles in respective aie reports
Xilinx/XRT pull request #7446
Opened 2023-03-16 16:14 UTC by saumyag-xilinx

#### Problem solved by the commit
https://jira.xilinx.com/browse/VITIS-6885
#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
N/A
#### How problem was solved, alternative solutions (if any) and why they were rejected
Made user space changes to add all buffer descriptor information for core and mem tiles.
#### Risks (if any) associated the changes in the commit
N/A
#### What has been tested and how, request additional testing if necessary
Adding output of aie report for vck190 (here displaying only two bds info for one of the core tile)

Aie
  Aie_Metadata
  GRAPH[ 0] Name      : clipgraph
            Status    : unknown
    SNo.  Core [C:R]          Iteration_Memory [C:R]        Iteration_Memory_Addresses    
    [ 0]   24:0                24:1                          12100                         
    [ 1]   25:0                24:0                          7012                          

Core [ 0]
    Column                : 24
    Row                   : 0
    Core:
        Status                : enabled, north_lock_stall
        Program Counter       : 0x00000282
        Link Register         : 0x000000b0
        Stack Pointer         : 0x00033000
    DMA:
        MM2S:
            Channel:
                Id                    : 0
                Channel Status        : stalled_on_requesting_lock
                Queue Size            : 0
                Queue Status          : okay
                Current BD            : 0

                Id                    : 1
                Channel Status        : idle
                Queue Size            : 0
                Queue Status          : okay
                Current BD            : 0

        S2MM:
            Channel:
                Id                    : 0
                Channel Status        : idle
                Queue Size            : 0
                Queue Status          : okay
                Current BD            : 0

                Id                    : 1
                Channel Status        : idle
                Queue Size            : 0
                Queue Status          : okay
                Current BD            : 0

    Locks:
        0                     : acquired_for_write
        1                     : released_for_write
        2                     : released_for_write
        3                     : released_for_write
        4                     : released_for_write
        5                     : released_for_write
        6                     : released_for_write
        7                     : released_for_write
        8                     : released_for_write
        9                     : released_for_write
        10                    : released_for_write
        11                    : released_for_write
        12                    : released_for_write
        13                    : released_for_write
        14                    : released_for_write
        15                    : released_for_write

    Events:
        core                  : 1, 2, 5, 22, 26, 28, 29, 32, 35, 38, 39, 44
        memory                : 1, 20, 23, 35, 43, 44, 106, 113

    Buffer Descriptor :
        Number of BDs         : 16
            BD number             : bd0
            Address A             : 0x800
            Address B             : 0x0
            Length                : 255
            Lock Acquire Id A     : 0
            Lock Acquire Value A  : 1
            Lock Release Value A  : 0
            Lock Acquire Id B     : 0
            Lock Acquire Value B  : 0
            Lock Release Value B  : 0
            X Increment           : 0
            X Wrap                : 255
            X Offset              : 0x1
            Y Increment           : 255
            Y Wrap                : 0
            Y Offset              : 0x100
            D0 Stepsize           : 0
            D0 Wrap               : 0
            D1 Stepsize           : 0
            D1 Wrap               : 0
            D2 Stepsize           : 0
            D2 Wrap               : 0
            D3 Stepsize           : 0

            BD number             : bd1
            Address A             : 0x1100
            Address B             : 0x0
            Length                : 255
            Lock Acquire Id A     : 1
            Lock Acquire Value A  : 1
            Lock Release Value A  : 0
            Lock Acquire Id B     : 0
            Lock Acquire Value B  : 0
            Lock Release Value B  : 0
            X Increment           : 0
            X Wrap                : 255
            X Offset              : 0x1
            Y Increment           : 255
            Y Wrap                : 0
            Y Offset              : 0x100
            D0 Stepsize           : 0
            D0 Wrap               : 0
            D1 Stepsize           : 0
            D1 Wrap               : 0
            D2 Stepsize           : 0
            D2 Wrap               : 0
            D3 Stepsize           : 0

#### Documentation impact (if any)

2023-03-16 16:32 UTC, stsoe reviewed
LGTM.  One minor smart pointer comment, there is no need to release() and delete before reassigning.

2023-03-16 16:32 UTC, stsoe commented on src/runtime_src/core/edge/user/shim.cpp
> +  aieArray = std::make_unique<zynqaie::Aie>(mCoreDevice, config);
```suggestion
  aieArray = std::make_unique<zynqaie::Aie>(mCoreDevice, config);
```

2023-03-16 16:57 UTC, larry9523 commented
A higher level question. IIRC, when xbutil displays AIE status, it query the sysfs nodes created by aie2 kernel driver. Is there a specific reason why for BD data, we want call aie2 user space API to read them directly?

2023-03-16 17:07 UTC, chvamshi-xilinx commented
> A higher level question. IIRC, when xbutil displays AIE status, it query the sysfs nodes created by aie2 kernel driver. Is there a specific reason why for BD data, we want call aie2 user space API to read them directly?

i am not 100% sure, but most likely the reason for going to user level API is to reduce sysfs entries in a system. VCK190 has 450 tiles, and Each Tile has around 15BDs and each BD has lot of information. ( We could have gone with driver API also ) 
@rbramand-xilinx / @saumyag-xilinx  can confirm.

2023-03-16 18:00 UTC, gbuildx commented
Build Failed! :(

2023-03-17 05:15 UTC, saumyag-xilinx commented
> A higher level question. IIRC, when xbutil displays AIE status, it query the sysfs nodes created by aie2 kernel driver. Is there a specific reason why for BD data, we want call aie2 user space API to read them directly?



> > A higher level question. IIRC, when xbutil displays AIE status, it query the sysfs nodes created by aie2 kernel driver. Is there a specific reason why for BD data, we want call aie2 user space API to read them directly?
> 
> i am not 100% sure, but most likely the reason for going to user level API is to reduce sysfs entries in a system. VCK190 has 450 tiles, and Each Tile has around 15BDs and each BD has lot of information. ( We could have gone with driver API also ) @rbramand-xilinx / @saumyag-xilinx can confirm.

That's right @chvamshi-xilinx. The main reason was that there was too much information to export over sysfs. Not just core tiles having around 16 BDs but each memtile will have around 47 buffer descriptors. So that's why we are using API to read BD info, than sysfs nodes.

2023-03-20 06:24 UTC, saumyag-xilinx commented
> > > A higher level question. IIRC, when xbutil displays AIE status, it query the sysfs nodes created by aie2 kernel driver. Is there a specific reason why for BD data, we want call aie2 user space API to read them directly?
> > 
> > 
> > > > A higher level question. IIRC, when xbutil displays AIE status, it query the sysfs nodes created by aie2 kernel driver. Is there a specific reason why for BD data, we want call aie2 user space API to read them directly?
> > > 
> > > 
> > > i am not 100% sure, but most likely the reason for going to user level API is to reduce sysfs entries in a system. VCK190 has 450 tiles, and Each Tile has around 15BDs and each BD has lot of information. ( We could have gone with driver API also ) @rbramand-xilinx / @saumyag-xilinx can confirm.
> > 
> > 
> > That's right @chvamshi-xilinx. The main reason was that there was too much information to export over sysfs. Not just core tiles having around 16 BDs but each memtile will have around 47 buffer descriptors. So that's why we are using API to read BD info, than sysfs nodes.
> 
> Maybe I missed something. But I thought aie2 kernel driver has already exported the sysfs nodes, no?

Hi @larry9523, this is the implementation from aie team, for BD information no sysfs is exported.

2023-03-20 08:12 UTC, gbuildx commented
Build Failed! :(

2023-03-20 13:42 UTC, gbuildx commented
Build Failed! :(

2023-03-23 18:25 UTC, chvamshi-xilinx requested changes
Why do we need to have an extra query to populate bd info? Why cant we use existing queries for core/mem/shim to fill this information aswell? 
am i missing anything?

2023-03-26 05:21 UTC, chvamshi-xilinx commented
retest this please

2023-03-26 07:31 UTC, gbuildx commented
Build Failed! :(

2023-03-28 16:22 UTC, saumyag-xilinx commented
> Why do we need to have an extra query to populate bd info? Why cant we use existing queries for core/mem/shim to fill this information aswell? am i missing anything?

Made requested changes.

2023-03-28 17:06 UTC, stsoe requested changes

2023-03-28 17:06 UTC, stsoe commented on src/runtime_src/core/edge/user/device_linux.cpp
> +get_bd_mem(zynqaie::Aie* aieArray, boost::property_tree::ptree& aie_meta , boost::property_tree::ptree& ptarray, uint8_t& row_offset)
A get function usually returns some thing, in this case the `ptarray`, but if it is adding to `ptarray` then the function name should reflect this.  Also if `aie_meta` is not modified it should be `const`

2023-03-28 17:06 UTC, stsoe commented on src/runtime_src/core/edge/user/device_linux.cpp
> +get_used_tile_bdinfo(const xrt_core::device* device, boost::property_tree::ptree& ptarray, bool is_core_tile)
Ditto about return value or proper function name.

2023-03-28 17:06 UTC, stsoe commented on src/runtime_src/core/edge/user/shim.cpp
> +registerAieArray(adf::driver_config& config)
Is `config` modified?  If not it should be `const`

2023-03-28 17:06 UTC, stsoe commented on src/runtime_src/core/edge/user/shim.h
> +  void registerAieArray(adf::driver_config& config);
const ?

2023-03-28 18:08 UTC, gbuildx commented
Build Failed! :(

2023-03-28 20:20 UTC, gbuildx commented
Build Failed! :(

2023-03-28 23:56 UTC, dayeh-xilinx commented
retest this please.

2023-03-29 02:30 UTC, gbuildx commented
Build Failed! :(

2023-03-29 11:23 UTC, gbuildx commented
Build Failed! :(

2023-03-29 15:01 UTC, stsoe approved these changes

2023-03-29 17:30 UTC, dayeh-xilinx commented
retest this please.

2023-03-30 17:24 UTC, dayeh-xilinx commented
retest this please.

2023-03-31 06:21 UTC, gbuildx commented
Build Failed! :(

2023-03-31 17:13 UTC, dayeh-xilinx commented
retest this please.

2023-03-31 22:22 UTC, gbuildx commented
Build Passed!

2023-04-05 16:17 UTC, chvamshi-xilinx commented
Saumya/Gregory Coming up with new design proposed by Larry.

2023-04-05 16:17 UTC, closed without merging