CR-1164853_Linux_Coding_Style_Adjust
Xilinx/XRT pull request #7574
Opened 2023-06-05 20:47 UTC by prapulkrishnamurthy

#### Problem solved by the commit

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered

#### How problem was solved, alternative solutions (if any) and why they were rejected
There is a variable called 'jiffies' which records timer ticks to keep track of timeout used in xgq_vmr.c.
Changed the direct comparison of this by using time_after  the Linux latest coding standards.

#### Risks (if any) associated the changes in the commit

#### What has been tested and how, request additional testing if necessary
This change is made in command queue interface; and tested Opcode base sysfs nodes on V70.

#### Documentation impact (if any)

2023-06-05 20:48 UTC, gbuildx commented
Can one of the admins verify this patch?

2023-06-05 22:08 UTC, maxzhen approved these changes

2023-06-06 05:07 UTC, xdavidz requested changes
There is another one at lin 333 within function xgq_submitted_cmds_drain, please fix it also. 
This one is not in our versal-mgmt.c yet, but will be in soon.

2023-06-06 19:58 UTC, xdavidz approved these changes

2023-06-07 18:01 UTC, dayeh-xilinx commented
retest this please.

2023-06-07 20:13 UTC, gbuildx commented
Build Passed!

2023-06-07 20:42 UTC, merged