VITIS-9224 Xbutil Enhancements for Power Management
Xilinx/XRT pull request #7682
Opened 2023-08-29 19:43 UTC by AShivangi

#### Problem solved by the commit
Plumbing for
- [VITIS-9561](https://jira.xilinx.com/browse/VITIS-9561) Set high, medium and low performance mode
- [VITIS-9562](https://jira.xilinx.com/browse/VITIS-9562) Report current frequencies and performance mode

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
N/A
#### How problem was solved, alternative solutions (if any) and why they were rejected
Created a new subcommand to set performance and display which mode it is in platform report

#### Risks (if any) associated the changes in the commit
None

#### What has been tested and how, request additional testing if necessary
Tested with simulated values:
```
$ xbutil examine -d b3:00 -r platform
***********************************************************
*        WARNING          WARNING          WARNING        *
*       SC version data missing. Upgrade your shell       *
***********************************************************

---------------------------------------------------
[0000:b3:00.1] : xilinx_vck5000_gen4x8_qdma_base_2
---------------------------------------------------
Platform
  XSA Name               : xilinx_vck5000_gen4x8_qdma_base_2 
  Logic UUID             : 05DCA096-76CB-730B-8D19-EC1192FBAE3F 
  FPGA Name              :  
  JTAG ID Code           : 0x0 
  DDR Size               : 0 Bytes
  DDR Count              : 0 
  Revision               : 1 
  MFG Date               : 0xcee875 
  Mig Calibrated         : false 
  P2P Status             : not supported 
  Performance Mode       : DEFAULT 

Clocks
  DATA_CLK (Data)        : 300 MHz
  KERNEL_CLK (Kernel)    : 500 MHz

Mac Addresses            : 00:0A:35:0D:55:8E
                         : 00:0A:35:0D:55:8F
```
```
$ xbutil configure --performance -d b3:00 low

Performance mode is set to low 

```

Negative test:
```$ xbutil configure --performance -d b3:00 lo
ERROR: Invalid action value: 'lo'

COMMAND: configure

DESCRIPTION: Change performance mode of the device

USAGE:  configure --performance [--help] [-d arg] action

OPTIONS:
  --performance      - Change performance mode of the device
  -d, --device       - The Bus:Device.Function (e.g., 0000:d8:00.0) device of interest
  --help             - Help to use this sub-command

ERROR: : Operation canceled
```

#### Documentation impact (if any)
Added the new command usage to github.io

2023-08-29 22:18 UTC, uday610 commented on src/runtime_src/doc/toc/xbutil.rst
> +    - ``medium``: Set performance mode to high
``high`` :

2023-08-29 22:18 UTC, uday610 requested changes

2023-08-29 22:18 UTC, uday610 commented on src/runtime_src/doc/toc/xbutil.rst
> +    - ``medium``: Set performance mode to default
default

2023-08-29 22:22 UTC, gbuildx commented
Build Passed!

2023-08-30 16:03 UTC, chvamshi-xilinx approved these changes
Looks good.

2023-08-30 16:26 UTC, AShivangi commented on src/runtime_src/doc/toc/xbutil.rst
> +    - ``medium``: Set performance mode to high
fixed

2023-08-30 16:26 UTC, AShivangi commented on src/runtime_src/doc/toc/xbutil.rst
> +    - ``medium``: Set performance mode to default
fixed

2023-08-30 19:51 UTC, gbuildx commented
Build Passed!

2023-08-31 16:05 UTC, merged