emconfig.json path issue if host code is in python.
Xilinx/XRT pull request #7687
Opened 2023-09-05 06:34 UTC by sgundime-xilinx

Fix:  emconfig.json file path is wrongly deduced with getSelfPath API especially if host code is python script. The current fix ensures the proper current path is chosen if the exe name contains /usr/*/python in it.

Risk: very low

Tests: Canary Run. Results are Clean.

Reviewer: venkatp

2023-09-05 07:56 UTC, gbuildx commented
Build failed :(

2023-09-05 17:51 UTC, chvamshi-xilinx requested changes
Hi @sgundime-xilinx ,
It is better to check the emconfig.json file in the executable path first. If we dont find it there, check in current working directory. We shouldn't be adding special checks for python etc.

2023-09-05 17:57 UTC, dayeh-xilinx commented
retest this please.

2023-09-05 22:09 UTC, gbuildx commented
Build failed :(

2023-09-06 14:41 UTC, chvamshi-xilinx approved these changes

2023-09-06 15:24 UTC, venkatp-xilinx approved these changes

2023-09-06 17:17 UTC, gbuildx commented
Build Passed!

2023-09-07 12:31 UTC, merged