Use write buffer for AIE Profile, AIE Debug Plugins in Client Device
Xilinx/XRT pull request #7757
Opened 2023-10-19 02:07 UTC by IshitaGhosh

#### Problem solved by the commit
Client Devices now provide a write buffer only which can be synced from device. So, AIE Profile and AIE Debug Plugins now use last 1K section of that buffer for result. The first 3Kbytes are used by ML Timeline.
Also, ML Timeline Plugin result buffer now has total number of entries in the first 32 bits. Update reading of result accordingly.

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered

#### How problem was solved, alternative solutions (if any) and why they were rejected

#### Risks (if any) associated the changes in the commit

#### What has been tested and how, request additional testing if necessary

#### Documentation impact (if any)

2023-10-19 04:15 UTC, gbuildx commented
Build Passed!

2023-10-19 14:46 UTC, stsoe requested changes

2023-10-19 14:46 UTC, stsoe commented on src/runtime_src/xdp/profile/plugin/aie_debug/aie_debug_plugin.cpp
> +    static constexpr uint32_t OFFSET_3K = 0x0C00;
lower case variable names, please.  Else you run the risk of preprocessor interfering when some obscure code out of your control defines these relatively common names.

2023-10-19 14:46 UTC, stsoe commented on src/runtime_src/xdp/profile/plugin/aie_profile/win/aie_profile.cpp
> +    static constexpr uint32_t OFFSET_3K = 0x0C00;
Ditto

2023-10-19 18:53 UTC, gbuildx commented
Build Passed!

2023-10-20 16:19 UTC, hackwa approved these changes

2023-10-20 18:25 UTC, stsoe approved these changes

2023-10-20 20:20 UTC, merged