Fix for CR-1178694: Kernel Panic - Parallel XRT Kernels Run
Xilinx/XRT pull request #7761
Opened 2023-10-20 07:24 UTC by saumyag-xilinx

#### Problem solved by the commit
https://jira.xilinx.com/browse/CR-1178694
#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered

#### How problem was solved, alternative solutions (if any) and why they were rejected
Partition fd from AIE driver is same in multithread case which leads to kernel crash as a thread tries to close the fd which is already closed by another thread, added lock before registering aie to handle this case.
#### Risks (if any) associated the changes in the commit
Low
#### What has been tested and how, request additional testing if necessary
tested with a multithread application on vck190 
#### Documentation impact (if any)
NA

2023-10-20 09:33 UTC, gbuildx commented
Build Passed!

2023-10-20 09:40 UTC, chvamshi-xilinx approved these changes

2023-10-20 14:21 UTC, stsoe requested changes

2023-10-20 14:21 UTC, stsoe commented on src/runtime_src/core/edge/user/shim.cpp
>    aieArray = std::make_unique<zynqaie::Aie>(mCoreDevice);
```suggestion
  std::lock_guard guard(registerAieLock);
  aieArray = std::make_unique<zynqaie::Aie>(mCoreDevice);
```

2023-10-24 09:45 UTC, gbuildx commented
Build Passed!

2023-10-26 15:13 UTC, stsoe commented on src/runtime_src/core/edge/user/shim.cpp
>    delete aieArray.release();
Why?   The point of smart pointers if that we don't write new and delete.

2023-11-11 15:29 UTC, chvamshi-xilinx commented
Hi @saumyag-xilinx , 
Looks like this is still not working for multiple devices. Lets have a generic fix. Closing this for now

2023-11-11 15:29 UTC, closed without merging