Fixing XRT compilation Issue on Ubuntu 23.10 (issue #7806)
Xilinx/XRT pull request #7834
Opened 2023-12-06 20:40 UTC by haghilin

Problem solved by the commit:
There was compilation issues on Ubuntu 23.10 which was reported in issue #7806.

Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
issue #7806

How problem was solved, alternative solutions (if any) and why they were rejected
Risks (if any) associated the changes in the commit
What has been tested and how, request additional testing if necessary

2023-12-06 20:54 UTC, keryell commented
Just curious, why has it been closed?
I was so happy you solved my issue! :-)

2023-12-06 20:57 UTC, haghilin commented
Hi Keryell,

Yeah, sorry by mistake I added 5 files without change to the commit so was trying to remove them from the PR. Will create the PR again shortly. :)

Thanks

2023-12-06 20:59 UTC, keryell commented
You can just reopen the PR and just force-push again onto the same branch instead.

2023-12-06 21:13 UTC, haghilin commented
Thanks Keryell,

for the help. I reverted the commit. It is now available for review.

2023-12-06 21:30 UTC, keryell commented on src/runtime_src/core/common/api/xrt_kernel.cpp
> +#pragma GCC diagnostic ignored "-Woverloaded-virtual"
Would it be possible to fix the root cause instead of make the compiler blind?

2023-12-06 22:56 UTC, gbuildx commented
Build failed :(

2023-12-06 23:01 UTC, stsoe requested changes
Thank you.   Let's not disable the warning in header files, targeted few .cpp is okay.  Else pragma push/pop.

2023-12-06 23:01 UTC, stsoe commented on src/runtime_src/core/common/system.h
> +#endif
Not in header file, that disables for all compilation units that end up including this file.

2023-12-06 23:01 UTC, stsoe commented on src/runtime_src/xdp/profile/database/dynamic_info/aie_db.h
> +#endif
Ditto.

2023-12-06 23:01 UTC, stsoe commented on src/runtime_src/xdp/profile/database/dynamic_info/host_db.h
> +#endif
Ditto

2023-12-08 16:59 UTC, haghilin commented
This PR cannot be built due to long branch name. I created another PR https://github.com/Xilinx/XRT/pull/7841.
Thanks.

2023-12-08 16:59 UTC, closed without merging