Add missing apt-get update to have an up-to-date package list
Xilinx/XRT pull request #7836
Opened 2023-12-06 22:07 UTC by keryell

Also remove random TAB and spaces.
This file would require a serious beautifier.

2023-12-06 22:08 UTC, gbuildx commented
Can one of the admins verify this patch?

2023-12-06 22:52 UTC, stsoe requested changes

2023-12-06 22:52 UTC, stsoe commented on src/runtime_src/tools/scripts/xrtdeps.sh
> +#!/bin/bash -vx
Really?

2023-12-06 22:52 UTC, stsoe commented
@keryell Please `git commit -s --amend --no-edit`

2023-12-06 22:54 UTC, keryell commented on src/runtime_src/tools/scripts/xrtdeps.sh
> +#!/bin/bash -vx
Ouch, I pushed my debug code. :-(

2023-12-07 01:51 UTC, stsoe commented
> Actually in Emacs/magit I just need to press 'r' and 'm'. I tend to forget about all the git CLI...

I was implying you need to sign your PR.

2023-12-07 15:28 UTC, keryell commented
> > @keryell Please `git commit -s --amend --no-edit`
> 
> Actually in Emacs/magit I just need to press 'r' and 'm'. I tend to forget about all the git CLI...

Oh, this is a new policy? By signing I guess this is just adding my e-mail, no cryptographic signature?

2023-12-12 16:26 UTC, stsoe commented
ok to test

2023-12-12 16:26 UTC, stsoe commented
add to whitelist

2023-12-12 19:46 UTC, gbuildx commented
Build Passed!

2023-12-12 19:50 UTC, merged