Fixing XRT issue for Ubuntu 23.10
Xilinx/XRT pull request #7841
Opened 2023-12-08 16:58 UTC by haghilin

Problem solved by the commit:
There was compilation issues on Ubuntu 23.10 which was reported in issue https://github.com/Xilinx/XRT/issues/7806.

Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
issue https://github.com/Xilinx/XRT/issues/7806

How problem was solved, alternative solutions (if any) and why they were rejected
Risks (if any) associated the changes in the commit
What has been tested and how, request additional testing if necessary

2023-12-08 17:06 UTC, haghilin commented
Hi @keryell,
Thanks for the comment. I could also replicate the issue during the test on my side. We will work on fixing "dpkg-shlibdeps: error". I guess at the moment build is fine.

Thanks for reporting the issue

2023-12-08 18:52 UTC, stsoe requested changes

2023-12-08 18:52 UTC, stsoe commented on src/runtime_src/core/pcie/emulation/sw_emu/generic_pcie_hal2/system_swemu.h
> +  program_plp(const device* dev, const std::vector<char> &buffer, bool) const;
```suggestion
  program_plp(const device* dev, const std::vector<char> &buffer, bool) const override;
```

2023-12-08 20:45 UTC, gbuildx commented
Build failed :(

2023-12-08 21:20 UTC, haghilin commented
retest this please!

2023-12-08 21:36 UTC, stsoe approved these changes
Thank you!

2023-12-09 00:25 UTC, gbuildx commented
Build failed :(

2023-12-09 00:28 UTC, keryell approved these changes
Thanks. The compilation is good now.
Just remaining https://github.com/Xilinx/XRT/issues/7806#issuecomment-1848002001

2023-12-11 15:46 UTC, haghilin commented
retest this please!

2023-12-11 19:14 UTC, gbuildx commented
Build failed :(

2023-12-12 04:52 UTC, stsoe commented
retest this please

2023-12-12 08:01 UTC, gbuildx commented
Build failed :(

2023-12-12 14:05 UTC, haghilin commented
retest this please

2023-12-12 16:28 UTC, chvamshi-xilinx approved these changes

2023-12-12 17:51 UTC, keryell commented
I have just tried and I still have
```
CMake Error at /usr/share/cmake-3.27/Modules/Internal/CPack/CPackDeb.cmake:348 (message):
  CPackDeb: dpkg-shlibdeps: 'dpkg-shlibdeps: error: no dependency information
  found for opt/xilinx/xrt/lib/libxdp_core.so.2 (used by
  ./opt/xilinx/xrt/lib/xrt/module/libxdp_hw_emu_pl_deadlock_plugin.so)

  Hint: check if the library actually comes from a package.

  ';

  executed command: '/usr/bin/dpkg-shlibdeps -O
  ./opt/xilinx/xrt/bin/mpd;./opt/xilinx/xrt/bin/msd;./opt/xilinx/xrt/bin/unwrapped/xbmgmt2;./opt/xilinx/xrt/bin/unwrapped/xbutil2;./opt/xilinx/xrt/bin/unwrapped/xclbinutil;./opt/xilinx/xrt/bin/xbflash.qspi;./opt/xilinx/xrt/lib/libsched_em.so.2.17.0;./opt/xilinx/xrt/lib/libsched_em_v30.so.2.17.0;./opt/xilinx/xrt/lib/libxdp_core.so.2.17.0;./opt/xilinx/xrt/lib/libxilinxopencl.so.2.17.0;./opt/xilinx/xrt/lib/libxma2api.so.2.17.0;./opt/xilinx/xrt/lib/libxma2plugin.so.2.17.0;./opt/xilinx/xrt/lib/libxrt++.so.2.17.0;./opt/xilinx/xrt/lib/libxrt_core.so.2.17.0;./opt/xilinx/xrt/lib/libxrt_coreutil.so.2.17.0;./opt/xilinx/xrt/lib/libxrt_hwemu.so.2.17.0;./opt/xilinx/xrt/lib/libxrt_noop.so.2.17.0;./opt/xilinx/xrt/lib/libxrt_swemu.so.2.17.0;./opt/xilinx/xrt/lib/xrt/module/libxdp_aie_profile_plugin.so;./opt/xilinx/xrt/lib/xrt/module/libxdp_aie_trace_plugin.so;./opt/xilinx/xrt/lib/xrt/module/libxdp_appdebug_plugin.so;./opt/xilinx/xrt/lib/xrt/module/libxdp_debug_plugin.so;./opt/xilinx/xrt/lib/xrt/module/libxdp_device_offload_plugin.so;./opt/xilinx/xrt/lib/xrt/module/libxdp_hal_api_interface_plugin.so;./opt/xilinx/xrt/lib/xrt/module/libxdp_hal_device_offload_plugin.so;./opt/xilinx/xrt/lib/xrt/module/libxdp_hal_plugin.so;./opt/xilinx/xrt/lib/xrt/module/libxdp_hw_emu_device_offload_plugin.so;./opt/xilinx/xrt/lib/xrt/module/libxdp_hw_emu_pl_deadlock_plugin.so;./opt/xilinx/xrt/lib/xrt/module/libxdp_lop_plugin.so;./opt/xilinx/xrt/lib/xrt/module/libxdp_native_plugin.so;./opt/xilinx/xrt/lib/xrt/module/libxdp_noc_plugin.so;./opt/xilinx/xrt/lib/xrt/module/libxdp_opencl_counters_plugin.so;./opt/xilinx/xrt/lib/xrt/module/libxdp_opencl_trace_plugin.so;./opt/xilinx/xrt/lib/xrt/module/libxdp_pl_deadlock_plugin.so;./opt/xilinx/xrt/lib/xrt/module/libxdp_power_plugin.so;./opt/xilinx/xrt/lib/xrt/module/libxdp_system_compiler_plugin.so;./opt/xilinx/xrt/lib/xrt/module/libxdp_user_plugin.so;./opt/xilinx/xrt/lib/xrt/module/libxdp_vart_plugin.so;./opt/xilinx/xrt/python/pyxrt.cpython-311-x86_64-linux-gnu.so';
```
@mamin506 suggested me it might be in @jvillarre backyard.

2023-12-12 23:08 UTC, gbuildx commented
Build failed :(

2023-12-13 04:45 UTC, dayeh-xilinx commented
retest this please

2023-12-13 07:52 UTC, gbuildx commented
Build failed :(

2023-12-13 17:25 UTC, gbuildx commented
Build Passed!

2023-12-14 15:57 UTC, merged

2024-04-22 02:13 UTC, dirksavage88 commented
Could this fix be backported to 2022.x?

2024-04-22 12:45 UTC, keryell commented
> Could this fix be backported to 2022.x?

You would probably need some other PR too. Is there an issue about using the latest XRT?

2024-04-22 17:35 UTC, keryell commented
I was unclear. My question is : does the latest XRT works for you?
It should work up to 6.8 kernel. I run Ubuntu 23.10 and Linux 6.8.7.
Do you really need an obsolete XRT for some reason?

2024-04-22 18:34 UTC, dirksavage88 commented
master fails with this error: 
`/usr/bin/ld: cannot find -ludev: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [runtime_src/core/pcie/tools/cloud-daemon/CMakeFiles/mpd.dir/build.make:148: runtime_src/core/pcie/tools/cloud-daemon/mpd] Error 1
make[1]: *** [CMakeFiles/Makefile2:2591: runtime_src/core/pcie/tools/cloud-daemon/CMakeFiles/mpd.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
`

I am following the docs that say to use XRT version that matches the Vitis version (of which I am using Vitis 2022.1)

2024-04-23 18:29 UTC, keryell commented
Usually recent XRT works with older Vitis. But you could give a try to Vitis 2023.2. :-)
https://github.com/Xilinx/XRT/blob/master/src/runtime_src/doc/toc/build.rst mentions https://github.com/Xilinx/XRT/blob/master/src/runtime_src/tools/scripts/xrtdeps.sh which installs a lot of requirement, including the `libudev-dev` package which seems to be missing on your system.