P1 - Initial changes for removal of xcl apis
Xilinx/XRT pull request #7860
Opened 2023-12-20 06:41 UTC by rbramand-xilinx

#### Problem solved by the commit
This commit adds new queries which will be used in XDP code base. XDP code will be moved from using xcl apis to query calls to fetch information. Confluence page capturing this work - https://confluence.xilinx.com/display/XSW/Vitis-9976+Work 

This change is part of series of changes which aim to remove release of xcl apis

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered

#### How problem was solved, alternative solutions (if any) and why they were rejected
New queries are added, XDP code will now link to xrt_coreutil which will be platform independent

#### Risks (if any) associated the changes in the commit
Low

#### What has been tested and how, request additional testing if necessary
Tested build flows (PCIE - Linux/Windows, Edge)
After XDP code adds these queries they will do functionality test with their test cases

#### Documentation impact (if any)
NA

2023-12-20 08:09 UTC, gbuildx commented
Build failed :(

2023-12-20 11:28 UTC, gbuildx commented
Build Passed!

2023-12-20 16:27 UTC, stsoe requested changes
@rajkumar-xilinx , please fix the mixed case structs.
I started adding changes for a few, but it's easier you sweep through and fix them.

2023-12-20 16:27 UTC, stsoe commented on src/runtime_src/core/edge/user/device_linux.cpp
> +struct device_clock_freq_MHz {
No CamelCase
```suggestion
struct device_clock_freq_mhz {
```

2023-12-20 16:27 UTC, stsoe commented on src/runtime_src/core/edge/user/device_linux.cpp
> +  emplace_func0_request<query::device_clock_freq_MHz,   device_clock_freq_MHz>();
```suggestion
  emplace_func0_request<query::device_clock_freq_mhz,   device_clock_freq_mhz>();
```

2023-12-21 04:43 UTC, IshitaGhosh approved these changes
Changes look good. When the PR is merged, Parth will use the new device query method in XDP and verify on local tests.

2023-12-21 10:09 UTC, rajkumar-xilinx commented
> @rajkumar-xilinx , please fix the mixed case structs. I started adding changes for a few, but it's easier you sweep through and fix them.

Sure

2023-12-22 09:36 UTC, gbuildx commented
Build Passed!

2023-12-22 10:07 UTC, chvamshi-xilinx approved these changes

2023-12-28 15:49 UTC, stsoe approved these changes
Thank you.

2023-12-28 15:49 UTC, merged