Create common utilities folder for XDP plugins that use the AIE driver
Xilinx/XRT pull request #7866
Opened 2023-12-28 02:14 UTC by nishraptor

#### Problem solved by the commit
Create common utilities folder for XDP plugins that use the AIE driver, including handling functions that are shared between profile/edge that use AIE driver enums and functions, as well as handling client transactions.

This PR is an initial attempt at this common utility folder, and any name changes or architectural suggestions would be welcome. For now, I have created a new folder called common in the plugin directory that is only used in the client implementation of each plugin.

#### What has been tested and how, request additional testing if necessary
Tested on client devices. 

#### Documentation impact (if any)

2023-12-28 05:05 UTC, gbuildx commented
Build Passed!

2024-01-12 06:24 UTC, gbuildx commented
Build Passed!

2024-01-12 21:34 UTC, gbuildx commented
Build failed :(

2024-01-16 00:07 UTC, stsoe commented
Please rebase.  Your PR contains changes that have been merged already.

2024-01-16 00:07 UTC, stsoe requested changes
Per comment, please rebase

2024-01-16 01:42 UTC, gbuildx commented
Build failed :(

2024-01-16 21:44 UTC, gbuildx commented
Build Passed!

2024-01-17 19:28 UTC, nishraptor commented
@stsoe I rebased and fixed the commit history.

2024-01-17 21:19 UTC, jvillarre approved these changes

2024-01-18 19:53 UTC, merged