Initial HIP binding build support using headers from standard HIP install
Xilinx/XRT pull request #7867
Opened 2023-12-31 07:32 UTC by sonals

#### Problem solved by the commit
Use standard HIP install for HIP runtime header files

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
HIP binding build support

#### How problem was solved, alternative solutions (if any) and why they were rejected
Install HIP in xrtdeps.h and then leverage hipconfig utility to find HIP include directories 

#### Risks (if any) associated the changes in the commit
None; only enabled when build is run with -hip switch and is limited to Linux

#### What has been tested and how, request additional testing if necessary
Compile tested on Ubuntu 23.10

#### Documentation impact (if any)
None

2023-12-31 07:40 UTC, gbuildx commented
Build failed :(

2023-12-31 15:05 UTC, sonals commented
retest this please

2023-12-31 15:10 UTC, gbuildx commented
Build failed :(

2023-12-31 19:11 UTC, stsoe requested changes
Many style comments.   This will be monkey-see-monkey-do, do we really want that? Or should we spend the time formatting this newly added code to perfection (whatever perfection is)?

2023-12-31 19:11 UTC, stsoe commented on tests/hip/vadd/VectorAdd/common.h
> +    }
Avoid constructor body for simple initializations.  Re-factor
```suggestion
    hip_device(int index = 0) 
      : m_index{index}
      , m_device{hip_check(hip_get_device(m_index)}
    {}
```
With 
```
static hipDevice_t
hip_get_device(int index)
{
  hipDevice_t device;
  hip_check(hipGetDevice(&device, index));
  return devlce;
}
```

2023-12-31 19:11 UTC, stsoe commented on tests/hip/vadd/VectorAdd/common.h
> +    int mIndex;
Swap
```suggestion
  int m_index;
  hipDevice_t m_device;
```

2023-12-31 19:11 UTC, stsoe commented on tests/hip/vadd/VectorAdd/common.h
> +    virtual ~HipDevice() {
Why virtual?

2024-01-02 19:07 UTC, dayeh-xilinx commented
retest this please.

2024-01-02 19:20 UTC, gbuildx commented
Build failed :(

2024-01-02 21:16 UTC, dayeh-xilinx commented
retest this please.

2024-01-03 00:14 UTC, gbuildx commented
Build failed :(

2024-01-03 04:45 UTC, dayeh-xilinx commented
retest this please.

2024-01-03 05:02 UTC, sonals commented on tests/hip/vadd/VectorAdd/main-stream.cpp
> +static const int LOOP = 1000;
Updated to use constexpr and lowercase

2024-01-03 05:03 UTC, sonals commented on tests/hip/vadd/VectorAdd/common.h
> +#include <boost/uuid/uuid_io.hpp>
Using boost essentially for OS independent way to print UUID to ostream. Does XRT UUID support printing?

2024-01-03 05:04 UTC, sonals commented on tests/hip/vadd/VectorAdd/common.h
> +class HIPError : public std::system_error
Updated to match the coding style.

2024-01-03 05:04 UTC, sonals commented on tests/hip/vadd/VectorAdd/main-stream.cpp
> +#include <boost/uuid/uuid_io.hpp>
Obsoleted this file

2024-01-03 05:05 UTC, sonals commented on tests/hip/vadd/VectorAdd/main-stream.cpp
> +/* Based on https://github.com/ROCm-Developer-Tools/HIP-Examples/tree/master/vectorAdd */
Obsoleted this file. Updated main.cpp to match the style suggested.

2024-01-03 05:05 UTC, sonals commented on tests/hip/vadd/VectorAdd/common.h
> +/* Copyright (C) 2023 Advanced Micro Devices, Inc. */
Updated to match the style suggested.

2024-01-03 05:05 UTC, sonals commented on tests/hip/vadd/VectorAdd/Makefile
> +# Copyright (C) 2022-2023 Advanced Micro Devices, Inc. #
Obsoleted this file.

2024-01-03 05:06 UTC, sonals commented on tests/hip/vadd/VectorAdd/common.h
> +    int mIndex;
Updated to match the coding style.

2024-01-03 05:06 UTC, sonals commented on tests/hip/vadd/VectorAdd/common.h
> +    virtual ~HipDevice() {
Removed

2024-01-03 07:55 UTC, gbuildx commented
Build failed :(

2024-01-03 16:46 UTC, sonals commented
retest this please

2024-01-03 18:37 UTC, gbuildx commented
Build failed :(

2024-01-03 18:50 UTC, sonals commented on tests/hip/vadd/VectorAdd/common.h
> +#include <boost/uuid/uuid_io.hpp>
Dropped boost completely and copied code from XRT uuid.h for printing.

2024-01-03 21:07 UTC, stsoe approved these changes
Looks good.   So by default hip will only be supported on Ubuntu 23+ or fedora > 38, not of which are built by CI?  And anyway hip build has to be enabled explicitly through build switch, so  assume this is all good enough for now.

2024-01-03 22:21 UTC, gbuildx commented
Build Passed!

2024-01-03 23:06 UTC, merged

2024-01-08 16:04 UTC, keryell commented on tests/hip/vadd/main.cpp
> +  std::unique_ptr<float[]> host_a(new float[vector_length]);
Why not just `std::vector`?