VITIS-11043 Refactor XRT to cache created devices
Xilinx/XRT pull request #7870
Opened 2024-01-04 00:59 UTC by dbenusov

#### Problem solved by the commit
https://jira.xilinx.com/browse/VITIS-11043
Each time XRT creates a device reference a new device wrapper is created. This is not correct, only one device should be created and that referenced cached.

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
Prevent XRT from constantly creating new xrt_core::device handles.

#### How problem was solved, alternative solutions (if any) and why they were rejected
Fixed by intercepting the create device call and storing the returned shared pointer. If a request is made for the same device id, the original referenced is returned.

#### Risks (if any) associated the changes in the commit
None. Should be an improvement in performance hopefully :) 

#### What has been tested and how, request additional testing if necessary
Ubuntu 22.04 U55c
```
dbenusov@xsjdbenusov50:/proj/rdi/staff/dbenusov$ xbutil examine -d -r electrical
WARNING: Unexpected xocl version (2.16.0) was found. Expected 2.17.0, to match XRT tools.

-------------------------------------------------
[0000:04:00.1] : xilinx_u55c_gen3x16_xdma_base_3
-------------------------------------------------
Electrical
  Max Power              : 225 Watts
  Power                  : 21.445936 Watts
  Power Warning          : false

  Power Rails            :   Voltage  Current
  ---------------------------------------------
  12 Volts Auxillary     :  12.256 V  0.481 A
  12 Volts PCI Express   :  12.240 V  0.985 A
  3.3 Volts PCI Express  :   3.360 V  1.040 A
  3.3 Volts Auxillary    :   0.000 V  0.000 A
  Internal FPGA Vcc      :   0.852 V  6.100 A
  Internal FPGA Vcc IO   :   0.854 V  3.800 A
  DDR Vpp Bottom         :   0.000 V  0.000 A
  DDR Vpp Top            :   0.000 V  0.000 A
  5.5 Volts System       :   5.006 V  0.000 A
  Vcc 1.2 Volts Top      :   0.000 V  0.000 A
  Vcc 1.2 Volts Bottom   :   0.000 V  0.000 A
  1.8 Volts Top          :   1.813 V  0.000 A
  0.9 Volts Vcc          :   0.898 V  0.000 A
  12 Volts SW            :   0.000 V  0.000 A
  Mgt Vtt                :   1.200 V  0.000 A
  3.3 Volts Vcc          :   3.354 V  0.000 A
  1.2 Volts HBM          :   1.203 V  0.000 A
  Vpp 2.5 Volts          :   2.468 V  0.000 A
  12 Volts Aux1          :   0.000 V  0.000 A
  Vcc 1.2 Volts i        :   0.000 V  0.000 A
  V12 in i               :   0.000 V  0.000 A
  V12 in Aux0 i          :   0.000 V  0.000 A
  V12 in Aux1 i          :   0.000 V  0.000 A
  Vcc Auxillary          :   0.000 V  0.000 A
  Vcc Auxillary Pmc      :   0.000 V  0.000 A
  Vcc Ram                :   0.000 V  0.000 A
  0.9 Volts Vcc Vcu      :   0.000 V  0.000 A
```

#### Documentation impact (if any)
None

2024-01-04 02:44 UTC, gbuildx commented
Build failed :(

2024-01-04 22:12 UTC, gbuildx commented
Build failed :(

2024-01-06 00:45 UTC, gbuildx commented
Build Passed!

2024-01-06 00:55 UTC, stsoe requested changes
Suggestion

2024-01-06 00:55 UTC, stsoe commented on src/runtime_src/core/tools/common/XBUtilities.cpp
> +
Is std::unordered_map a bit of an overkill here ?  And the function is not thread safe, is that okay, else protect with static mutex at first line followed by lock_guard.
How about
```suggestion
static std::shared_ptr<xrt_core::device>
get_device_internal(int index, bool in_user_domain)
{
  static std::mutex mutex;
  std::lock_guard lk(mutex);
  
  if (in_user_domain) {
    static std::vector<std::shared_ptr<xrt_core::device>> user_device_map { xrt_core::get_total_devices(true /*user/*) };
    auto& device = user_device_map.at(index);
    if (!device)
     device = xrt_core::get_userpf_device(index);

    return device;
  }

  static std::vector<std::shared_ptr<xrt_core::device>> mgmt_device_map { xrt_core::get_total_devices(false /*mgmt*/) };
  auto& device = mgmt_device_map.at(index);
  if (!device)
    device = xrt_core::get_mgmtpf_device(index));

  return device;
}

```

2024-01-08 22:17 UTC, gbuildx commented
Build Passed!

2024-01-08 23:24 UTC, stsoe approved these changes

2024-01-08 23:28 UTC, stsoe reviewed
Thank you for removing the xrt:;device::get_info calls.

2024-01-09 12:27 UTC, chvamshi-xilinx approved these changes

2024-01-09 12:27 UTC, merged