VITIS-11275 Add support for telemetry report in XRT core
Xilinx/XRT pull request #7921
Opened 2024-01-31 23:06 UTC by dbenusov-xilinx

#### Problem solved by the commit
https://jira.xilinx.com/browse/VITIS-11275

Add Telemetry report for future RyzenAI needs.

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
New feature!

#### How problem was solved, alternative solutions (if any) and why they were rejected
Create the required output report, parsing logic, and query requests to display the needed data.

#### Risks (if any) associated the changes in the commit
None.

#### What has been tested and how, request additional testing if necessary
Tested on Windows VM Simulated IPU

All displayed values are simulated and not from the actual firmware.

Report Output
```
Z:\XRT-MCDM\build\WDebug\xilinx\xrt>xbutil examine -d -r telemetry -o test.json --force
------------------------------------------------------------
                        EARLY ACCESS
        This release of xbutil contains early access
         experimental features which may have bugs.
------------------------------------------------------------

---------------------------------
[0000:18:00.1] : RyzenAI-Phoenix
---------------------------------
Telemetry
  L1 Interrupt Count     : 1234

  RTOS Task  Starts  Schedules  Syscalls  DMA Accesses  Resource Acquisitions
  -----------------------------------------------------------------------------
  0          0       3          6         9             12
  1          1       4          7         10            13
  2          2       5          8         11            14

  RTOS DTLBs
  RTOS Task  Region 0 Misses  Region 1 Misses  Region 2 Misses
  --------------------------------------------------------------
  0          0                1                2
  1          3                4                5
  2          6                7                8

  Opcode  Receive Count
  -----------------------
  0       0
  1       1
  2       2
  3       3

  Stream Buffer  Tokens
  -----------------------
  0              0
  1              1

  AIE Column  Deep Sleep Count
  ------------------------------
  0           0
  1           1
  2           2
  3           3
  4           4

Successfully wrote the json file: test.json
```
JSON Output
```
{
    "schema_version": {
        "schema": "JSON",
        "creation_date": "Wed Jan 31 22:51:26 2024 GMT"
    },
    "devices": [
        {
            "interface_type": "pcie",
            "device_id": "0000:18:00.1",
            "device_status": "HEALTHY",
            "telemetry": {
                "level_one_interrupt_count": "1234",
                "rtos_tasks": [
                    {
                        "started_count": "0",
                        "scheduled_count": "3",
                        "syscall_count": "6",
                        "dma_access_count": "9",
                        "resource_acquisition_count": "12",
                        "dtlb_data": [
                            {
                                "dtlb_misses": "0"
                            },
                            {
                                "dtlb_misses": "1"
                            },
                            {
                                "dtlb_misses": "2"
                            }
                        ]
                    },
                    {
                        "started_count": "1",
                        "scheduled_count": "4",
                        "syscall_count": "7",
                        "dma_access_count": "10",
                        "resource_acquisition_count": "13",
                        "dtlb_data": [
                            {
                                "dtlb_misses": "3"
                            },
                            {
                                "dtlb_misses": "4"
                            },
                            {
                                "dtlb_misses": "5"
                            }
                        ]
                    },
                    {
                        "started_count": "2",
                        "scheduled_count": "5",
                        "syscall_count": "8",
                        "dma_access_count": "11",
                        "resource_acquisition_count": "14",
                        "dtlb_data": [
                            {
                                "dtlb_misses": "6"
                            },
                            {
                                "dtlb_misses": "7"
                            },
                            {
                                "dtlb_misses": "8"
                            }
                        ]
                    }
                ],
                "opcodes": [
                    {
                        "received_count": "0"
                    },
                    {
                        "received_count": "1"
                    },
                    {
                        "received_count": "2"
                    },
                    {
                        "received_count": "3"
                    }
                ],
                "stream_buffers": [
                    {
                        "tokens": "0"
                    },
                    {
                        "tokens": "1"
                    }
                ],
                "aie_columns": [
                    {
                        "deep_sleep_count": "0"
                    },
                    {
                        "deep_sleep_count": "1"
                    },
                    {
                        "deep_sleep_count": "2"
                    },
                    {
                        "deep_sleep_count": "3"
                    },
                    {
                        "deep_sleep_count": "4"
                    }
                ]
            }
        }
    ]
}
```

#### Documentation impact (if any)
Need to add new report to documentation list for AIE.

2024-01-31 23:36 UTC, stsoe requested changes
Looks good.  Few suggestions.

2024-01-31 23:36 UTC, stsoe commented on src/runtime_src/core/common/query_requests.h
> +    std::vector<struct dtlb_data> dtlbs;
```suggestion
    std::vector<dtlb_data> dtlbs;
```

2024-01-31 23:36 UTC, stsoe commented on src/runtime_src/core/common/query_requests.h
> +  using result_type = std::vector<struct data>;
```suggestion
  using result_type = std::vector<data>;
```

2024-01-31 23:36 UTC, stsoe commented on src/runtime_src/core/common/query_requests.h
> +  using result_type = std::vector<struct data>;
```suggestion
  using result_type = std::vector<data>;
```

2024-01-31 23:36 UTC, stsoe commented on src/runtime_src/core/common/query_requests.h
> +  using result_type = std::vector<struct data>;
```suggestion
  using result_type = std::vector<data>;
```

2024-01-31 23:36 UTC, stsoe commented on src/runtime_src/core/common/query_requests.h
> +  using result_type = struct data;
```suggestion
  using result_type = data;
```

2024-01-31 23:36 UTC, stsoe commented on src/runtime_src/core/common/query_requests.h
> +  using result_type = std::vector<struct data>;
```suggestion
  using result_type = std::vector<data>;
```

2024-01-31 23:36 UTC, stsoe commented on src/runtime_src/core/tools/common/reports/ReportTelemetry.cpp
> +#include <map>
Is std::map used?
```suggestion
```

2024-02-01 17:50 UTC, dbenusov-xilinx commented on src/runtime_src/core/tools/common/reports/ReportTelemetry.cpp
> +#include <map>
It is not! Good catch.

2024-02-01 18:30 UTC, stsoe approved these changes

2024-02-01 19:02 UTC, AShivangi approved these changes

2024-02-01 19:02 UTC, AShivangi commented on src/runtime_src/core/tools/common/reports/ReportTelemetry.cpp
> +  boost::property_tree::ptree telemetry_pt = pt.get_child("telemetry");
Just add the "info not available" but the rest looks good. Thanks for the comments in the query_requests!

2024-02-08 19:06 UTC, chvamshi-xilinx approved these changes

2024-02-08 19:06 UTC, merged