VITIS-8728 Update skd files to remove xcl apis
Xilinx/XRT pull request #7995
Opened 2024-03-08 10:31 UTC by rbramand-xilinx

#### Problem solved by the commit
Removed xcl apis from skd flow

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
#### How problem was solved, alternative solutions (if any) and why they were rejected

Conversion of xclBufferHandle to xrtBufferHandle is deprecated
So added internal shim function which converts buffer fd to buffer_handle
This way use of xcl buffer shim apis can be eliminated.

#### Risks (if any) associated the changes in the commit
Low

#### What has been tested and how, request additional testing if necessary
Tested pcie and edge  builds by hiding symbols exported by xrt.h header file

#### Documentation impact (if any)
NA

2024-03-10 14:08 UTC, stsoe approved these changes

2024-03-11 06:28 UTC, chvamshi-xilinx requested changes
Looks good. 
I dont see a change to link with xrt_coreutil instead of xrt_core.

2024-03-11 06:45 UTC, rbramand-xilinx commented
> Looks good. I dont see a change to link with xrt_coreutil instead of xrt_core.
We still have functions like xclGetHostBO, xclGetSKCmd which are from xrt_core so I haven't changed the linking part, I will create a CR which can be used for rewriting SKD code. At the time time of handling the CR I will create apis at xrt_coreutil level to replace these, then we can remove xrt_core linking.

2024-03-11 06:49 UTC, chvamshi-xilinx commented
> We still have functions like xclGetHostBO, xclGetSKCmd which are from xrt_core so I haven't changed the linking part, I will create a CR which can be used for rewriting SKD code. At the time time of handling the CR I will create apis at xrt_coreutil level to replace these, then we can remove xrt_core linking.

Ok. Thanks Rahul. Approving.

2024-03-11 06:49 UTC, chvamshi-xilinx approved these changes

2024-03-11 06:49 UTC, merged