HIP tests for GPU and other build improvements
Xilinx/XRT pull request #8008
Opened 2024-03-12 22:27 UTC by sonals

#### Problem solved by the commit

1. Provide a switch for disabling bundling of Alveo drivers with XRT package
2. Fix a build failure on Ubuntu 23.10
3. Add Makefiles for HIP tests to run then on AMD GPU

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
NA

#### How problem was solved, alternative solutions (if any) and why they were rejected
NA

#### Risks (if any) associated the changes in the commit
NA

#### What has been tested and how, request additional testing if necessary
Build tested

#### Documentation impact (if any)
NA

2024-03-12 23:07 UTC, maxzhen approved these changes
Assuming you have tested the produced package when driver is not bundled and it installs fine. Just wondering if anything needs changing in post install script.

2024-03-12 23:42 UTC, keryell commented
*Fix a build failure on Ubuntu 23.10*: I think I fixed this already with https://github.com/Xilinx/XRT/pull/8003

2024-03-13 02:48 UTC, sonals commented
> Assuming you have tested the produced package when driver is not bundled and it installs fine. Just wondering if anything needs changing in post install script.

Thanks for reminding, I overlooked the postinst script. Let me validate install/uninstall and update the PR.

2024-03-13 09:29 UTC, stsoe requested changes
Can you rebase please?  I think the xrt_graph.cpp change was from #8003 which has been merged.

2024-03-13 15:55 UTC, keryell commented on tests/hip/vadd-stream/Makefile.gpu
> +# Copyright (C) 2022-2023 Advanced Micro Devices, Inc. #
Happy new year everywhere! :-)

2024-03-14 22:34 UTC, sonals commented on tests/hip/vadd-stream/Makefile.gpu
> +# Copyright (C) 2022-2023 Advanced Micro Devices, Inc. #
Updated

2024-03-14 22:34 UTC, sonals commented
> Can you rebase please? I think the xrt_graph.cpp change was from #8003 which has been merged.

Done

2024-03-14 22:37 UTC, sonals commented
> > Assuming you have tested the produced package when driver is not bundled and it installs fine. Just wondering if anything needs changing in post install script.
> 
> Thanks for reminding, I overlooked the postinst script. Let me validate install/uninstall and update the PR.

Made updates to postinst script to skip Alveo steps. Install tested both artifacts.

2024-03-14 22:48 UTC, maxzhen commented
> > > Assuming you have tested the produced package when driver is not bundled and it installs fine. Just wondering if anything needs changing in post install script.
> > 
> > 
> > Thanks for reminding, I overlooked the postinst script. Let me validate install/uninstall and update the PR.
> 
> Made updates to postinst script to skip Alveo steps. Install tested both artifacts.

Looks good :-)

2024-03-16 08:22 UTC, chvamshi-xilinx approved these changes

2024-03-18 15:46 UTC, stsoe approved these changes

2024-03-18 16:00 UTC, merged