VITIS-11503 - Dump instruction bo created from Elf so verification can be done
Xilinx/XRT pull request #8043
Opened 2024-04-01 21:46 UTC by dezhiAmd

#### Problem solved by the commit
Create a mechanism to dump instruction-buffer BO(s) constructed from elf. This is critical to verify the elf's correctness. 
#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered

#### How problem was solved, alternative solutions (if any) and why they were rejected
Only in debug mode, Use the xrt_core::config::get_feature_toggle which reading xrt.ini to decide whether or not dumping instruction-buffer bo. This can avoid any potential performance impact to real applications.
#### Risks (if any) associated the changes in the commit
None
#### What has been tested and how, request additional testing if necessary

#### Documentation impact (if any)

2024-04-02 16:49 UTC, stsoe requested changes

2024-04-02 16:49 UTC, stsoe commented on src/runtime_src/core/common/api/xrt_module.cpp
> +          char* buf = static_cast<char*>(m_instr_buf.map());
```suggestion
          auto buf = m_instr_buf.map<char*>();
```

2024-04-02 16:49 UTC, stsoe commented on src/runtime_src/core/common/api/xrt_module.cpp
> +          ofs.write((char*)buf, m_instr_buf.size());
```suggestion
          ofs.write(buf, m_instr_buf.size());
```

2024-04-02 16:49 UTC, stsoe commented on src/runtime_src/core/common/api/xrt_module.cpp
> +          ofs.close();
```suggestion
```

2024-04-02 18:12 UTC, stsoe commented on src/runtime_src/core/common/api/xrt_module.cpp
> +      }
This appears to be a repeated code block from above; I didn't notice that before.  If so, please refactor in a separate function that take output filename and xrt::bo to dump.  E.g.
dump_bo(m_ctrl_buf, "ctrlpktbo.bin");

2024-04-02 22:20 UTC, stsoe commented on src/runtime_src/core/common/api/xrt_module.cpp
> +#endif
Move to global function under unnamed namespace within this compilation unit as there no need for state access.
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c4-make-a-function-a-member-only-if-it-needs-direct-access-to-the-representation-of-a-class

Remove the surrounding `#ifdef _DEBUG` from the function.  It is okay and good to protect the call from create_instr_buf as you are doing.

2024-04-02 23:41 UTC, stsoe approved these changes

2024-04-03 03:16 UTC, sonals commented on src/runtime_src/core/common/api/xrt_module.cpp
> +    if (xrt_core::config::get_feature_toggle(Debug_Bo_From_Elf_Feature)) {
Can you invert the check and do an early exit?

2024-04-05 16:01 UTC, stsoe approved these changes

2024-04-05 16:28 UTC, stsoe requested changes

2024-04-05 16:28 UTC, stsoe commented on src/runtime_src/core/common/api/xrt_module.cpp
> +  void
Hi @dezhiAmd .  The build is failing because the function is unused in release builds.
Please do this:
```suggestion
  XRT_CORE_UNUSED void
```

2024-04-05 21:48 UTC, merged