fix hipMalloc() issue when running in multithreads.
Xilinx/XRT pull request #8127
Opened 2024-05-01 08:03 UTC by zhangchiming

fix hipMalloc() issue when running in multithreads.

Problem solved by the commit
crash on calling hipMalloc() from multiple threads.

Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
Issue was found during developing unit testing case.

How problem was solved, alternative solutions (if any) and why they were rejected
Add lock for memory_database::remove() and  memory_database::insert(). Allow device_init() be called once per thread.

Risks (if any) associated the changes in the commit
None. Code will only be built with switch "-hip".

What has been tested and how, request additional testing if necessary
Compiled and tested on Ubuntu 22.04 running on Ryzen 7840.

Documentation impact (if any)
None.

2024-05-01 14:33 UTC, stsoe requested changes
Minor

2024-05-01 14:33 UTC, stsoe commented on src/runtime_src/hip/core/memory.cpp
> +    std::lock_guard<std::mutex> lock(m_mutex);
```suggestion
    std::lock_guard lock(m_mutex);
```

2024-05-01 14:33 UTC, stsoe commented on src/runtime_src/hip/core/memory.cpp
> +    std::lock_guard<std::mutex> lock(m_mutex);
```suggestion
    std::lock_guard lock(m_mutex);
```

2024-05-01 16:08 UTC, zhangchiming commented on src/runtime_src/hip/core/memory.cpp
> +    std::lock_guard<std::mutex> lock(m_mutex);
fixed

2024-05-01 16:08 UTC, zhangchiming commented on src/runtime_src/hip/core/memory.cpp
> +    std::lock_guard<std::mutex> lock(m_mutex);
fixed.

2024-05-01 16:10 UTC, stsoe approved these changes

2024-05-02 13:48 UTC, chvamshi-xilinx approved these changes

2024-05-02 13:49 UTC, merged

2024-05-02 13:51 UTC, chvamshi-xilinx reviewed
I missed one point. You need acquire lock in get_hip_mem_from_addr function also.
Please send a PR for that.