Global structure macro rename
Xilinx/XRT pull request #8169
Opened 2024-05-15 10:14 UTC by mnaguban

#### Problem solved by the commit
Total 3 commits:-
i)->  Added global platform structures for both USERPF & MGMTPF for all subdev files.
ii)-> Macro names added to subdev/ device files to differentiate between userpf and mgmtpf functions. 
iii)-> To separate userpf & mgmtpf modules, we used one flag instead of macro in the xocl_fdt blob functions.
#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered

#### How problem was solved, alternative solutions (if any) and why they were rejected

#### Risks (if any) associated the changes in the commit

#### What has been tested and how, request additional testing if necessary

#### Documentation impact (if any)

2024-05-15 10:14 UTC, gbuildx commented
mnaguban - is not a collaborator 
 Can XRT admins please validate PR

2024-05-15 10:16 UTC, gbuildx commented
Can one of the admins verify this patch?

2024-05-29 08:35 UTC, gbuildx commented
mnaguban - is not a collaborator 
 Can XRT admins please validate PR

2024-05-29 14:17 UTC, stsoe requested changes
rebase ?  PR seems to have unrelated changes.

2024-07-24 10:20 UTC, closed without merging

2024-07-24 10:20 UTC, chvamshi-xilinx commented
Closing as these changes are available in 2022.2