Custom kernel Makefile changes
Xilinx/XRT pull request #8173
Opened 2024-05-16 09:15 UTC by rmeridoddi

#### Problem solved by the commit
Userpf/ and Mgmtpf/ Makefile changes for custom kernel source to build 
#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered

#### How problem was solved, alternative solutions (if any) and why they were rejected

#### Risks (if any) associated the changes in the commit

#### What has been tested and how, request additional testing if necessary

#### Documentation impact (if any)

2024-05-16 09:15 UTC, gbuildx commented
rmeridoddi - is not a collaborator 
 Can XRT admins please validate PR

2024-05-16 09:16 UTC, gbuildx commented
Can one of the admins verify this patch?

2024-05-16 14:16 UTC, stsoe requested changes
This PR does not match the description.  There are many more changes.

2024-05-20 14:37 UTC, stsoe commented
Closing and asking for re-do.

2024-05-20 14:37 UTC, closed without merging

2024-05-22 06:49 UTC, rmeridoddi commented
Thanks for comment. Will update the description accordingly.