VITIS-11750 Create a wrapper (e.g. npu-smi) on top of xbutil
Xilinx/XRT pull request #8191
Opened 2024-05-21 20:35 UTC by rchane

#### Problem solved by the commit
https://jira.xilinx.com/browse/VITIS-11750
Create a wrapper (e.g. npu-smi) on top of xbutil for npu management and monitoring
#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
N/A
#### How problem was solved, alternative solutions (if any) and why they were rejected
Enabled npu-smi while keeping an "xbutil" backdoor for commands as described in the ticket. On both Linux and Windows, one can use either "npu-smi" or "xbutil" before xbutil commands.
#### Risks (if any) associated the changes in the commit
Possible documentation change. Should not break old tests as "xbutil" is still allowed.
#### What has been tested and how, request additional testing if necessary
`npu-smi/npu-smi.bat examine/configure/validate` and `xbutil/xbutil.bat examine/configure/validate` on MCDM/Strix works. `npu-smi examine/configure/validate` and `xbutil examine/configure/validate` on Linux works.
#### Documentation impact (if any)
Possibly need to update that "npu-smi" can replace "xbutil" in the cmd line

2024-05-22 06:04 UTC, AShivangi commented on src/runtime_src/core/tools/xbutil2/npu-smi
> +        echo "----------------------------------------------------------------------"
We don't need this anymore, but is there a way we can do something like this for "xbutil"? So if someone uses xbutil, we should inform them that this is a deprecated toolname, please use "npu-smi

2024-05-22 06:06 UTC, AShivangi commented
Overall it looks good, but waiting on the final decision for now.

2024-06-04 18:28 UTC, AShivangi approved these changes

2024-06-04 18:29 UTC, AShivangi commented
@stsoe, can you please look at this PR?

2024-06-04 18:33 UTC, stsoe reviewed
I am a little confused here?  Aren't we renaming `xbutil` to `xrt-smi`?  If so I imagine the the executable should be renamed to `xrt-smi` and that we provide xbutil scripts for backwards compatibility?

2024-06-05 21:05 UTC, AShivangi requested changes
Thanks for the verbose description!

Let's cleanup the new xrt-smi script and we should be good!

2024-06-05 21:05 UTC, AShivangi commented on src/runtime_src/core/tools/xbutil2/xrt-smi
> +done
no one uses legacy anymore. We don't need this while loop

2024-06-10 15:20 UTC, stsoe approved these changes
Thank you for good detailed PR description.  This looks good.

2024-06-10 16:14 UTC, chvamshi-xilinx approved these changes
Looks good.

2024-06-10 16:14 UTC, merged