Add changes to support xrt::elf based flows in HIP
Xilinx/XRT pull request #8206
Opened 2024-05-31 13:02 UTC by rbramand-xilinx

#### Problem solved by the commit
Added changes to support xrt::elf based flow in HIP. 
https://confluence.amd.com/display/AIE/HIP+Architecture#HIPArchitecture-proposal-2  - this page explains the proposal of the solution
Traditional test cases without elf are not supported any more.

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
#### How problem was solved, alternative solutions (if any) and why they were rejected
Two proposals are discussed in confluence page provided, going with proposal 2 as it is convenient and doesn't deviate from original HIP application flow

#### Risks (if any) associated the changes in the commit
Low

#### What has been tested and how, request additional testing if necessary
Tested by running HIP application on RyzenAI in Linux

#### Documentation impact (if any)
NA

2024-05-31 14:37 UTC, stsoe requested changes

2024-05-31 14:37 UTC, stsoe commented on src/runtime_src/hip/core/module.cpp
> +module_xclbin(std::shared_ptr<context> ctx, const std::string& file_name)
```suggestion
module_xclbin(const std::shared_ptr<context>& ctx, const std::string& file_name)
```
Either move into module ctor or receive by const ref and let module ctor move as it already does.

2024-05-31 14:37 UTC, stsoe commented on src/runtime_src/hip/core/module.h
> +  xrt::ext::kernel m_kernel;
```suggestion
  xrt::kernel m_kernel;
```
xrt::ext::kernel is just for construction, but assignment should be to xrt::kernel.  You can remove the default xrt::ext::kernel ctor.

2024-05-31 14:37 UTC, stsoe commented on src/runtime_src/hip/core/module.cpp
> +  m_kernel = xrt::ext::kernel{m_module->get_hw_context(), xrt_module, name};
This should be done in initializer list line 39.
, m_kernel{xrt::ext::kernel{m_module->get_hw_context(), xrt_module, name}};

I think #8198 unfortunately implicitly removed the move-ctor from xrt::kernel, which we should add back in, but this shouldn't matter for you, it's just an unnecessary reference count update.

2024-06-03 11:03 UTC, chvamshi-xilinx reviewed
Functionality is looking good. Feedback about member variable names and const-ness of member functions.

2024-06-03 11:03 UTC, chvamshi-xilinx commented on src/runtime_src/hip/core/module.h
> +  bool m_xclbin_type;
rename. m_is_xclbin?

2024-06-03 11:03 UTC, chvamshi-xilinx commented on src/runtime_src/hip/core/module.h
> +  get_hw_context()
const?

2024-06-03 11:03 UTC, chvamshi-xilinx commented on src/runtime_src/hip/core/module.h
> +  get_xclbin_module() const { return m_xclbin_module; }
const?

2024-06-03 11:03 UTC, chvamshi-xilinx commented on src/runtime_src/hip/core/module.h
> +  module_xclbin*
const?

2024-06-03 11:03 UTC, chvamshi-xilinx commented on src/runtime_src/hip/core/module.h
> +  const xrt::kernel&
const?

2024-06-03 11:47 UTC, chvamshi-xilinx approved these changes

2024-06-03 14:26 UTC, stsoe approved these changes

2024-06-03 16:22 UTC, merged