VITIS-11401 : Shim DMA based array reconfiguration overhead
Xilinx/XRT pull request #8308
Opened 2024-07-25 17:49 UTC by aktondak

#### Problem solved by the commit

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered

#### How problem was solved, alternative solutions (if any) and why they were rejected

#### Risks (if any) associated the changes in the commit

#### What has been tested and how, request additional testing if necessary

#### Documentation impact (if any)

2024-07-25 17:50 UTC, gbuildx commented
Can one of the admins verify this patch?

2024-07-30 18:05 UTC, AShivangi requested changes
Overall looks good. Some minor changes requested. Try this out with the validate xclbin and see if you get similar results!

2024-07-30 18:05 UTC, AShivangi commented on src/runtime_src/core/tools/common/tests/TestArrayReconfOverhead.cpp
> +    exit(EXIT_FAILURE);
use xrt_core::error

2024-07-30 18:05 UTC, AShivangi commented on src/runtime_src/core/tools/common/tests/TestArrayReconfOverhead.cpp
> +	for (size_t i = 0; i < word_count; i++)
indentation

2024-07-30 18:05 UTC, AShivangi commented on src/runtime_src/core/tools/common/tests/TestArrayReconfOverhead.cpp
> +  float overhead = elapsedSecs - elapsedSecsAverage;
All this goes in verbose

2024-07-30 18:05 UTC, AShivangi commented on src/runtime_src/core/tools/common/tests/TestArrayReconfOverhead.cpp
> +}
Add a newline at the end of file

2024-07-30 18:05 UTC, AShivangi commented on src/runtime_src/core/tools/common/tests/TestArrayReconfOverhead.h
> +#endif
same

2024-07-30 18:57 UTC, AShivangi commented
Oh we have another test "aie-config-latency" so we need to name this something else like "aie-reconfig-overhead"

2024-08-02 20:04 UTC, rchane requested changes

2024-08-02 20:04 UTC, rchane commented on src/runtime_src/core/tools/common/tests/TestAIEReconfigOverhead.cpp
> +  boost::property_tree::ptree ptree = get_test_header();
Please do ptree.erase("xclbin") after get_test_header() as part of our hotfix to remove the empty xclbin field from the json; you can verify this by checking the json output! We'll fix this with a better approach soon.

2024-08-05 16:06 UTC, AShivangi commented on src/runtime_src/core/tools/common/tests/TestAIEReconfigOverhead.cpp
> +    exit(EXIT_FAILURE);
let's not use exit()

2024-08-06 16:31 UTC, AShivangi requested changes
A few last comments. 
Did you experiment with different buffer sizes and iterations? Is this the least overhead that you could see?
Can you also check with Pranjal once if this number looks decent?

2024-08-06 16:31 UTC, AShivangi commented on src/runtime_src/core/tools/common/tests/TestAIEReconfigOverhead.cpp
> +    logger(ptree, "Details", boost::str(boost::format("ElapsedSecAverage: '%.1f' us") % (elapsedSecsAverage * 1000000)));
remove this print

2024-08-06 16:31 UTC, AShivangi commented on src/runtime_src/core/tools/common/tests/TestAIEReconfigOverhead.cpp
> +    logger(ptree, "Details", boost::str(boost::format("ElapsedSec: '%.1f' us") % (elapsedSecs * 1000000)));
Let's print this is seconds for consistency and instead of "ElapsedSec" let's name it "Total Duration"

2024-08-06 16:31 UTC, AShivangi commented on src/runtime_src/core/tools/common/tests/TestAIEReconfigOverhead.cpp
> +  logger(ptree, "Details", boost::str(boost::format("Overhead: '%.1f' us") % (overhead * 1000000)));
```suggestion
  logger(ptree, "Details", boost::str(boost::format("Array reconfiguration overhead: '%.1f' us") % (overhead * 1000000)));
```

2024-08-20 17:41 UTC, AShivangi commented on src/runtime_src/core/tools/common/tests/TestAIEReconfigOverhead.cpp
> +  logger(ptree, "Details", boost::str(boost::format("Array reconfiguration overhead: '%.7f's") % (overhead)));
Let's convert s to ms so it shows up as "3.4 ms" which is more readable and limit the decimal place to 1 for consistency with other tests

2024-08-20 17:42 UTC, AShivangi approved these changes
Looks good! One minor comment!

2024-08-21 23:50 UTC, stsoe approved these changes
LGTM

2024-08-21 23:50 UTC, merged