VITIS-13074 - Dump common control codes before and after being patched
Xilinx/XRT pull request #8338
Opened 2024-08-06 23:41 UTC by dezhiAmd

#### Problem solved by the commit
The overall goal is to provide a debugging method when there is a hang caused by control-codes.
Add one flag **dump-control-codes** in file xrt.ini Debug section. When this flags is true, no packet will be sent to Firmware, thus avoid any hang caused by TXN control codes. In the meantime, common control-codes before and after patching are dumped for users to further identify the issue.

Refer to this confluence page for spec: https://confluence.amd.com/x/8avhV
#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered

#### How problem was solved, alternative solutions (if any) and why they were rejected
1) when Dump-control-codes is true, in xrt_kernel.cpp, xrt::run_impl::start function will not execute cmdbuf, thus control codes will not be sent to firmware.
Same idea, when Dump-control-codes is true, wait function and wait_throw_on_error function will return immediately.
 
2) At the phase of creating xrt::device, Check whether Dump-control-codes is true. If yes, record it in xrt::device::m_debug_mode. The reason is to ensure critical path does not need to check whether Dump-control-codes is true. So we can enable this debug mode for anyone using XRT in release mode
#### Risks (if any) associated the changes in the commit

#### What has been tested and how, request additional testing if necessary

#### Documentation impact (if any)
The new entry in xrt.ini needs to be documented

2024-08-08 18:01 UTC, maxzhen approved these changes

2024-08-08 18:35 UTC, stsoe requested changes

2024-08-08 18:35 UTC, stsoe commented on src/runtime_src/core/common/api/xrt_module.cpp
> +  static uint32_t s_id; //TODO: it needs come from the elf file
Don't you need this as a regular non static data member.   The value is associated with the object (module_sram) once created.   If you use the static it is not specific to this object hence all the dump file names could be wrong.

```suggestion
  uint32_t m_id {0}; //TODO: it needs come from the elf file
```

2024-08-08 18:35 UTC, stsoe commented on src/runtime_src/core/common/api/xrt_module.cpp
> +uint32_t module_sram::s_id = 0;
Remove

2024-08-08 18:35 UTC, stsoe commented on src/runtime_src/core/common/api/xrt_module.cpp
> +    s_id++;
```suggestion
    static std::atomic<uint32_t> s_id {0}
    m_id = s_id++;
    
    m_debug_mode.debug_flags.dump_control_codes = xrt_core::config::get_feature_toggle("Debug.dump_control_codes");
    m_debug_mode.debug_flags.dump_control_packet = xrt_core::config::get_feature_toggle("Debug.dump_control_packet");
    m_debug_mode.debug_flags.dump_preemption_codes = xrt_core::config::get_feature_toggle("Debug.dump_preemption_codes");
```

2024-08-08 18:35 UTC, stsoe commented on src/runtime_src/core/common/api/xrt_module.cpp
> +    return s_id;
```suggestion
    return m_id;
```

2024-08-09 15:23 UTC, larry9523 approved these changes

2024-08-21 15:04 UTC, merged