XRT OS Support for Ubuntu 24.04. Removed one element arrays in the driver code
Xilinx/XRT pull request #8381
Opened 2024-08-29 09:09 UTC by ManojTakasi

#### Problem solved by the commit
https://jira.xilinx.com/browse/VITIS-12053 XRT OS Support for Ubuntu 24.04

This is an intial PR to move to flexible arrays instead of one length array in structures. Reference: https://www.kernel.org/doc/html/latest/process/deprecated.html#zero-length-and-one-element-arrays

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
Removed mmap xocl_gem_prime_mmap function as drm_gem_mmap() function  is capible of setting flags before mmap.

#### How problem was solved, alternative solutions (if any) and why they were rejected
Removed the xocl_gem_prime_mmap and changed some structures into flexible arrays as one-legth arrays are throwing call trace while using memcpy() function.

#### Risks (if any) associated the changes in the commit
low

#### What has been tested and how, request additional testing if necessary
Tested with u250 in ubuntu 22.04 and 24.04

#### Documentation impact (if any)
Yes

2024-08-29 11:18 UTC, chvamshi-xilinx requested changes
As discussed, please try to create  a macro instead of calling sizeof in lot of places.

2024-08-29 12:03 UTC, ManojTakasi commented
Hi Vamshi, as suggested used struct_size in all the places.

2024-08-29 16:22 UTC, keryell commented
I do not understand the reference to VLA here.
Where are the VLA in the code?

2024-08-29 16:46 UTC, keryell commented
Just to clarify, the "flexible array" is a coding convention, like VLA () are a C99 features made optional starting with C11
https://en.wikipedia.org/wiki/Variable-length_array
```c
int n = 42;
float a[n];
```
It is not in C++ because you cannot have `sizeof(a)` not being `constexpr`.

2024-08-29 17:15 UTC, ManojTakasi commented
Hi Keryell, Thanks for your clarification. Sorry for referencing wrong link. Please check this link: https://www.kernel.org/doc/html/latest/process/deprecated.html#zero-length-and-one-element-arrays

2024-08-30 05:35 UTC, chvamshi-xilinx commented on src/runtime_src/core/pcie/driver/linux/xocl/userpf/xocl_drv.c
> +	mbret = xocl_peer_request(xdev, &mbreq, sizeof(mbreq) + sizeof(int32_t),
struct_size here aswell?

2024-08-30 07:02 UTC, chvamshi-xilinx approved these changes

2024-08-30 10:24 UTC, merged