Vitis 13170 - Allow setting thread CPU affinity for XRT applications on Windows
Xilinx/XRT pull request #8437
Opened 2024-09-19 18:26 UTC by diukirde

#### Problem solved by the commit
We want to set cpu affinity for threads on Windows like we do currently for Linux. 
#### Issue
https://jira.xilinx.com/browse/VITIS-13170
#### How problem was solved
Using the APIs provided by windows - SetThreadAffinityMask function (winbase.h)

#### What has been tested and how
cpu_affinity is being honored from xrt.ini. Verified affinity mask calculation seems to be accurate. No error in the API call observed.

![cpu_affinity](https://github.com/user-attachments/assets/244c76a7-7025-4de0-a8aa-d183c2e7078a)

#### Documentation impact (if any)
None

2024-09-19 18:28 UTC, gbuildx commented
Can one of the admins verify this patch?

2024-09-19 18:30 UTC, AShivangi commented
Do we want to show this in host report? We used to have it, but it has been removed since

2024-09-19 18:49 UTC, stsoe requested changes

2024-09-19 18:49 UTC, stsoe commented on src/runtime_src/core/common/thread.cpp
> +  static bool all = false;
Let's fix this here and for Linux as well.  Remove this `all` variable and replace all occurrences of `all = true;` with `return;`.  Drop the outer `else` and reduce indentation with early-exit.

2024-09-19 18:49 UTC, stsoe commented on src/runtime_src/core/common/thread.cpp
> +    }
```suggestion
    if (cpus == "default")
      return;

```

2024-09-19 18:49 UTC, stsoe commented on src/runtime_src/core/common/thread.cpp
> +    else {
Remove and reduce identation.
```suggestion
```

2024-09-19 18:49 UTC, stsoe commented on src/runtime_src/core/common/thread.cpp
> +    return;
Not needed.
```suggestion
```

2024-09-19 18:49 UTC, stsoe commented on src/runtime_src/core/common/thread.cpp
> +          all = true;
```suggestion
          return;
```

2024-09-19 18:49 UTC, stsoe commented on src/runtime_src/core/common/thread.cpp
> +  static DWORD_PTR affinityMask = 0;
user space code never uses camelCase; of course windows functions are CamelCase, but variables we create should not be.

2024-09-19 18:49 UTC, stsoe commented on src/runtime_src/core/common/thread.cpp
> +  }
```suggestion
  if (!SetThreadAffinityMask(threadHandle, affinityMask))
    throw std::runtime_error("error calling SetThreadAffinityMask");
```

2024-09-19 18:49 UTC, stsoe commented on src/runtime_src/core/common/thread.cpp
> +      auto max_cpus = GetMaximumProcessorCount(ALL_PROCESSOR_GROUPS);
Does `std::thread::hardware_concurrency` not work?

2024-09-19 19:46 UTC, stsoe approved these changes
LGTM.  Some opportunity for refactoring of code shared between Linux and Windows, but no big deal.

2024-09-30 22:43 UTC, stsoe approved these changes
Looks good :-)  So sorry for the confusion.

2024-09-30 22:44 UTC, merged