proper cleanup of Aie context
Xilinx/XRT pull request #8446
Opened 2024-09-24 10:33 UTC by SravanKumarAllu-xilinx

#### Problem solved by the commit

shim is getting destroyed before Aie

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered

N/A

#### How problem was solved, alternative solutions (if any) and why they were rejected

resetting Aie in shim's destructor

#### Risks (if any) associated the changes in the commit

N/A

#### What has been tested and how, request additional testing if necessary

graph test cases with device / hwcontext

#### Documentation impact (if any)

N/A

2024-09-24 10:34 UTC, gbuildx commented
Can one of the admins verify this patch?

2024-09-24 14:58 UTC, stsoe reviewed
LGTM.  One comment.  It is not very common to compare a  ptr against nullptr in a conditional.  `!= nullptr` or `== nullptr` is not needed.

2024-09-24 16:02 UTC, chvamshi-xilinx requested changes
Can you please explain the ownership of all these objects. Is my below understand correct? if yes, why do we need to manage these shared_pointers by calling reset etc?
graph is going to have a reference of hw_context
AieArray is going to have a reference of hw_context
hw_context is going to have a reference of core_device.

2024-09-25 07:37 UTC, SravanKumarAllu-xilinx commented
Due to difficulty in resolving merge conflicts , deleting this PR and rasing new PR with updated feedback comments

2024-09-25 07:37 UTC, closed without merging