Temporal Sharing Overhead Benchmark Test
Xilinx/XRT pull request #8457
Opened 2024-09-25 20:59 UTC by aktondak

#### Problem solved by the commit
https://jira.xilinx.com/browse/VITIS-12999 : Temporal Sharing Overhead Benchmark Test

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
https://jira.xilinx.com/browse/VITIS-12999

#### How problem was solved, alternative solutions (if any) and why they were rejected
The enhancement was made via a 2-phase test comparison between 2 threaded 2 hardware context run and a multi-threaded temporally shared hardware contexts to calculate time overhead. More details :
https://confluence.amd.com/display/~aktondak/spatial+sharing+overhead+via+xrt-smi+validate
```
Verbose: Enabling Verbosity
Test 1 [00c5:00:01.1]     : temporal-sharing-overhead
    Description           : Run Temporal Sharing Overhead Test
    Xclbin                : C:\WINDOWS\System32\DriverStore\FileRepository\ipukmddrv.inf_amd64_a38cb2a3e688a71e\validate_17f0_20.xclbin
    Details               : Kernel name is 'DPU_1x4'
                            Spatially shared contexts latency: '209.5' ms
                            Temporally shared contexts latency: '311.7' ms
                            Overhead: '102.2' ms
    Test Status           : [PASSED]
```
#### Risks (if any) associated the changes in the commit
None

#### What has been tested and how, request additional testing if necessary
Needs testing from DSV

#### Documentation impact (if any)
None

2024-09-25 21:00 UTC, gbuildx commented
Can one of the admins verify this patch?

2024-09-25 21:12 UTC, AShivangi requested changes

2024-09-25 21:12 UTC, AShivangi commented on src/runtime_src/core/tools/common/tests/TestTemporalSharingOvd.cpp
> +  const auto xclbin_name = xrt_core::device_query<xrt_core::query::xclbin_name>(dev, xrt_core::query::xclbin_name::type::validate);
We need to add the set_threshold() else the test won't work

2024-09-25 21:12 UTC, AShivangi commented on src/runtime_src/core/tools/common/tests/TestTemporalSharingOvd.cpp
> +  ptree.put("status", test_token_passed);
check if benchmark is in range

2024-10-01 15:56 UTC, AShivangi commented
What's the variance when the test is run in validate back to back and when it is run by itself?

2024-10-01 18:45 UTC, aktondak commented
> What's the variance when the test is run in validate back to back and when it is run by itself?

The standard deviation with current parameters used for 10 subsequent runs is 13.9ms with a mean of 4300 (~0.3%)

2024-10-01 19:39 UTC, AShivangi approved these changes

2024-10-11 17:59 UTC, closed without merging