close aie context cleanup in shim
Xilinx/XRT pull request #8479
Opened 2024-10-01 11:22 UTC by SravanKumarAllu-xilinx

#### Problem solved by the commit

shim is getting destroyed before Aie

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered

N/A

#### How problem was solved, alternative solutions (if any) and why they were rejected

resetting Aie in shim's destructor

#### Risks (if any) associated the changes in the commit

N/A

#### What has been tested and how, request additional testing if necessary

graph test cases including profiling with device / hwcontext

#### Documentation impact (if any)

N/A

2024-10-01 11:24 UTC, gbuildx commented
Can one of the admins verify this patch?

2024-10-01 15:12 UTC, stsoe requested changes

2024-10-01 15:12 UTC, stsoe commented on src/runtime_src/core/edge/user/shim.cpp
> +  if(m_aie_array == nullptr)
```suggestion
  if (!m_aie_array)
```

2024-10-01 15:12 UTC, stsoe commented on src/runtime_src/core/edge/user/shim.cpp
> +  return (m_aie_array != nullptr);
Here the comparison can be argued to clarify the meaning of what it means to be registered, so this one I would leave.

2024-10-03 15:14 UTC, stsoe reviewed
Looks good, minor tweaks.

2024-10-03 15:14 UTC, stsoe commented on src/runtime_src/core/edge/user/aie/aie_buffer_object.cpp
> +  aie_buffer_object::aie_buffer_object(xrt_core::device* device ,const xrt::uuid uuid, const char* buffer_name, zynqaie::hwctx_object* hwctx)
```suggestion
  aie_buffer_object::aie_buffer_object(xrt_core::device* device, const xrt::uuid uuid, const char* buffer_name, zynqaie::hwctx_object* hwctx)
```

2024-10-03 15:14 UTC, stsoe commented on src/runtime_src/core/edge/user/aie/aie_buffer_object.h
> +    aie_buffer_object(xrt_core::device* device , const xrt::uuid uuid, const char* name, zynqaie::hwctx_object* hwctx=nullptr);
```suggestion
    aie_buffer_object(xrt_core::device* device, const xrt::uuid uuid, const char* name, zynqaie::hwctx_object* hwctx=nullptr);
```

2024-10-03 15:14 UTC, stsoe commented on src/runtime_src/core/edge/user/device_linux.cpp
> +  if (int ret; ret = drv->openAIEContext(am))
```suggestion
  if (int ret = drv->openAIEContext(am))
```

2024-10-03 15:14 UTC, stsoe commented on src/runtime_src/core/edge/user/device_linux.cpp
> +  auto aie_array = drv->get_aie_array_shared();
```suggestion
  if (!drv->isAieRegistered())
    throw xrt_core::error(-EINVAL, "No AIE presented");
    
  auto aie_array = drv->get_aie_array_shared();
```

2024-10-04 10:15 UTC, chvamshi-xilinx approved these changes

2024-10-04 10:15 UTC, merged