TestRunner code cleanup
Xilinx/XRT pull request #8571
Opened 2024-10-25 06:32 UTC by aktondak

#### Problem solved by the commit
This code cleans up the TestRunner class by moving all the APIs which do not belong there to the TestValidateUtilities namespace.
This code clean-up is an effort towards building the runner recipe based xrt-smi validate test. This will facilitate the following.
1. Usage of APIs freely out of the TestRunner class hierarchy as well.
2. Making TestRunner objects lightweight since every validate test spawns a TestRunner object upon creation.
3. Allow for code re-use between multiple xrt-smi validate tests.

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered
https://jira.xilinx.com/browse/VITIS-13774

#### How problem was solved, alternative solutions (if any) and why they were rejected

#### Risks (if any) associated the changes in the commit

#### What has been tested and how, request additional testing if necessary

#### Documentation impact (if any)

2024-10-25 06:34 UTC, gbuildx commented
Can one of the admins verify this patch?

2024-10-29 16:46 UTC, AShivangi requested changes
I think this is a good start. Some comments. 

In the next iteration, we should separate out the boiler plate code, like "init_hw_context", "init_BO" etc. All these can live in XBValidateUtils

2024-11-01 19:21 UTC, aktondak commented on src/runtime_src/core/tools/common/tests/TestBist.cpp
> +#include "TestValidateUtilities.h"
Max pointed to a confirmation from @chvamshi-xilinx 
Waiting for reply to decide on this clean-up

2024-11-10 21:41 UTC, aktondak commented on src/runtime_src/core/tools/common/tests/TestValidateUtilities.cpp
> +std::string
Cleaned up after confirmation

2024-11-11 16:47 UTC, AShivangi commented on src/runtime_src/core/tools/common/tests/TestPsIops.cpp
> +#include "TestValidateUtilities.h"
Please remove this testcase as well

2024-11-20 17:01 UTC, AShivangi commented on src/runtime_src/core/tools/common/tests/TestValidateUtilities.cpp
> +std::string
Waiting to make sure if we still support any of the legacy devices, before this PR is ready for merge

2024-11-25 17:59 UTC, merged