Vitis 13804
Xilinx/XRT pull request #8656
Opened 2024-12-12 23:32 UTC by aktondak

#### Problem solved by the commit

#### Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered

#### How problem was solved, alternative solutions (if any) and why they were rejected

#### Risks (if any) associated the changes in the commit

#### What has been tested and how, request additional testing if necessary

#### Documentation impact (if any)

2024-12-12 23:34 UTC, gbuildx commented
Can one of the admins verify this patch?

2024-12-13 04:23 UTC, stsoe requested changes

2024-12-13 04:23 UTC, stsoe commented on src/runtime_src/core/tools/xbutil2/SubCmdJsonObjects.cpp
> +#include <iostream>
This file is missing copyright and for sure many includes.  Please include-what-you-use, e.g. do no rely on indirect includes and never include more than what you use.

2024-12-13 04:23 UTC, stsoe commented on src/runtime_src/core/tools/xbutil2/SubCmdJsonObjects.cpp
> +}
Missing new line

2024-12-13 04:23 UTC, stsoe commented on src/runtime_src/core/tools/xbutil2/SubCmdJsonObjects.h
> +// Copyright (C) 2022-2024 Advanced Micro Devices, Inc. All rights reserved.
This is a new file, right?  How come copyright starts at 2022?

2024-12-13 04:23 UTC, stsoe commented on src/runtime_src/core/tools/xbutil2/SubCmdJsonObjects.h
> +};
Never use UPPERCASE for class enumerators; these are bound to be replaced by some stupid braindead macro from some place.  Class enumerators are scoped, so keep them lower case and short like you have them here.

2024-12-13 04:23 UTC, stsoe commented on src/runtime_src/core/tools/xbutil2/xrt_smi_config.json
> +{
Copyright and license.

2024-12-13 04:23 UTC, stsoe commented on src/runtime_src/core/tools/xbutil2/xrt_smi_config.json
> +}
new line

2025-01-09 00:02 UTC, aktondak commented on src/runtime_src/core/tools/xbutil2/xrt_smi_config.json
> +{
Resolved as file is no longer required

2025-01-10 17:32 UTC, rchane approved these changes
After initial discussion, this PR seems good to me for our first step of re-architecture once it is ironed out and passes pipeline.

2025-01-14 19:49 UTC, AShivangi commented on src/runtime_src/core/tools/xbutil2/SubCmdValidate.h
> +  std::string m_device;
let's remove m_ in the next iteration of changes

2025-01-14 19:50 UTC, AShivangi approved these changes
Looks good for the first iteration! Let's get this in asap so we can start some bash testing

2025-01-14 20:14 UTC, stsoe requested changes

2025-01-14 20:14 UTC, stsoe commented on src/runtime_src/core/pcie/linux/smi.cpp
> +} // namespace xrt_core::smi
newline

2025-01-14 20:14 UTC, stsoe commented on src/runtime_src/core/pcie/linux/smi.h
> +} // namespace xrt_core::smi
newline

2025-01-14 20:14 UTC, stsoe commented on src/runtime_src/core/tools/common/SubCmdJsonObjects.h
> +#include "boost/program_options.hpp"
Use angle brackets for system headers (headers not local to xrt repo).

2025-01-14 20:14 UTC, stsoe commented on src/runtime_src/core/tools/common/SubCmdJsonObjects.h
> +#include <unordered_map>
Is there any reason to use std::unordered_map over std::map?  It's fine, but beware that unordered_map is "unordered" meaning the order of items is platform dependent.  This is okay as long as you don't rely on the order in a way it affects output (visual).

2025-01-14 20:14 UTC, stsoe commented on src/runtime_src/core/tools/common/SubCmdJsonObjects.h
> +static constexpr std::string_view const_options_literal = "options";
IMO, you'd be better off moving these to SubCmdJsonObjects.cpp along with the inline functions that use these.

2025-01-14 20:14 UTC, stsoe commented on src/runtime_src/core/tools/common/SubCmdJsonObjects.h
> +
I think move to .cpp a namespaced static global.

2025-01-14 20:14 UTC, stsoe commented on src/runtime_src/core/tools/common/SubCmdJsonObjects.h
> +  std::unordered_map<std::string, SubCommand>
Ditto... unordered

2025-01-14 21:16 UTC, aktondak commented on src/runtime_src/core/tools/common/SubCmdJsonObjects.h
> +#include <unordered_map>
The function of these maps for now is only for look-up retrieval, thus for a faster query I've kept it as unordered. Though given the small size of data being stored, I agree it would not be a considerable runtime advantage in current state. I'll switch to std::map when we need iterating over these maps and visually printing them.

2025-01-14 22:12 UTC, aktondak commented on src/runtime_src/core/tools/common/SubCmdJsonObjects.h
> +static constexpr std::string_view const_options_literal = "options";
Moved.

2025-01-15 18:02 UTC, stsoe approved these changes

2025-01-15 18:02 UTC, merged